### ISSUE TITLE
There is no way to have Flux automated images in Helm subcharts with multiple containers

### ISSUE THREAD

**Issue by svinther** [fluxcd/flux#1629]
The Helm convention for specifying values for subcharts is like

```
subchart:
  container1:
    image:
    tag:
  container2:
    image:
    tag:
```

But Flux does not recognize image spec structures on any sublevel of the values.yaml

Same problem for nested subcharts with only 1 container in the subchart, as the Helm convention is

```
subchart1:
  subchart2:
    image:
    tag:
```

**Comment by stefanprodan** [comment]
Duplicate of #1262

**Comment by timwebster9** [comment]
I'm slightly confused - doesn't [this](https://github.com/weaveworks/flux/blob/master/site/helm-integration.md#upgrading-images-in-a-helmrelease-using-flux) say it's supported at least partially:
```
values:
  persistent: true

  # image that will be labeled "chart-image"
  image: repo/image1:version

  subsystem:
    # image that will be labeled "subsystem"
    image:
      repository: repo/image2
      tag: version
      imagePullPolicy: IfNotPresent
    port: 4040
```
Having said that, I'm trying something similar and can't seem to get it to work...
