### ISSUE TITLE
mergeValues doesn't merge values inside of maps

### ISSUE THREAD

**Issue by jfrndz** [fluxcd/flux#1696]
Running flux 1.9.0 and flux-helm-operator 0.5.3

I ran into this issue while trying to configure a HelmRelease that combines values from the `values` key with sensitive values from a `valuesFileSecret`. As an example, given the following values:
```
# values.yaml in a valuesFileSecret:
mychart:
  api_client_id: CLIENT_ID
  api_secret: SECRET_TOKEN
---
# spec.values in a HelmRelease:
mychart:
  image: my-registry/myapp:1.0.0
  ...
```
I was expecting that these would be combined like so before being applied to the helm release:
```
mychart:
  api_client_id: CLIENT_ID
  api_secret: SECRET_TOKEN
  image: my-registry/myapp:1.0.0
  ...
```
However, the resulting values reported by `helm get` _only_ include the keys in spec.values. This merging works for top-level keys in values YAMLs, so it only seems to affect keys inside of maps. Looking at the implementation of `mergeValues` in `flux/integrations/helm/release/release.go:274` I get the impression that keys inside of maps were intended to be combined this way. 

I'm able to work around this issue by avoiding these kinds of merges but it would be nice to be able to combine values this way. For instance, I could use a separate valueFileSecret for each set of API tokens.
