### ISSUE TITLE
Missing documentation for annotations

### ISSUE THREAD

**Issue by eimarfandino** [fluxcd/flux#1778]
I miss in the flux documentation a full list of the different types of annotations that can be used. I see two examples but not a clear list of what can be used.

here the examples that are documented: 
* https://github.com/weaveworks/flux/blob/91ec3fd66782289407bc88ca15885102dc52d9f3/site/fluxctl.md#using-annotations 
* https://github.com/weaveworks/flux/blob/c2dfbf585252657b4ea4f0c4c54d4fe0c9d5bacf/site/annotations-tutorial.md

**Comment by stefanprodan** [comment]
I'll make the list here and do a PR for it after we decide on #1262

On/off:

```yaml
# container image automated updates
flux.weave.works/automated: "true"

# lock image updates even if automated is enabled
flux.weave.works/locked: "true"
flux.weave.works/locked_msg: "Halt updates for now, latest release is buggy"
flux.weave.works/locked_user: "Stefan Prodan <stefan@example.com>"

# do not apply this manifest on the cluster
flux.weave.works/ignore: "true"
```

Container image filters (automated must be enabled):

```yaml
# semantic versioning
flux.weave.works/tag.<container-name>: semver:<expression>

# glob 
flux.weave.works/tag.<container-name>: glob:<expression>

# regular expression 
flux.weave.works/tag.<container-name>: regexp:<expression>
```
