### ISSUE TITLE
Auto updating failing memcached issue

### ISSUE THREAD

**Issue by montyz** [fluxcd/flux#1897]
I noticed that some of our new docker tags weren't pulled automatically like they should have been. 

I didn't see any errors in the flux logs. 

So I upgraded from 1.10.1 to 1.11.1 and no change.

Then I increased the memcached settings and restarted both:

```
      - name: memcached
        image: memcached:1.4.25
        imagePullPolicy: IfNotPresent
        args:
        - -m 256    # Maximum memory to use, in megabytes. 64MB is default.
        - -p 11211    # Default port, but being explicit is nice.
        - -I 10m
```

That made it work.

An error message would be really helpful! https://github.com/weaveworks/flux/issues/1720 is related, and having that SERVER_ERROR message was very helpful.
