### ISSUE TITLE
kubectl patch function

### ISSUE THREAD

**Issue by phoppe93** [fluxcd/flux#1927]
Hey Flux Team,

is it possbile to patch managed deployment from kubernetes. 
for example i would add a pod priority at the managed eks coredns deployment. 
i would use kubectl patch coredns .......

how can add it to my flux repo ?

**Comment by hiddeco** [comment]
Is your question how you can sync a state from a manual `kubectl patch` back to git or how you can partially update a deployment?

The former is not possible, all changes have to be made through git and Flux will undo any mutations made to resources it manages by reapplying state.

The later is possible as Flux performs a `kubectl apply -f`, this does a [merge patch calculation](https://kubernetes.io/docs/concepts/overview/object-management-kubectl/declarative-config/#merge-patch-calculation), and it is thus possible to add a manifest to git which only defines the values you want to change/patch.

**Comment by stefansedich** [comment]
@hiddeco so the following should be safe then to manage updating the image version only for the coredns deployment?

```
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: coredns
spec:
  template:
    spec:
      containers:
        image: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/coredns:v1.2.6
```
