### ISSUE TITLE
Automatic image update changes feature tags

### ISSUE THREAD

**Issue by autarchprinceps** [fluxcd/flux#1938]
The last automatic image update changed this for us:
```
-        image: fluent/fluentd-kubernetes-daemonset:v1.3-debian-graylog
+        image: fluent/fluentd-kubernetes-daemonset:v1.3-debian-elasticsearch-1
```
That is not an update, that is a different feature set. It will not work in the same circumstance. It's not even alphabetically greater.

**Comment by 2opremio** [comment]
@autarchprinceps Can you share the full resource definition, I suspect it works in a different way than you think.

**Comment by autarchprinceps** [comment]
This is the DaemonSet with the correct image definition. In this case it is applied directly like this from the flux repo, not via HelmRelease.
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd-cloudwatch
  namespace: kube-system
  labels:
    k8s-app: fluentd-cloudwatch
spec:
  template:
    metadata:
      labels:
        k8s-app: fluentd-cloudwatch
    spec:
      serviceAccountName: fluentd
      terminationGracePeriodSeconds: 30
      initContainers:
      - name: copy-fluentd-config
        image: busybox:1-musl
        command: ['sh', '-c', 'cp /config-volume/..data/* /fluentd/etc']
        volumeMounts:
        - name: config-volume
          mountPath: /config-volume
        - name: fluentdconf
          mountPath: /fluentd/etc
      containers:
      - name: fluentd-cloudwatch
        image: fluent/fluentd-kubernetes-daemonset:v1.3.3-debian-graylog
        env:
        - name: REGION
          value: eu-central-1
        - name: CLUSTER_NAME
          value: dev-mgmt
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: config-volume
          mountPath: /config-volume
        - name: fluentdconf
          mountPath: /fluentd/etc
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: runlogjournal
          mountPath: /run/log/journal
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: fluentd-config
      - name: fluentdconf
        emptyDir: {}
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: runlogjournal
        hostPath:
          path: /run/log/journal
```
