### ISSUE TITLE
Flux should use kubeconfig supplied when installing it with helm

### ISSUE THREAD

**Issue by j-halbert** [fluxcd/flux#2015]
**Describe the bug**
Workload gives error when trying to update image: `manifest not found`

**To Reproduce**
Steps to reproduce the behaviour:
0. Flux installed with:
```
helm install \
  -f values.yaml \ 
  --name flux-dev \
  --tls \
  --set git.branch=develop \
  --set git.path="com/myapp" \
  --set helmOperator.allowNamespace=dev \
  --set nameOverride=flux-dev \
  --namespace weave \
  weaveworks/flux
```

`values.yaml`

```
rbac:
  create: true
serviceAccount:
  create: true
git:
  url: git@bitbucket.org:my-team/com.myapp.git
  ciSkip: true
helmOperator:
  create: true
kube:
  config: |
    apiVersion: v1
    clusters: []
    contexts:
    - context:
        cluster: ""
        namespace: dev
        user: ""
      name: default
    current-context: default
    kind: Config
    preferences: {}
    users: []
```

1. Deployment yaml (deployed by fluxd):

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: com-myapp-frontends-mockups
  labels:
    app: com-myapp-frontends-mockups
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.nginx: glob:0.0.*
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: com-myapp-frontends-mockups
    spec:
      containers:
        - name: nginx
          image: "000000000000.dkr.ecr.us-west-2.amazonaws.com/com.myapp.frontends.mockups:0.0.1-develop.1"
```

**Expected behavior**
1. Flux monitors docker repo & identifies new image available
2. Flux updates version in deployment yaml, saving changes to version control
3. Flux applies changes to updated deployment yaml and triggers rolling update

**Logs**
```
ts=2019-05-07T14:05:08.814130509Z caller=images.go:112 component=sync-loop workload=dev:deployment/com-myapp-frontends-mockups container=nginx repo=000000000000.dkr.ecr.us-east-2.amazonaws.com/com.myapp.frontends.mockups pattern=glob:0.0.* current=000000000000.dkr.ecr.us-east-2.amazonaws.com/com.myapp.frontends.mockups:0.0.1-develop.1 info="added update to automation run" new=000000000000.dkr.ecr.us-east-2.amazonaws.com/com.myapp.frontends.mockups:0.0.7-develop.1 reason="latest 0.0.7-develop.1 (2019-05-07 00:25:58.530354757 +0000 UTC) > current 0.0.1-develop.1 (2019-05-06 19:33:32.368680851 +0000 UTC)"
ts=2019-05-07T14:05:08.814204976Z caller=loop.go:111 component=sync-loop jobID=dd41d00f-9331-43e2-215e-7b2239d0adce state=in-progress
ts=2019-05-07T14:05:08.850178835Z caller=releaser.go:58 component=sync-loop jobID=dd41d00f-9331-43e2-215e-7b2239d0adce type=release updates=1
ts=2019-05-07T14:05:08.933433054Z caller=loop.go:121 component=sync-loop jobID=dd41d00f-9331-43e2-215e-7b2239d0adce state=done success=false err="applying changes: updating resource dev:deployment/com-myapp-frontends-mockups in com/myapp/frontends/mockups/k8s/deployment.yaml: manifest not found"
```

**Additional context**
- Flux version: 1.12.1 (server/operator); 1.12.0 (client/fluxctl)
- Helm Operator version: 0.8.0
- Kubernetes version: 1.11.9
- Git provider: Bitbucket
- Container registry provider: AWS ECR
- Running on EC2 instances in AWS
