### ISSUE TITLE
Flux doesn't update images consistently

### ISSUE THREAD

**Issue by koustubhg** [fluxcd/flux#2020]
**Describe the bug**
Flux doesn't auto-update images consistently (after an expected behaviour of a week or so)

**To Reproduce**
Steps to reproduce the behaviour:
Configure flux the same as original except the following diff
![image](https://user-images.githubusercontent.com/44349550/57342344-d896eb80-7181-11e9-984c-8336f7e5ef59.png)

The `HelmRelease` is as below:

```
---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: myapp
  namespace: dev
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: regexp:\b[0-9a-f]{7}\b
    flux.weave.works/tag.proxy: regexp:\b[0-9a-f]{7}\b
spec:
  chart:
    git: git@github.com:myorg/my-releases.git
    path: charts/myapp
    ref: master
  values:
    image:
      repository: asia.gcr.io/myproj/myservice1
      tag: "1d83c62"
    proxy:
      image:
        tag: 925726a
        repository: asia.gcr.io/myproj/myservice2
      pausingThreshold: 24h
      pausingGracePeriod: 1h
    replicaCount: 1
    istioSidecarInject: "true"
    prometheus:
      port: 10003
      enable: true
```
This config worked perfectly well for a week or so. However, after a week the docker images were stopped being automatically updated into the git repo and hence couldn't be deployed.
There were no errors on the `fluxd` pod.
**Workaround:** On restarting the flux pod, it did update as expected immediately
However, would like to know if there is any issue with the configuration.
The same issue was observed for other `HelmRelease` files as well.

**Expected behavior**
Flux should automatically update images in the git repo and perform release consistently whenever there is new image in the container registry.

**Logs**
No relevant logs

**Additional context**
Add any other context about the problem here, e.g 
- Flux version: 1.12.0
- Helm Operator version: 0.8.0
- Kubernetes version: 1.12.6-gke.10
- Git provider: github
- Container registry provider: Google Container Registry
