### ISSUE TITLE
Vault Integration with Helm

### ISSUE THREAD

**Issue by ghost** [fluxcd/flux#2038]
**Describe the feature**
One of the issues I have with Helm is the ability to pass secrets.  You usually have to do this part through the shell using --set and then have separate values file for the non sensitive values.  We can't do this when we use the helm operator and we can't commit sensitive values.  

It would be great if the vault operator could support a way to go and get those secrets from a secret management system like hashicorps vault, then pass them into the values.

This is more of a question if you think this feature would be worth while and if so I could look to write the code if I could be pointed in the right direction.

A rough example of how it could be used.

** Example **
```
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: myapp
  namespace:  mynamespace
spec:
  releaseName: myapp
  chart:
    git: https://github.com/helm/charts.git
    path: stable/jenkins
    ref: master
  vault:
    address: https://myvault.example.com
    auth_type: kubernetes
    secret_map:
      - admin
        path: secret/jenkins
        helm_value: administratorPassword 
```
0. What are the prerequisites for this?
 Maybe a configuration section to turn this feature on.

**Comment by squaremo** [comment]
There is some room for this kind of feature, in the way that the `valuesFrom` field is used. But before diving into that: can Vault put values into an ordinary Kubernetes secret? Then you could just use `.spec.valuesFrom.secretKeyRef` to refer to such a secret from the HelmRelease.

**Comment by simonmacklin** [comment]
Thanks @squaremo 

I am not aware of any vault functionality that could put a value from vault into a k8 secret.  Although that would be awesome.

For our own applications we build our apps to speak directly to vault or do something in a init container.  

This ask would be great for community charts, where sensitive values are required.

**Comment by ncabatoff** [comment]
> But before diving into that: can Vault put values into an ordinary Kubernetes secret? 

The whole idea of Vault is central management and control of secrets.  If you start pushing those secrets into k8s secrets, you lose the benefits that come with that centralization.  The secrets are now at greater risk, since they're stored less securely in etcd - by default without even encryption.  There's no longer an audit trail recording how they're accessed and by what.  Revocation can no longer be done immediately or reliably.  And so on.

That said, I think the proposal makes sense for the community charts use case.  Probably the reason no one's created a vault->k8ssecret gateway (besides the drawbacks I just listed) is that there's no mechanism to signal applications that they need to re-read an updated secret.  But here the mechanism to update secrets is to redeploy the application, which is heavy-handed but works.  

Is the plan is to have helm-operator poll Vault for the secrets, and changes would trigger a new deployment?  I guess that's not really required, as the user could always setup consul-template or something like that to monitor secrets and trigger a release when they change.  For now just being able to inject the secrets into a release would be awesome.

There are two ways Flux could bridge Vault and Kubernetes secrets.  The first is what you're proposing, i.e. providing values to charts so they can create secrets based on their templates.  I think that means that the secrets will be recorded in plaintext in helm's release history, which of course isn't great.  Alternatively, helm-operator could itself create the secrets to be consumed by charts, without persisting them in the release history.  This would be preferable from a security standpoint but I'm guessing that would decrease the number of community charts that could benefit from this feature.

Last thought: can we make the solution more generic rather than Vault specific?  Let's say we target REST APIs that yield JSON results, and we tweak your example a bit, with the assumption that a Vault Agent sidecar is deployed with Flux that save us from having to deal with authentication:

```
spec:
  releaseName: myapp
  chart:
    git: https://github.com/helm/charts.git
    path: stable/jenkins
    ref: master
  secret_source: https://example.com
  secrets:
    admin:
      request_path: v1/secret/data/jenkins
      response_jsonpath: data.data
    dbpass:
      request_path: v1/database/creds/mypg
      response_jsonpath: data
```

This would GET https://example.com/v1/secret/data/jenkins, parse the result as JSON, index the jsonpath data.data which would yield the JSON map corresponding to the [KV-V2](https://www.vaultproject.io/api/secret/kv/kv-v2.html) secret named `jenkins`, and build a secret named `admin` containing the corresponding key-value pairs that would be included in the release.

Then it would do similarly to create a secret named `dbpass` containing the username and password keyvals coming from a [DB secret engine](https://www.vaultproject.io/api/secret/databases/index.html) named `mypg`.
