### ISSUE TITLE
Support running multiple workloads in an environment via manifest generation

### ISSUE THREAD

**Issue by jrryjcksn** [fluxcd/flux#2197]
**Describe the feature**
Automated workloads often have very similar configurations with minor variations. Rather than require each of a set of such workloads have a distinct directory (i.e. `git-path`), it would be useful to support some way of specifying that particular patch files apply to particular workloads. One of our uses would like to have:

```
1) Can i have multiple automated workloads under same git.path directory , but use different patch files while using `patchUpdated`  ?
2) Also, I am assuming i can't do multiple .flux.yaml files per a given git path ?
```

because:

```
we want to use kustomize with flux for our automated workloads so that we reduce the 
duplication in our application config. But, we can't afford to have one directory per workload 
as they are too many to be in git.paths. Having single path file will make it too big with time and might turn unmanageable .
```

in support of:

```
~ 100 HelmReleases on each environment 
(using Kustomize to merge / override env specific config) ... 
with different behaviour as well (like different tag per env)
```

**What would the new user story look like?**
I believe this could be addressed by supporting multiple `.flux.yaml` files in a given directory (e.g. all files with names of the form `.<name>.flux.yaml` or some variation). Our user could have one for each distinct workload. Otherwise, things could work the same way they do now except each `.<name>.flux.yaml` found at the relevant level of the tree would be run to generate manifests.

**Expected behavior**
Everything works as today except that a set of config files could be specified in a directory and they would all be applied.

**Comment by stealthybox** [comment]
> we can't afford to have one directory per workload 
as they are too many to be in git.paths.

`git.path` is recursive. You can set it to a single parent directory and all sub-directories will be traversed for their manifests.
Upon reaching a `.flux.yaml`, manifests are then recursively ignored.
Each path in `git.path` under a `.flux.yaml` will run the generator commands using that path as the working directory.

The generator commands run in a shell with popular UNIX tools.
You can run multiple kustomize dirs from a single config file and even a single generator command!

**Here's how to run kustomize recursively from a single config:**
```yaml
version: 1
commandUpdated:
  generators:
    - command: |
        for k in `find . -name kustomization.yaml`; do
          echo ---; kustomize build `dirname $k`
        done
# I tested this
```
From here, you can use directories in your control git repo without having to modify the Flux config or fluxd deployment.
You can also just specify the patch files individually per HelmRelease in the appropriate `kustomization.yaml`.

Using a directory hierarchy will allow you to group related kustomizations appropriately.

If you don't want to use directories, and you really want to use `patchUpdated`, you can use a generator to silently cat all the patch files together so that you're not maintaining one really long one.

You can also use that `sh` for-loop to create kustomize directories on demand or pass variables into the kustomization based on file or directory names:
```yaml
version: 1
commandUpdated:
  generators:
    - command: |
        for f in `find . -name *.patch`; do
          mkdir tmpdir
          cp $f tmpdir/

          cat << EOF > tmpdir/kustomization.yaml
          bases:
          - ../../../helm-release-base
          patches:
          - $f
          EOF

          echo ---
          kustomize build tmpdir

          rm -rf tmpdir/
        done
# I did not test this
```

Whatever repo structure is desired, there is certainly a way to generate your desired manifests with the existing functionality.
