### ISSUE TITLE
Subcharts with flux in GIT Repo

### ISSUE THREAD

**Issue by linuxbsdfreak** [fluxcd/flux#2215]
**Describe the bug**
I am trying to setup a HELM parent subchart scenario to be used in a git Repo and to be deployed via Flux

**To Reproduce**
Steps to reproduce the behaviour:
0. What's your setup?

Chart repo structure is as follows

```
├── charts

│   ├── podinfo2

│   │   ├── Chart.yaml

│   │   ├── requirements.yaml

│   │   └── values.yaml

│   └── podinfo-dep

│       ├── Chart.yaml

│       ├── README.md

│       ├── templates

│       │   ├── deployment.yaml

│       │   ├── _helpers.tpl

│       │   ├── hpa.yaml

│       │   ├── ingress.yaml

│       │   ├── NOTES.txt

│       │   ├── service.yaml

│       │   └── tests

│       │       ├── service.yaml

│       │       └── storage.yaml

│       └── values.yaml```

In requirements.yaml i have

dependencies:

  - name: podinfo-dep

    version: 1.4.4

    repository: file://../podinfo-dep```
```
podinfo2 chart is dependant on podinfo-dep with a requirements.yaml

podinfo2/podinfo2.yaml
```
---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: podinfo2
  namespace: podinfo2
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:dev-*
spec:
  releaseName: podinfo2
  chart:
    git: git@github.mydomain.com:app-k8s/helm-charts-flux
    path: charts/podinfo2
    ref: master
  values:
    hpa:
      enabled: false
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      path: /
      hosts:
      - k8podinfo2.ingress.mydomain.com
```

Following Error
```
ts=2019-07-03T07:26:03.747344867Z caller=chartsync.go:252 component=chartsync info="enqueing release upgrade due to change in git chart source" resource=podinfo2:helmrelease/podinfo2

ts=2019-07-03T07:26:07.078092614Z caller=chartsync.go:354 component=chartsync warning="failed to update chart dependencies" resource=podinfo2:helmrelease/podinfo2 err="could not update dependencies in /tmp/flux-working909485013/charts/podinfo2: Hang tight while we grab the latest from your chart repositories...\n...Unable to get an update from the \"local\" chart repository (http://127.0.0.1:8879/charts):\n\tGet http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: connect: connection refused\n...Successfully got an update from the \"incubator\" chart repository\n...Successfully got an update from the \"svc-cat\" chart repository\n...Successfully got an update from the \"build-milestones-helm\" chart repository\n...Successfully got an update from the \"stable\" chart repository\nUpdate Complete. ⎈Happy Helming!⎈\nError: open /var/fluxd/helm/repository/cache/local-index.yaml: no such file or directory\n
```

**Expected behavior**
Expectation was that flux would pull the dependent chart and install it.

**Logs**
If applicable, please provide logs of `fluxd` or the helm-operator. In a standard stand-alone installation of Flux, you'd get this by running `kubectl logs -n default deploy/flux`.

**Additional context**
Add any other context about the problem here, e.g 
- Flux version: 1.13.0
- Helm Operator version: 0.9.2
- Kubernetes version: 1.14.3
- Git provider: Enterprise github
- Container registry provider:

**Comment by stefanprodan** [comment]
Looks to me that Helm does not support relative paths outside the chart itself.

```
Unable to get an update from the "local" chart repository http://127.0.0.1:8879/charts
Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: connect: connection refused
```

**Comment by hiddeco** [comment]
You can validate @stefanprodan his theory by running `helm template .` in your chart directory.

**Comment by linuxbsdfreak** [comment]
@stefanprodan @hiddeco . 

If i do helm template under the parent chart for eg: charts/podinfo2/ . I have to do a a helm dependency update before a helm template. 

Is this a know issue with parent/subcharts with helm and flux? or Is there a way to resolve it ?

Regards,
Kevin

**Comment by hiddeco** [comment]
The following works for my local Helm operator setup, running on a default configuration.

```
❯ tree charts
charts
├── child
│   ├── Chart.yaml
│   ├── templates
│   │   ├── deployment.yaml
│   │   ├── _helpers.tpl
│   │   ├── ingress.yaml
│   │   ├── NOTES.txt
│   │   ├── service.yaml
│   │   └── tests
│   │       └── test-connection.yaml
│   └── values.yaml
└── parent
    ├── Chart.yaml
    ├── requirements.lock
    ├── requirements.yaml
    ├── templates
    │   ├── deployment.yaml
    │   ├── _helpers.tpl
    │   ├── ingress.yaml
    │   ├── NOTES.txt
    │   ├── service.yaml
    │   └── tests
    │       └── test-connection.yaml
    └── values.yaml

6 directories, 18 files

❯ cat charts/parent/requirements.yaml
dependencies:
- name: child
  version: 0.1.0
  repository: file://../child
```

```yaml
---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: parent
spec:
  releaseName: parent
  chart:
    git: ssh://git@192.168.39.64:2022/home/git/repo
    path: charts/parent
    ref: master
  values: {}
```

```sh
❯ kubectl describe hr parent
Name:         parent
Namespace:    default
Labels:       flux.weave.works/sync-gc-mark=sha256.RjINrEKY4VXdcPuB_hPj4DUerVLpvwemxaQojEcQa5Y
Annotations:  flux.weave.works/sync-checksum: fb110b0e4fc52fe5595a39742168e15a279bdffc
              kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"flux.weave.works/v1beta1","kind":"HelmRelease","metadata":{"annotations":{"flux.weave.works/sync-checksum":"fb110b0e4fc52fe...
API Version:  flux.weave.works/v1beta1
Kind:         HelmRelease
Metadata:
  Creation Timestamp:  2019-07-12T11:44:45Z
  Generation:          1
  Resource Version:    83963
  Self Link:           /apis/flux.weave.works/v1beta1/namespaces/default/helmreleases/parent
  UID:                 71febfdb-a49a-11e9-affe-00364618578c
Spec:
  Chart:
    Git:         ssh://git@192.168.39.64:2022/home/git/repo
    Path:        charts/parent
    Ref:         master
  Release Name:  parent
  Values:
Status:
  Conditions:
    Last Transition Time:  2019-07-12T11:47:48Z
    Last Update Time:      2019-07-12T11:47:48Z
    Message:               helm install succeeded
    Reason:                HelmSuccess
    Status:                True
    Type:                  Released
    Last Transition Time:  2019-07-12T11:47:41Z
    Last Update Time:      2019-07-12T12:02:40Z
    Message:               successfully cloned git repo
    Reason:                GitRepoCloned
    Status:                True
    Type:                  ChartFetched
  Observed Generation:     1
  Release Name:            parent
  Release Status:          DEPLOYED
  Revision:                64131089ce0d85bb64db2a338f4a4bf26fb1f03f
  Values Checksum:         ca3d163bab055381827226140568f3bef7eaac187cebd76878e0b63e9e442356
Events:
  Type    Reason       Age                From           Message
  ----    ------       ----               ----           -------
  Normal  ChartSynced  18m (x2 over 19m)  helm-operator  Chart managed by HelmRelease processed
  Normal  ChartSynced  66s (x7 over 16m)  helm-operator  Chart managed by HelmRelease processed
```

Interestingly enough, a local `helm dep update` in the `parent` chart results in an error:

```
❯ cd charts/parent
❯ helm dep update
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
	Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: connect: connection refused
...Successfully got an update from the "stable" chart repository
Update Complete.
Saving 1 charts
Deleting outdated charts
```

but still adds the `child` chart to `charts/parent/charts`

```sh
❯ tree charts/parent
charts/parent
├── charts
│   └── child-0.1.0.tgz
├── Chart.yaml
├── requirements.lock
...
```
