### ISSUE TITLE
Flux missing a previously installed HelmRelease

### ISSUE THREAD

**Issue by jowparks** [fluxcd/flux#2246]
**Describe the bug**
Using flux-helm-operator with flux in kubernetes cluster and one of the HelmReleases I define is currently installed in cluster (was once being recognized by flux) and is currently managed by flux-helm-operator, but in the logs of the standard flux pod I am not seeing the helm release anymore. I noticed this because updates to the git branch it is pointing at are also no longer working, I purged the helm release for the app (prometheus-operator) and flux-helm-operator correctly installs the old version, seems to be using a cache somehow.
I also don't see any errors in the flux or flux-helm-operator pods.

Here is the first bit of the chart in question that is not being recognized:
```---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: kube-system-prometheus-operator
  namespace: kube-system
  annotations:
    flux.weave.works/ignore: false
    flux.weave.works/automated: true
spec:
  releaseName: prometheus-operator
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: prometheus-operator
    version: 0.1.29
  values:
    global:
      rbac:
        pspEnabled: false

    prometheusOperator:
      cleanupCustomResource: false

    prometheus:
```

It is worth noting I have many other helm releases/deployments in the same subdirectory and they are all working and updating fine. 
**To Reproduce**
Steps to reproduce the behaviour:
N/A

**Expected behavior**
When I update chart on git branch that flux is pointing towards, it should find the specified HelmRelease in a subfolder of the designed folder.

**Logs**
```
ts=2019-07-11T01:06:11.933820657Z caller=sync.go:531 component=cluster method=Sync cmd="kubectl apply -f -" took=877.984809ms err=null output="namespace/dataeng configured
namespace/dataeng-test configured
namespace/flux configured
namespace/platform-svcs configured
namespace/sre configured
namespace/stats configured
namespace/syslog configured
service/fluxcloud unchanged
service/invitae-bbe-prometheus-blackbox-exporter unchanged
role.rbac.authorization.k8s.io/kafka-connect-operator configured
serviceaccount/kafka-connect-operator unchanged
customresourcedefinition.apiextensions.k8s.io/kafkaconnectors.dataeng.invitae.com configured
service/pricing-svc-dev-http-service unchanged
service/prometheus-rabbitmq-exporter unchanged
service/statsd unchanged
configmap/dashboard-confluent unchanged
configmap/dashboard-kafka-connect unchanged
configmap/dashboard-log-levels unchanged
configmap/invitae-bbe-invitae-ca-certs unchanged
ingress.extensions/invitae-bbe-prometheus-blackbox-exporter unchanged
configmap/invitae-bbe-prometheus-blackbox-exporter unchanged
configmap/kafka-connect-configmap unchanged
configmap/kafka-connect-configmap unchanged
rolebinding.rbac.authorization.k8s.io/kafka-connect-operator unchanged
configmap/mtail-progs-dir unchanged
ingress.extensions/pricing-svc-dev-http-service unchanged
configmap/statsd-exporter-config-dev unchanged
configmap/syslog-ng-conf unchanged
configmap/syslog-ng-pipes-conf unchanged
deployment.extensions/fluxcloud unchanged
deployment.apps/invitae-bbe-prometheus-blackbox-exporter configured
deployment.apps/kafka-connect-operator unchanged
deployment.apps/pricing-svc-dev-http-service configured
deployment.extensions/prometheus-kafka-exporter unchanged
deployment.extensions/prometheus-rabbitmq-exporter unchanged
deployment.extensions/statsd-exporter unchanged
daemonset.apps/syslog-ng configured
daemonset.apps/syslog-pipes configured
helmrelease.flux.weave.works/helm-exporter unchanged
helmrelease.flux.weave.works/invitae-control-center unchanged
helmrelease.flux.weave.works/invitae-kafka-connect-test unchanged
helmrelease.flux.weave.works/invitae-kafka-connectors unchanged
helmrelease.flux.weave.works/invitae-schema-registry-cloud unchanged
servicemonitor.monitoring.coreos.com/kafka-streams-servicemonitor-dev unchanged
helmrelease.flux.weave.works/nginx-ingress unchanged
helmrelease.flux.weave.works/platformsvcs-postgres unchanged
prometheusrule.monitoring.coreos.com/prom-blackbox-rules unchanged
prometheusrule.monitoring.coreos.com/prom-disk-space unchanged
prometheusrule.monitoring.coreos.com/prom-kafka-brokers unchanged
prometheusrule.monitoring.coreos.com/prom-kafka-connect unchanged
prometheusrule.monitoring.coreos.com/prom-kafka-connect-operator unchanged
prometheusrule.monitoring.coreos.com/prom-kafka-platform unchanged
prometheusrule.monitoring.coreos.com/prom-rabbitmq unchanged
prometheusrule.monitoring.coreos.com/prom-suppressed-log-lines unchanged
helmrelease.flux.weave.works/prometheus-pushgateway unchanged
```

**Additional context**
Add any other context about the problem here, e.g 
- Flux version: flux, chart version flux-0.9.1, app version 1.12.0
- Helm Operator version: docker.io/weaveworks/helm-operator:0.8.0
- Kubernetes version: Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-eks-c57ff8", GitCommit:"c57ff8e35590932c652433fab07988da79265d5b", GitTreeState:"clean", BuildDate:"2019-06-07T20:43:03Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
- Git provider: bitbucket
- Container registry provider: self hosted

**Comment by jowparks** [comment]
Ok update, flux has picked back up the `prometheus-operator` but I had to remove these settings from the `additionalScrapeConfig` heading:

```
        # This jobs config was pulled from https://grafana.com/dashboards/315
        - job_name: kubernetes-nodes-cadvisor
          scrape_interval: 10s
          scrape_timeout: 10s
          scheme: https  # remove if you want to scrape metrics on insecure port
          tls_config:
            ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          kubernetes_sd_configs:
            - role: node
          relabel_configs:
            - action: labelmap
              regex: __meta_kubernetes_node_label_(.+)
            - target_label: __address__
              replacement: kubernetes.default.svc:443
            - source_labels: [__meta_kubernetes_node_name]
              regex: (.+)
              target_label: __metrics_path__
              replacement: /api/v1/proxy/nodes/${1}:4194/metrics
          metric_relabel_configs:
            - action: replace
              source_labels: [id]
              regex: '^/machine\.slice/machine-rkt\\x2d([^\\]+)\\.+/([^/]+)\.service$'
              target_label: rkt_container_name
              replacement: '${2}-${1}'
            - action: replace
              source_labels: [id]
              regex: '^/system\.slice/(.+)\.service$'
              target_label: systemd_service_name
                replacement: '${1}'
```
Seems like flux or the flux-helm operator was choking on this info, but neither was producing an observable error. The helm operator was chugging along on its merry way with the old deployment, and flux was picking up the new commits on the branch we were pointing it to, but it was just not recognizing (or producing an error) on the `prometheus-operator` because of the config above.
