### ISSUE TITLE
validation failure list: spec.rollback.timeout in body must be of type int64: "integer"

### ISSUE THREAD

**Issue by sureshamk** [fluxcd/flux#2250]
**Describe the bug**
My helm release as follows 

```yml

apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: demolocal
  namespace: local
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:loc-*
spec:
  releaseName: demo-local
  chart:
    git: git@bitbucket.org:sureshamk/my_helm.git
    path: charts/demo
    ref: local
  values:
    demoadmin:
      name: demoadmin
      image: cr.demolocal.com/demoadmin:loc-1
      imagePullPolicy: IfNotPresent
      ingress:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
          nginx.ingress.kubernetes.io/rewrite-target: /
        path: /newadmin/api
        hosts:
        - apps.demolocal.com
  rollback:
    # If set, will perform rollbacks for this release.
    enable: true
    # If set, will force resource update through delete/recreate if
    # needed.
    force: true
    # Prevent hooks from running during rollback.
    disableHooks: false
    # Time in seconds to wait for any individual Kubernetes operation.
    timeout: 5000
    # If set, will wait until all Pods, PVCs, Services, and minimum
    # number of Pods of a Deployment are in a ready state before
    # marking the release as successful. It will wait for as long
    # as the set timeout.
    wait: false

```

When i apply this file  (`kubectl apply -f local.yaml`)
i m getting this error
: validation failure list:
spec.rollback.timeout in body must be of type int64: "integer"
