### ISSUE TITLE
flux.weave.works/ignore annotation and sync-garbage-collection flag not working as expected together

### ISSUE THREAD

**Issue by michaelgeorgeattard** [fluxcd/flux#2272]
Given a `HelmRelease` definition as below:

```
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: foo
  namespace: bar
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:*-demo-*
spec:
  releaseName: foo
  chart:
    repository: http://chartmuseum-chartmuseum.management:8080
    name: site
    version: 0.4.7
```

With `sync-garbage-collection` flag enabled, deleting this HelmRelease correctly removes the configuration from the cluster, ultimately resulting in `foo` helm release being deleted.

Modifying the `HelmRelease` by adding the `flux.weave.works/ignore` annotation:

```
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: foo
  namespace: bar
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:*-demo-*
    flux.weave.works/ignore: "true"
spec:
  releaseName: foo
  chart:
    repository: http://chartmuseum-chartmuseum.management:8080
    name: site
    version: 0.4.7
```

In this scenario I would expect:

* If the HelmRelease does not currently exist in the cluster, it will remain as so.
* If the HelmRelease does currently exist in the cluster, and `sync-garbage-collection` flag is currently enabled, it is removed, finally resulting in the helm release being deleted.

The second point is currently not working as expected, the HelmRelease configuration + helm release both remain in the cluster.
