### ISSUE TITLE
Question: How to use common environment variables or shared config-maps across chart

### ISSUE THREAD

**Issue by ingeknudsen** [fluxcd/flux#2293]
Not sure if this will become a feature request, or if this is possible with the version we have, or will be possible with the new Kustomize feature. We have started using Flux in development and production clusters. For development we create new clusters on a, almost, weekly basis. All development clusters points to the same branch and config in the repo. Before we installed flux we installed the components to the cluster through a custom script, but we want to move most of this to Flux config. We have started to see that it would be nice to have a mechanism to share config across components. However we struggle when having components in different namespaces and/or where the config for each component is named differently in the different charts. An example of such a config is the **clusterName**. For the first component we flux'ified, our own controller which runs in default namespace, we created a configmap which feeds the values into the Helm-release. For that component the **clusterName** is a top level value in the values file. The second component was Velero, which needed to be inside a velero namespace. The **clusterName** went into the `configuration -> backupStorageLocation -> bucket`. The third component, kubed, would need to has its **clusterName** config in `config -> clusterName`, the fourth, external-dns, gets **clusterName** into `txtOwnerId`. The way we know how to solve this would be to create a config-map for each namespace where there is a component which should be managed by flux, which needs dynamic variables from outside. For components living in the same namespace, to have a shared configmap where the clustername is duplicated to different sections of that configmap.

What would be nice to be able to do was to either:
- Tell flux about cluster global environment variables, through i.e. ``extraEnvs`` that we could set when we install to that specific cluster, and refer to that variable in the Helmrelease when setting the specific value
- Or to have a `configMapKeyRef` to a shared configmap in the cluster. I.e. having a configmap in the default namespace holding all, even if values are duplicated to different sections, cluster global environment variables, and allow flux to read from that configmap

**Comment by nabadger** [comment]
Could you not do this at rendering time via kustomize?

We do something like:

```
configMapGenerator:
- env: properties/cluster.properties
  name: cluster-properties
  namespace: kustomize

vars:
- fieldref:
    fieldPath: data.DOMAIN
  name: DOMAIN
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: cluster-properties
- fieldref:
    fieldPath: data.CLUSTER_NAME
  name: CLUSTER_NAME
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: cluster-properties
```

Now you can reference those values anywhere you want...
```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app
spec:
  rules:
  - host: $(DEPLOYMENT_NAME).svc.$(CLUSTER_NAME).$(DOMAIN)
    http:
      paths:
      - backend:
          serviceName: app
          servicePort: 8000
  tls:
  - hosts:
    - $(DEPLOYMENT_NAME).svc.$(CLUSTER_NAME).$(DOMAIN)
```

At this point it's all kustomize. We end up with a cluster-properties configmap in-cluster, but it's not used (it's only used at the rendering point in time).
