### ISSUE TITLE
flux image tag regex issue

### ISSUE THREAD

**Issue by aliartiza75** [fluxcd/flux#2309]
**Describe the bug**
I want flux to detect the change in the image tag. I have the following configuration:

```yaml
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: test-app
  namespace: default
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.deployment: regexp:^([0-9]+.[0-9]+.[0-9]+-PR-[0-9]+-[0-9]+-SNAPSHOT)$
spec:
  releaseName: test
  chart:
    repository: https://xxx.github.io/xyz/
    name: application
    version: 0.0.6
  values:
    applicationName: "test"
    # deployment config parameters
    deployment:
      tolerations: 
      - key: "dedicated"
        operator: "Equal"
        value: "app"
        effect: "NoSchedule" 
      strategy:
        type: RollingUpdate
      podLabels:
        app: test
      image:
        repository: testImage
        tag: 0.0.0-PR-324-9-SNAPSHOT
```

I have provided the following regex for image tag
```yaml
flux.weave.works/tag.deployment: regexp:^([0-9]+.[0-9]+.[0-9]+-PR-[0-9]+-[0-9]+-SNAPSHOT)$
```

Example of an image tag is given below:

```
0.0.0-PR-324-9-SNAPSHOT
```

flux is not able to detect the changes in the image tag and no error is being generated in logs.

**To Reproduce**
Steps to reproduce the behaviour:
0. What's your setup?
I have deployed it on a kubernetes cluster. Jenkins creates a new image an push it to the repository. Flux need to detect the change in the image tag.

**Expected behaviour**
Flux should detect the change in the image tag.

**Logs**
No error is being generated in the logs

**Additional context**
Add any other context about the problem here, e.g 
- Flux version:  1.13.2
- Helm Operator version: None 
- Kubernetes version: None
- Git provider: bitbucket
- Container registry provider: nexus

**Comment by stefanprodan** [comment]
You have a `"` at the end of the regex expression.

**Comment by aliartiza75** [comment]
@stefanprodan sorry for inconvenience, I have provided the regex in these formats:

* format-1
```
flux.weave.works/tag.deployment: regexp:^([0-9]+.[0-9]+.[0-9]+-PR-[0-9]+-[0-9]+-SNAPSHOT)$
```

* format-2
```
flux.weave.works/tag.deployment: "regexp:^([0-9]+.[0-9]+.[0-9]+-PR-[0-9]+-[0-9]+-SNAPSHOT)$"
```

it didn't work in both ways

**Comment by hiddeco** [comment]
It is not due to the regex not understanding the pattern, as I provided a test case to https://github.com/fluxcd/flux/blob/036221706f3ffdeb215a3a037b97573b7cf17008/policy/pattern_test.go#L90

```go
		{
			name: "complex",
			pattern: `regex:^([0-9]+.[0-9]+.[0-9]+-PR-[0-9]+-[0-9]+-SNAPSHOT)$`,
			true: []string{"0.0.0-PR-324-9-SNAPSHOT", "10.0.0-PR-324-9-SNAPSHOT"},
			false: []string{"something-else"},
		},
```

which resulted in

```sh
=== RUN   TestRegexpPattern_Matches/complex["0.0.0-PR-324-9-SNAPSHOT"]
    --- PASS: TestRegexpPattern_Matches/complex["0.0.0-PR-324-9-SNAPSHOT"] (0.00s)
=== RUN   TestRegexpPattern_Matches/complex["10.0.0-PR-324-9-SNAPSHOT"]
    --- PASS: TestRegexpPattern_Matches/complex["10.0.0-PR-324-9-SNAPSHOT"] (0.00s)
=== RUN   TestRegexpPattern_Matches/complex["something-else"]
    --- PASS: TestRegexpPattern_Matches/complex["something-else"] (0.00s)
PASS
```

**Comment by aliartiza75** [comment]
@hiddeco thank you, I will check again my configurations maybe I am configuring something incorrectly.

**Comment by aliartiza75** [comment]
@hiddeco i think the issue is not with the regex  but it is with the method I am specifying to check the regex of the image tag, can you kindly check the manifest i have provided below is for any possible issue thank you:

```yaml
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: app
  namespace: 
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.deployment: regexp:^(*-SNAPSHOT)$
spec:
  releaseName: app
  chart:
    repository: chart-repository
    name: application
    version: 0.0.6
  values:
    applicationName: "app"

    # deployment config parameters
    deployment:
      tolerations: 
      - key: "dedicated"
        operator: "Equal"
        value: "app"
        effect: "NoSchedule" 
      strategy:
        type: RollingUpdate
      podLabels:
        app: emrmanager
      image:
        repository: xyz
        tag: 0.0.0-develop-1-SNAPSHOT
```
