### ISSUE TITLE
Cannot automate workloads with flux or fluxctl

### ISSUE THREAD

**Issue by matthewbednarski** [fluxcd/flux#2319]
I am not able to automate workloads with flux; neither through annotations in the manifests nor using fluxctl directly. 

The error is always the same in both the flux logs and the `fluxctl automate` output:

```
Error: Traceback (most recent call last):
  File "kubeyaml.py", line 238, in <module>
  File "kubeyaml.py", line 233, in main
  File "kubeyaml.py", line 66, in apply_to_yaml
  File "site-packages/ruamel/yaml/main.py", line 452, in dump_all
  File "kubeyaml.py", line 96, in update_annotations
  File "kubeyaml.py", line 116, in manifests
TypeError: 'NoneType' object has no attribute '__getitem__'
Failed to execute script kubeyaml
```

Flux does correctly sync with the git repository and apply any changes, it only seems relevant to the management of workloads.

**Logs**

Here is the log output from flux:

```
ts=2019-08-02T08:52:27.989097573Z caller=images.go:17 component=sync-loop msg="polling images"
ts=2019-08-02T08:52:28.119782018Z caller=images.go:111 component=sync-loop workload=dev:deployment/ui-element container=ui-element repo=registry.gitlab.com/aicomp-dev/ui-element pattern=semver:~1.0 current=registry.gitlab.com/aicomp-dev/ui-element:latest info="added update to automation run" new=registry.gitlab.com/aicomp-dev/ui-element:1.0.41 reason="latest 1.0.41 (2019-08-01 14:41:14.032935118 +0000 UTC) > current latest (2019-07-23 08:55:52.829516843 +0000 UTC)"
ts=2019-08-02T08:52:28.120658983Z caller=images.go:111 component=sync-loop workload=dev:deployment/api-element-no-auth container=api-element-no-auth repo=registry.gitlab.com/aicomp-dev/api-element pattern=semver:~1.0 current=registry.gitlab.com/aicomp-dev/api-element:latest info="added update to automation run" new=registry.gitlab.com/aicomp-dev/api-element:1.0.27 reason="latest 1.0.27 (2019-07-23 16:13:42.423164511 +0000 UTC) > current latest (1970-01-01 00:00:00 +0000 UTC)"
ts=2019-08-02T08:52:28.121506641Z caller=images.go:111 component=sync-loop workload=dev:deployment/api-element container=api-element repo=registry.gitlab.com/aicomp-dev/api-element pattern=semver:~1.0 current=registry.gitlab.com/aicomp-dev/api-element:latest info="added update to automation run" new=registry.gitlab.com/aicomp-dev/api-element:1.0.27 reason="latest 1.0.27 (2019-07-23 16:13:42.423164511 +0000 UTC) > current latest (1970-01-01 00:00:00 +0000 UTC)"
ts=2019-08-02T08:52:28.121697026Z caller=loop.go:119 component=sync-loop jobID=4060f4f0-7e7a-ce06-9734-342814f908e9 state=in-progress
ts=2019-08-02T08:52:28.339155535Z caller=releaser.go:59 component=sync-loop jobID=4060f4f0-7e7a-ce06-9734-342814f908e9 type=release updates=3
ts=2019-08-02T08:52:28.523914512Z caller=loop.go:129 component=sync-loop jobID=4060f4f0-7e7a-ce06-9734-342814f908e9 state=done success=false err="applying changes: updating resource dev:deployment/ui-element in ui-element/frontend.yaml: Traceback (most recent call last):\n  File \"kubeyaml.py\", line 238, in <module>\n  File \"kubeyaml.py\", line 233, in main\n  File \"kubeyaml.py\", line 66, in apply_to_yaml\n  File \"site-packages/ruamel/yaml/main.py\", line 452, in dump_all\n  File \"kubeyaml.py\", line 73, in update_image\n  File \"kubeyaml.py\", line 116, in manifests\nTypeError: 'NoneType' object has no attribute '__getitem__'\nFailed to execute script kubeyaml"
```

**Additional context**
- Flux version: fluxcd/flux:1.13.3 (it was the same while using weaveworks/flux:1.13.1)
- Kubernetes version: 1.13.5-do.f.0
- Git provider: gitlab.com
- Container registry provider: registry.gitlab.com

**Comment by stefanprodan** [comment]
Looks like a malformed yaml in `deployment/ui-element`, I'm guessing mixed tabs and spaces.

**Comment by matthewbednarski** [comment]
@stefanprodan , I don't see any tabs in the file, and all the manifests are correctly applied by flux if I change the version in the image field in the manifest. Also, this occurs with all of the workloads I have tried.

Here is that particular manifest containing that deployment.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.ui-element: semver:~1.0
  labels:
    app: ui-element
  name: ui-element
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ui-element
  template:
    metadata:
      labels:
        app: ui-element
    spec:
      containers:
      - env:
        - name: DESIGNER_URL
          value: https://internal.domain/designer
        - name: OIDC_ACCOUNT_URL
          value: https://internal.domain/auth/realms/vcppc-dev/account
        - name: OIDC_LOGOUT_URL
          value: https://internal.domain/auth/realms/vcppc-dev/protocol/openid-connect/logout
        image: registry.gitlab.com/aicomp-dev/ui-element:latest
        imagePullPolicy: Always
        name: ui-element
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 150m
            memory: 132Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
---

kind: Service
apiVersion: v1
metadata:
  name: ui-element
spec:
  ports:
    - name: web
      port: 80
  selector:
    app: ui-element
---
```
