### ISSUE TITLE
valuesFromFile to create key's value sourced from file content

### ISSUE THREAD

**Issue by cdenneen** [fluxcd/flux#2322]
```yaml
valuesFromFile:
  chartFileRef:
    myScript: path/to/file.js
  externalSourceRef:
    defaultScript: https://raw.githubusercontent.com/cdenneen/example/master/script.js
```

result in equivalent of:

`helm install --set-file key=path/to/file.js`

```values.yaml
myScript: |
  const { events, Job } = require("brigadier")
  function run(e, project) {
    console.log("this is my script")
  }
  events.on("run", run)
defaultScript: |
  const { events, Job } = require("brigadier")
  function run(e, project) {
    console.log("hello default script")
  }
  events.on("run", run)
```
