### ISSUE TITLE
Flux v1.11.1 syncs our EKS cluster just fine, but later versions won't sync

### ISSUE THREAD

**Issue by fshot** [fluxcd/flux#2374]
**Describe the bug**
Flux 1.11.1 syncs fine for our repo & cluster, but later versions just hang on sync. 

**To Reproduce**
Steps to reproduce the behaviour:
Our flux config:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    name: flux
  name: flux
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    name: flux
  name: flux
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    name: flux
  name: flux
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flux
subjects:
- kind: ServiceAccount
  name: flux
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: flux-git-deploy
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: memcached
spec:
  ports:
  - name: memcached
    port: 11211
  selector:
    name: memcached
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux
spec:
  replicas: 1
  selector:
    matchLabels:
      name: flux
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/port: "3031"
      labels:
        name: flux
    spec:
      containers:
      - args:
        - --memcached-service=
        - --ssh-keygen-dir=/var/fluxd/keygen
        - --git-url=git@github.com:org/repo
        - --git-branch=master
        - --listen-metrics=:3031
        - --git-poll-interval=60s
        - --registry-exclude-image=*
        image: docker.io/fluxcd/flux:1.13.3
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /api/flux/v6/identity.pub
            port: 3030
          initialDelaySeconds: 5
          timeoutSeconds: 5
        name: flux
        ports:
        - containerPort: 3030
        readinessProbe:
          httpGet:
            path: /api/flux/v6/identity.pub
            port: 3030
          initialDelaySeconds: 5
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
        volumeMounts:
        - mountPath: /etc/fluxd/ssh
          name: git-key
          readOnly: true
        - mountPath: /var/fluxd/keygen
          name: git-keygen
      serviceAccountName: flux
      volumes:
      - name: git-key
        secret:
          defaultMode: 256
          secretName: flux-git-deploy
      - emptyDir:
          medium: Memory
        name: git-keygen
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached
spec:
  replicas: 1
  selector:
    matchLabels:
      name: memcached
  template:
    metadata:
      labels:
        name: memcached
    spec:
      containers:
      - args:
        - -m 512
        - -I 5m
        - -p 11211
        image: memcached:1.5.15
        imagePullPolicy: IfNotPresent
        name: memcached
        ports:
        - containerPort: 11211
          name: clients
        securityContext:
          allowPrivilegeEscalation: false
          runAsGroup: 11211
          runAsUser: 11211
```

**Expected behavior**
We expect to see sync checks happening every minute and syncs completing without hanging.

**Logs**
 `kubectl logs -n default deploy/flux`
```logs -f deployment/flux
ts=2019-08-20T00:40:50.629592487Z caller=main.go:225 version=1.13.3
ts=2019-08-20T00:40:50.629787108Z caller=main.go:317 msg="using in cluster config to connect to the cluster"
ts=2019-08-20T00:40:51.672328094Z caller=main.go:396 component=cluster identity=/etc/fluxd/ssh/identity
ts=2019-08-20T00:40:51.672362453Z caller=main.go:397 component=cluster identity.pub="[redacted]"
ts=2019-08-20T00:40:51.672418379Z caller=main.go:402 host=https://x.x.x.x:443 version=kubernetes-v1.13.8-eks-a977ba
ts=2019-08-20T00:40:51.672495434Z caller=main.go:414 kubectl=/usr/local/bin/kubectl
ts=2019-08-20T00:40:51.673165689Z caller=main.go:426 ping=true
ts=2019-08-20T00:40:51.682168697Z caller=main.go:562 url=git@github.com:org/repo user="Weave Flux" email=support@weave.works signing-key= verify-signatures=false sync-tag=flux-sync notes-ref=flux set-author=false
ts=2019-08-20T00:40:51.682210775Z caller=main.go:623 upstream="no upstream URL given"
ts=2019-08-20T00:40:51.68238395Z caller=main.go:652 metrics-addr=:3031
ts=2019-08-20T00:40:51.694160569Z caller=loop.go:85 component=sync-loop err="git repo not ready: git repo has not been cloned yet"
ts=2019-08-20T00:40:51.694315086Z caller=images.go:17 component=sync-loop msg="polling images"
ts=2019-08-20T00:40:51.694404933Z caller=images.go:27 component=sync-loop msg="no automated workloads"
ts=2019-08-20T00:40:51.696182127Z caller=main.go:644 addr=:3030
ts=2019-08-20T00:40:52.053349409Z caller=checkpoint.go:24 component=checkpoint msg="up to date" latest=1.13.3
ts=2019-08-20T00:40:57.75779353Z caller=loop.go:111 component=sync-loop event=refreshed url=git@github.com:org/repo branch=master HEAD=...7732c1
```

`fluxctl sync`

```Synchronizing with git@github.com:org/repo
Failed to complete sync job (ID "601ccdff-c921-6dd8-2d7b-f4bf2b8b9b29")
Error: timeout
Run 'fluxctl sync --help' for usage.
```

**Additional context**
Add any other context about the problem here, e.g 
- Flux version: 1.11.1 works great, 1.12.3 and 1.13.3 (and intermediate versions) don't
- Helm Operator version: Not using Helm operator
- Kubernetes version: 1.13.8 EKS
- Git provider: github.com
- Container registry provider: Amazon ECS
