### ISSUE TITLE
unable to connect to azure devops

### ISSUE THREAD

**Issue by smartpcr** [fluxcd/flux#2391]
**Describe the bug**

I am unable to connect to Azure Devops

- kubectl logs -n flux flux-944479699-rkn8w
``` logs 
ts=2019-08-22T00:34:16.352078999Z caller=main.go:193 version=1.12.2
ts=2019-08-22T00:34:16.43601428Z caller=main.go:350 component=cluster identity=/etc/fluxd/ssh/identity
ts=2019-08-22T00:34:16.43605168Z caller=main.go:351 component=cluster identity.pub="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDOxGSdt7ajs6hbRAwyZXG5hO6S88rjUGMksYlXstgk7DVmV6yHrR9xdy2+Hf3mm0flgAMW8dYsl1xfgwf0TRGsGtVeqzNeRMds1fWg5yhuWlEwHGNrwnBwYUf6KsGXqRGFXDjU8nolnHXxuYquLjul2h14xBqyFTtUSNEudueOwgNE8DcEabLdFmVuNqywhZ4Mi9frWfGnP2jmHUJj4hKSR3wplpShT4NhGXmZuJ1glXIPSlMcynjN3Y4i73B9b3ziB1FGHRRRPG+EX00TpuLkDkkA14+/GmKRb/oK4pOD39KE7uefT2XDrglJcpfYqWpYa3cA5sotZOnYVNxeSEPkjmwFclLUIDbYV376mwJFW7XN2aDThf2QQITEgrR9BbNCEg6nqovr3lI1Lw+LlLzCNHaKsWxsC7ZbFh7q4XgPtHf+0jJy82LTPDBPdD0UESUYnE/UJqvYFml+BpURFlnCtQvy0RGQ4PhaPn66XhApZD3MPN6nfwBbmxOOxUyc58q2WCGZNQVKorPF9ecfktglJrf2Ll/8Zgm7TNtAzZKXscOxIGMJrSzW3W3wnQ451LuBW8GkIvClyzMSP11gkV8wShYlhVrfC9SHXJzuJ79xq56NTZsJ0C00ye5NX3yoY34mkzWS5JqHx8sQcGbc2iDPdOJsGz3nQEYTxA2l501WMw=="
ts=2019-08-22T00:34:16.43606878Z caller=main.go:352 component=cluster host=https://10.0.0.1:443 version=kubernetes-v1.13.9
ts=2019-08-22T00:34:16.436120479Z caller=main.go:364 component=cluster kubectl=/usr/local/bin/kubectl
ts=2019-08-22T00:34:16.439629758Z caller=main.go:375 component=cluster ping=true
ts=2019-08-22T00:34:16.442137842Z caller=main.go:508 url=git@ssh.dev.azure.com:v3/biosoftworks/git-deploy/git-deploy user="Weave Flux" email=support@weave.works signing-key= sync-tag=flux-sync notes-ref=flux set-author=false
ts=2019-08-22T00:34:16.442178542Z caller=main.go:565 upstream="no upstream URL given"
ts=2019-08-22T00:34:16.44412123Z caller=main.go:586 addr=:3030
ts=2019-08-22T00:34:16.444417528Z caller=images.go:18 component=sync-loop msg="polling images"
ts=2019-08-22T00:34:16.444453828Z caller=images.go:28 component=sync-loop msg="no automated workloads"
ts=2019-08-22T00:34:16.444549527Z caller=loop.go:90 component=sync-loop err="git repo not ready: git repo has not been cloned yet"
ts=2019-08-22T00:34:16.719202928Z caller=images.go:147 component=cluster resource=kube-system:daemonset/kube-proxy err="decoded credential has wrong number of fields (expected 2, got 1)"
```

- kubectl describe po -n flux flux-944479699-rkn8w
``` yaml
Name:           flux-944479699-rkn8w
Namespace:      flux
Priority:       0
Node:           aks-default-33055681-2/10.240.0.6
Start Time:     Wed, 21 Aug 2019 17:33:59 -0700
Labels:         app=flux
                pod-template-hash=944479699
                release=flux
Annotations:    <none>
Status:         Running
IP:             10.244.1.4
Controlled By:  ReplicaSet/flux-944479699
Containers:
  flux:
    Container ID:  docker://7f304080c29d2eefa7a0682341f13734040d196aff7b572b06ea09b18a33809e
    Image:         docker.io/weaveworks/flux:1.12.2
    Image ID:      docker-pullable://weaveworks/flux@sha256:368bc5b219feffb1fe00c73cd0f1be7754591f86e17f57bc20371ecba62f524f
    Port:          3030/TCP
    Host Port:     0/TCP
    Args:
      --ssh-keygen-dir=/var/fluxd/keygen
      --k8s-secret-name=flux-ssh
      --memcached-hostname=flux-memcached
      --memcached-service=
      --git-url=git@ssh.dev.azure.com:v3/biosoftworks/git-deploy/git-deploy
      --git-branch=master
      --git-path=
      --git-user=Weave Flux
      --git-email=support@weave.works
      --git-set-author=false
      --git-poll-interval=5m
      --git-timeout=20s
      --sync-interval=5m
      --git-ci-skip=false
      --registry-poll-interval=5m
      --registry-rps=200
      --registry-burst=125
      --registry-trace=false
      --sync-garbage-collection=true
    State:          Running
      Started:      Wed, 21 Aug 2019 17:34:16 -0700
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:     50m
      memory:  64Mi
    Environment:
      KUBECONFIG:  /root/.kubectl/config
    Mounts:
      /etc/fluxd/ssh from git-key (ro)
      /etc/kubernetes/azure.json from acr-credentials (ro)
      /root/.kubectl from kubedir (rw)
      /var/fluxd/keygen from git-keygen (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from flux-token-xj5bv (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  kubedir:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      flux-kube-config
    Optional:  false
  git-key:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  flux-ssh
    Optional:    false
  git-keygen:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  acr-credentials:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/azure.json
    HostPathType:
  flux-token-xj5bv:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  flux-token-xj5bv
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
```

- known-hosts within pod (I didn't modify)
```
~/.ssh # cat ~/.ssh/known_hosts
40.91.93.56 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7Hr1oTWqNqOlzGJOfGJ4NakVyIzf1rXYd4d7wo6jBlkLvCA4odBlL0mDUyZ0/QUfTTqeu+tm22gOsv+VrVTMk6vwRU75gY/y9ut5Mb3bR5BV58dKXyq9A9UeB5Cakehn5Zgm6x1mKoVyf+FFn26iYqXJRgzIZZcZ5V6hrE0Qg39kZm4az48o0AUbf6Sp4SLdvnuMa2sVNwHBboS7EJkm57XQPVU3/QpyNLHbWDdzwtrlS+ez30S3AdYhLKEOxAG8weOnyrtLJAUen9mTkol8oII1edf7mWWbWVf0nBmly21+nZcmCTISQBtdcyPaEno7fFQMDD26/s0lfKob4Kw8H
```

- I have verified ssh keys are correct, and I can use it to clone a repo. Also I didn't modify `~/.ssh/knownhosts`. Any idea where I should look to trouble-shoot? 

thanks
