### ISSUE TITLE
Flux 1.14.0 does not update automatically detected HR images

### ISSUE THREAD

**Issue by aliartiza75** [fluxcd/flux#2399]
**Describe the bug**

I was using `weaveworks/flux:1.10.1` image and everything was working fine. But the issue is that when I updated the image version to `fluxcd/flux:1.14.0` flux stopped working because it was not able to detect the image param in the application git repo.

My application manifest is given below:

```yaml
---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: app
  namespace: default
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.deployment: semver:~0.0.*
spec:
  releaseName: app
  chart:
    repository: xxx
    name: application
    version: 0.0.6
  values:
    applicationName: "app"
    # deployment config parameters
    deployment:
      image:
        repository: image-repository
        tag: v0.0.2
```

**Expected behaviour**
It should have been a breaking change

**logs**

I am getting following logs:

```
ts=2019-08-22T14:19:33.788876142Z caller=images.go:111 component=sync-loop workload=-dev:helmrelease/-dev-app container=deployment repo=docker.release.domain.com:443/user/-app pattern=semver:~0.0.* current=docker.release.domain.com:443/user/-app:v0.0.2 info="added update to automation run" new=docker.release.domain.com:443/user/-app:v0.0.3 reason="latest v0.0.3 (2019-08-19 08:46:37.366692006 +0000 UTC) > current v0.0.2 (2019-08-19 08:46:37.366692006 +0000 UTC)"
ts=2019-08-22T14:19:33.789018546Z caller=loop.go:134 component=sync-loop jobID=2a94e779-a6bc-1555-9363-26993c055e7c state=in-progress
ts=2019-08-22T14:19:33.867211399Z caller=releaser.go:59 component=sync-loop jobID=2a94e779-a6bc-1555-9363-26993c055e7c type=release updates=1
ts=2019-08-22T14:19:33.886150892Z caller=loop.go:144 component=sync-loop jobID=2a94e779-a6bc-1555-9363-26993c055e7c state=done success=false err="applying changes: updating resource -dev:helmrelease/-dev-app in manifests/hr-app.yaml: did not find image map for container deployment in HelmRelease"
```

Add any other context about the problem here, e.g 

- Flux version: fluxcd/flux:1.14.0

- Git provider: bitbucket
- Container registry provider: nexus
