### ISSUE TITLE
hotfix tag is not deployed due to regex provided in annotation

### ISSUE THREAD

**Issue by aliartiza75** [fluxcd/flux#2409]
**Describe the bug**
I have a CD pipeline for an application in which an image generated and pushed to a repository. I have provided a regex in the application annotation based on that regex latest image gets deployed.

But the problem is that what should I do when I want to deploy a hotfix image for the application, whose tag doesn't match the regex I provided in the application manifest annotation. 

Although, flux doesn't work in this way but is it possible somehow to enable this feature?

Application manifest
```yaml
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: appdev-application
  namespace: appdev
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.deployment: regexp:^([0-9]+.[0-9]+.[0-9]+-develop-[0-9]+-SNAPSHOT)$
spec:
  releaseName: appdev-application
  chart:
    repository: XXX
    name: application
    version: 0.0.6
  values:
    applicationName: "application"
    # deployment config parameters
    deployment:
      strategy:
        type: Recreate
      image:
        repository: XXXX
        tag: 0.0.0-develop-6-SNAPSHOT
```

I want to deploy an image with this tag: `0.0.0-hotfix-6-SNAPSHOT`
