### ISSUE TITLE
Unable to parse files as manifests

### ISSUE THREAD

**Issue by adeleglise** [fluxcd/flux#2414]
**Describe the bug**
Unable to parse files as manifests

**To Reproduce**
Use the flux-helm-operator to maintain helm Charts.

**Expected behavior**
Flux is able to automate the charts and releases.

**Logs**
```
ts=2019-08-30T08:34:18.003278662Z caller=images.go:23 component=sync-loop error="getting unlocked automated resources: scanning multidoc from \"charts/redacted/templates/configmap.yml\": yaml: invalid map key: map[interface {}]interface {}{\".Values.data.rkBind\":interface {}(nil)}"
```

**Additional context**
We're currently migrating from GitlabCI/CD deployments of our charts to FluxCD. We use helm charts to deploy our workloads with values file depending on the stage and lifecycle of the workload (dev, stg, prd).

We manage the configMaps with helm too, so that it can be updated if a value is modified/added/removed.

The deployment template contains this line :

```
template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yml") . | sha256sum }}
```

FluxCD is currently failing on reading the values needed in the configMaps from the template.

Configmap template :

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: REDACTED
  namespace: development
data:
  REDACTED: {{ .Values.data.rkBind }}
  REDACTED: {{ .Values.data.redacted2 | quote }}
  REDACTED: {{ .Values.data.redacted3 | quote }}
```
Do we have an error in our templates, or does Flux have a bug with this type of charts ?
