### ISSUE TITLE
HelmRelease causes fluxd  CrashLoop: assignment to entry in nil map

### ISSUE THREAD

**Issue by IsNull** [fluxcd/flux#2415]
**assignment to entry in nil map**
```
panic: assignment to entry in nil map
goroutine 100 [running]:
github.com/weaveworks/flux/cluster/kubernetes.(*helmReleaseKind).getWorkloads(0x286b410, 0x1aeee80, 0xc0000c0058, 0xc0005ba100, 0xc00056df34, 0xc, 0x1addf00, 0xc00000d940, 0x1ac5c80, 0xc000138e10, ...)
/home/circleci/go/src/github.com/weaveworks/flux/cluster/kubernetes/resourcekinds.go:518 +0x165
github.com/weaveworks/flux/cluster/kubernetes.(*Cluster).ImagesToFetch(0xc0005ba100, 0x8)
/home/circleci/go/src/github.com/weaveworks/flux/cluster/kubernetes/images.go:137 +0x76f
github.com/weaveworks/flux/registry.ImageCredsWithAWSAuth.func5(0xdf8475800)
/home/circleci/go/src/github.com/weaveworks/flux/registry/aws.go:211 +0x8d
github.com/weaveworks/flux/registry/cache.(*Warmer).Loop(0xc0000485c0, 0x1ab9120, 0xc0005c6300, 0xc0000aa480, 0xc0000c0910, 0xc0003bea00)
/home/circleci/go/src/github.com/weaveworks/flux/registry/cache/warming.go:83 +0x90
created by main.main
/home/circleci/go/src/github.com/weaveworks/flux/cmd/fluxd/main.go:724 +0x635f
```

**To Reproduce**

Adding the following yaml to our git-ops test repo will lead to the crash when picked up by flux:
```yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: helm-mongodb
  namespace: mongo-global
spec:
  releaseName: mongodb
  targetNamespace: mongo-global
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: mongodb
    version: 7.2.4
  values:
    image:
      repository: bitnami/mongodb
      tag: 4.0.12-debian-9-r5
      pullPolicy: IfNotPresent
    mongodbRootPassword: 1234
    replicaSet:
      enabled: true
      name: rs0
      replicas:
        secondary: 1
        arbiter: 1
    persistence:
      enabled: true
      size: 50Gi
      storageClass: ssd-retained
```

**Expected behavior**
No crash, the CR should be created.

**Additional context**
Add any other context about the problem here, e.g 
- Flux version: docker.io/fluxcd/flux:1.14.1
- Helm Operator version: docker.io/fluxcd/helm-operator:1.0.0-rc1
- Kubernetes version: v1.13.7
- Git provider: gitlab
