### ISSUE TITLE
flux is scanning image tags and their content that are not specified in regex

### ISSUE THREAD

**Issue by aliartiza75** [fluxcd/flux#2416]
**Describe the bug**
I have deployed flux using its helm chart, but the issue is that the flux is not able to deploy the latest image of the applications:

The application manifest is given below:

```yaml
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: namespace-app
  namespace: namespace
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.deployment: regexp:^([0-9]+.[0-9]+.[0-9]+-(develop|develop-temp)-[0-9]+-SNAPSHOT)$
spec:
  releaseName: namespace-app
  chart:
    repository: XXXX
    name: XXX
    version: 0.0.6
  values:
    applicationName: "application"
    # deployment config parameters
    deployment:
      strategy:
        type: Recreate
      image:
        repository: XXXXX
        tag: 0.0.0-develop-8-SNAPSHOT

      imagePullSecrets: "secretname"
```

Before using helm release, i deployed helm using its charts manually and I was using the earlier version fo flux `before 0.14.0`, never had this problem. I updated the flux version in the hem release but now i am getting this error.

I have provided the logs in the log section. There are two things that confuse me: 

1- the image tag specified in the logs doesn't match the application tag.

2- I used to think that the flux only scans the image tag but after looking at the logs, it seems to me that it also scans image layers (the issue that is specified in the logs exists in few of my app images), 
but the point is that it should scan the image tags not the layers. Kindly correct me if I am wrong. 

thanks

**To Reproduce**
Nill

**Expected behaviour**
flux should detect a new image and deploy it.

**Logs**

```bash
ts=2019-09-02T08:29:00.023578518Z caller=repocachemanager.go:226 component=warmer canonical_name=X:443/X/app auth="{map[docker.release.domain.com:443:<registry creds for user-admin@docker.release.domain.com:443, from namespace:secret/secret-name> index.docker.io:<registry creds for domainuser@index.docker.io, from namespace:secret/secretname>]}" err="mediaType in manifest should be 'application/vnd.docker.distribution.manifest.v2+json' not ''" ref=docker.release.domain.com:443/X/app:0.0.0-PR-237-3-SNAPSHOT
```

**Additional context**
Add any other context about the problem here, e.g 
- Flux version: 0.14.0
- Helm Operator version: 
- Kubernetes version: 
- Git provider: bitbucket
- Container registry provider: nexus
