### ISSUE TITLE
Flux doesn't upgrade helm release

### ISSUE THREAD

**Issue by adeleglise** [fluxcd/flux#2417]
**Describe the bug**
Automated helm releases are deployed, but not upgraded when a new image is found.

**To Reproduce**
Steps to reproduce the behaviour:
0. Kubernetes 1.14.6, Flux 1.14.1, Flux helm operator 0.10.1, connected to a private gitlab repo and private gitlab registry
1. Push a commit to a repo, to trigger the CI
2. Launch fluxctl sync
3. Fluxctl see the new image, commit the release file with the new image tag
4. Flux helm operator trigger the helm upgrade, but fails it

**Expected behavior**
Flux helm operator upgrade the release when a new image is found

**Logs**

 Helm operator logs:
```
 ts=2019-09-02T09:19:51.799888885Z caller=release.go:183 component=release info="processing release api-1 (as 8e1e9a2e-cb06-11e9-9e30-ac1f6b90cfa0)" action=CREATE options="{DryRun:true ReuseName:false}" timeout=500s
 ts=2019-09-02T09:22:51.49430209Z caller=operator.go:309 component=operator info="enqueuing release" resource=development:helmrelease/api-2                      
 ts=2019-09-02T09:22:51.49458506Z caller=operator.go:309 component=operator info="enqueuing release" resource=development:helmrelease/api-1
 ts=2019-09-02T09:22:51.638421148Z caller=release.go:183 component=release info="processing release api-2 (as c828c2f2-cb1f-11e9-9e30-ac1f6b90cfa0)" action=CREATE options="{DryRun:true ReuseName:false}" timeout=400s
 ts=2019-09-02T09:22:51.819936819Z caller=release.go:183 component=release info="processing release api-1 (as 8e1e9a2e-cb06-11e9-9e30-ac1f6b90cfa0)" action=CREATE options="{DryRun:true ReuseName:false}" timeout=500s
 ts=2019-09-02T09:25:51.494503037Z caller=operator.go:309 component=operator info="enqueuing release" resource=development:helmrelease/api-1
 ts=2019-09-02T09:25:51.494737742Z caller=operator.go:309 component=operator info="enqueuing release" resource=development:helmrelease/api-2
 ts=2019-09-02T09:25:52.221917531Z caller=release.go:183 component=release info="processing release api-1 (as 8e1e9a2e-cb06-11e9-9e30-ac1f6b90cfa0)" action=CREATE options="{DryRun:true ReuseName:false}" timeout=500s
 ts=2019-09-02T09:25:52.383190672Z caller=release.go:183 component=release info="processing release api-2 (as c828c2f2-cb1f-11e9-9e30-ac1f6b90cfa0)" action=CREATE options="{DryRun:true ReuseName:false}" timeout=400s
 ts=2019-09-02T09:28:51.494605759Z caller=operator.go:309 component=operator info="enqueuing release" resource=development:helmrelease/api-1
 ts=2019-09-02T09:28:51.49476549Z caller=operator.go:309 component=operator info="enqueuing release" resource=development:helmrelease/api-2
 ts=2019-09-02T09:28:51.668150398Z caller=release.go:183 component=release info="processing release api-1 (as 8e1e9a2e-cb06-11e9-9e30-ac1f6b90cfa0)" action=CREATE options="{DryRun:true ReuseName:false}" timeout=500s
 ts=2019-09-02T09:28:51.848429055Z caller=release.go:183 component=release info="processing release api-2 (as c828c2f2-cb1f-11e9-9e30-ac1f6b90cfa0)" action=CREATE options="{DryRun:true ReuseName:false}" timeout=400s
```

Tiller logs
```
[storage] 2019/09/02 09:55:31 getting last revision of "api-2"
[storage] 2019/09/02 09:55:31 getting release history for "api-2"
[kube] 2019/09/02 09:55:31 Doing get for ConfigMap: "api-2-config"
[kube] 2019/09/02 09:55:31 get relation pod of object: development/ConfigMap/api-2-config
[kube] 2019/09/02 09:55:31 Doing get for Deployment: "api-2"
[kube] 2019/09/02 09:55:31 get relation pod of object: development/Deployment/api-2
```

**Helm chart deployment :**

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: api-2
    fonction: api
    version: v1
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: api-2
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        prometheus.io/scrape: "false"
        sidecar.istio.io/inject: "false"
      labels:
        app: api-2
    spec:
      containers:
      - name: apollon
        image: "redacted/api-2:tag"
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: {{ .Values.ressources.limits.cpu }}
            memory: {{ .Values.ressources.limits.memory }}
          requests:
            cpu: {{ .Values.ressources.requests.cpu }}
            memory: {{ .Values.ressources.requests.memory }}
        ports:
        -  containerPort: 8080
           name: http
           protocol: TCP
        envFrom:
        - configMapRef:
            name: api-2-config
        env:
        - name: REDACTED
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.redacted }}
              key: REDACTED
        - name: REDACTED
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.redacted }}
              key: REDACTED
        - name: REDACTED
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.redacted }}
              key: REDACTED
      imagePullSecrets:
      - name: regcred
```

**Release file** :

```
---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: api-2
  namespace: development
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:nightly-*
spec:
  releaseName: api-2
  chart:
    git: git@redacted:redacted/repo.git
    path: charts/api-2
    ref: master
  values:
    image: redacted/api-2:tag
    replicaCount: 3
  timeout: 400
  ```
