### ISSUE TITLE
Kustomize & configMapGenerator

### ISSUE THREAD

**Issue by ChrisScottThomas** [fluxcd/flux#2426]
**Describe the bug**
When Flux is using Kustomize, it doesn't create/apply configMaps created using `configMapGenerator` from the kustomization.yaml.  I see my `variant: development` label in whatever is successfully created, but it's not creating the configMap : 
`Warning  Failed                  49m (x11 over 51m)   kubelet, vm014273        Error: configmaps "teamcity-server-env" not found`

It's also referring to a configMap with no -HASH appended, so it looks like `configMapGenerator` is being ignored all together?

**To Reproduce**
Steps to reproduce the behaviour:
my .flux.yaml just invokes kustomize
```
version: 1
commandUpdated:
  generators:
    - command: kustomize build .
  patchFile:
  - patch-ingress.yaml
  - patch-statefulset.yaml
```

my kustomization.yaml in base/ :
```
resources:
- ingress.yaml
- statefulset.yaml
configMapGenerator:
- name: config-map
  literals:
  - KEY=VALUE
  - KEY2=VALUE2
```

and in overlay/dev/:
```
commonLabels:
  variant: development
resources:
- ../../base/
- deployer-cert.yaml
- deployer-secrets.yaml
patchesStrategicMerge:
- patch-ingress.yaml
- patch-statefulset.yaml
```
Flux is watching ../overlays/dev/, with the .flux.yaml in ..

**Expected behavior**
I expect Kustomize to be able to create the configMap, and Flux to apply it.

**Logs**
```
ts=2019-09-04T13:50:44.307963919Z caller=sync.go:545 method=Sync cmd="kubectl apply -f -" took=297.392628ms err=null output="statefulset.apps/my-app configured"
```

Flux seems super happy to not quite deploy everything...

**Additional context**
Add any other context about the problem here, e.g 
- Flux version:  1.14.2
- Helm Operator version: null
- Kubernetes version: 1.13.5
- Git provider: Github.com
- Container registry provider: Private hosted.

**Comment by stefanprodan** [comment]
@2opremio can you please take a look at this? Thanks

**Comment by 2opremio** [comment]
I am overloaded with other stuff, but I will try to find time.

**Comment by ChrisScottThomas** [comment]
I fixed it.  I was using namespaces.
```
configMapGenerator:
- name: config-map
  namespace: custom-namespace
  literals:
  - KEY=VALUE
  - KEY2=VALUE2
```
