### ISSUE TITLE
Unable to apply tag filter policy using fluxctl

### ISSUE THREAD

**Issue by smartpcr** [fluxcd/flux#2433]
**Describe the bug**
 
When I ran the following command:
``` bash
fluxctl policy --workload=default:deployment/product-catalog-api --tag='product-catalog-api=*-prod-ready' --k8s-fwd-ns=flux
```

I got the following error:
``` log
Error: Traceback (most recent call last):
  File "kubeyaml.py", line 238, in <module>
  File "kubeyaml.py", line 233, in main
  File "kubeyaml.py", line 66, in apply_to_yaml
  File "site-packages/ruamel/yaml/main.py", line 452, in dump_all
  File "kubeyaml.py", line 96, in update_annotations
  File "kubeyaml.py", line 116, in manifests
TypeError: 'NoneType' object has no attribute '__getitem__'
Failed to execute script kubeyaml
```

**Expected behavior**

I should be able to specify tag filter on container's image tag

**Additional context**

I am using latest flux running AKS and git repo is Azure DevOps. 

yaml manifest file was generated using fabrikate:

``` yaml
---
# Source: chart/templates/service.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: product-catalog-api
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: 443
    targetPort: 6001
    name: "product-catalog-api-https"
  selector:
    app: product-catalog-api
---
# Source: chart/templates/deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog-api
  labels:
    app: product-catalog-api
    aadpodidbinding: sace-prod-kv-reader
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/tag.product-catalog-api: "glob:*-prod-ready"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-catalog-api
  template:
    metadata:
      labels:
        app: product-catalog-api
        aadpodidbinding: sace-prod-kv-reader
      annotations:
        flux.weave.works/automated: "false"
        flux.weave.works/tag.product-catalog-api: "glob:*-prod-ready"
    spec:
      containers:
        - name: product-catalog-api
          image: "saceprodacr.azurecr.io/product-catalog-api:745687"
          resources:
            requests:
              memory: "200Mi"
              cpu: "100m"
            limits:
              memory: "800Mi"
              cpu: "750m"
          securityContext:
            capabilities:
              drop:
              - all
          livenessProbe:
            httpGet:
              path: "/status"
              port: 6001
              scheme: HTTPS
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: "/status"
              port: 6001
              scheme: HTTPS
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 10
          env:
            - name: "ASPNETCORE_ENVIRONMENT"
              value: "Integration"
            - name: "TENANT"
              value: "onees"
            - name: "ROLE"
              value: "product-catalog-api"
            - name: DEPLOYMENT_UNIT
              value: "sace-prod-kv"
          ports:
          - containerPort: 6001
            protocol: TCP

      imagePullSecrets:
        - name: acr-auth

---
# Source: chart/templates/ingress.yaml
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: "product-catalog-api"
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  tls:
  - hosts:
    - "product-catalog-api-prod.aks.run"
    secretName: "sslcert-aks-run"
  rules:
  - host: "product-catalog-api-prod.aks.run"
    http:
      paths:
      - path: "/"
        backend:
          serviceName: "product-catalog-api"
          servicePort: 443

```
