### ISSUE TITLE
cannot unmarshal !!seq into resource.baseObject (kustomize) 

### ISSUE THREAD

**Issue by Jonathan34** [fluxcd/flux#2442]
**Describe the bug**
I just installed flux and running `fluxctl list-images --k8s-fwd-ns flux` gives the following:
```
== Error ==

Unable to parse files as manifests

Flux was unable to parse the files in the git repo as manifests,
giving this error:

    parsing YAML doc from "k8s/overlays/development/patches/routes-my-ui-patch.yaml": yaml: unmarshal errors:
  line 1: cannot unmarshal !!seq into resource.baseObject

Check that any files mentioned are well-formed, and resources are not
defined more than once. It's also worth reviewing

    https://docs.fluxcd.io/en/latest/requirements.html

to make sure you're not running into any corner cases.

If you think your files are all OK and you are still getting this
message, please log an issue at

    https://github.com/fluxcd/flux/issues

and include the problematic file, if possible.
```
the patch is a simple patch that looks like this:
```
# https://github.com/kubernetes-sigs/kustomize/blob/master/examples/jsonpatch.md
- op: replace
  path: /spec/hosts/0
  value: new-url.com
- op: replace
  path: /spec/http/0/corsPolicy/allowOrigin
  value:
      - "https://new-url.slb.com"
```

and declared as follow in kustomize
```
patchesJson6902:
  - target:
      group: networking.istio.io
      version: v1alpha3
      kind: VirtualService
      name: istio-routes
    path: patches/routes-my-ui-patch.yaml
```

**To Reproduce**
kustomize:
`Version: {KustomizeVersion:3.1.0 GitCommit:95f3303493fdea243ae83b767978092396169baf BuildDate:2019-07-26T19:21:45+01:00 GoOs:darwin GoArch:amd64}`
kubectl:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T16:54:35Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.8-gke.10", GitCommit:"f53039cc1e5295eed20969a4f10fb6ad99461e37", GitTreeState:"clean", BuildDate:"2019-06-19T20:48:40Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Expected behavior**
json patch is parsed properly

**Additional context**
Add any other context about the problem here, e.g 
- Flux version: 1.14.2
- Git provider: azure devops / git
- Container registry provider: GCR
