### ISSUE TITLE
Flux removes annotations added to cluster resources

### ISSUE THREAD

**Issue by primeroz** [fluxcd/flux#2474]
**Describe the feature**
I am not even sure this is possible since flux seems to just do a _kubectl apply_ but i thought asking about it could not harm

I am trying to add [stash backup operator](https://github.com/stashed/stash) to my deployments performed with flux.

One of the resources applied is a an [apiregistration.k8s.io/v1beta1 APIService](https://github.com/stashed/installer/blob/master/deploy/apiservices.yaml) 

the operator will annotate this resource once it verified the webhook is working as expected with 2 annotations
* admission-webhook.appscode.com/active
* admission-webhook.appscode.com/status

Flux will though overwrite the resource at next sync and remove those annotations. 

Is it possible / feasable to define a list of annotations to ignore when applying manifests ?

**Comment by stefanprodan** [comment]
The only way it will work is if you can remove those annotations from git. Flux uses kubectl 3 way merge, if the annotations are not in git, it will keep them as they are in the cluster.

**Comment by primeroz** [comment]
Interesting. 

I don't have any annotation in the git source repo , [this](https://github.com/primeroz/stash-kind-example/blob/0.9-test/rendered/stash/apiservices.yaml) is the file applied by flux 1.14.2 

The first resource in that file is the one being applied and it is 

```
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.admission.stash.appscode.com
  labels:
    app: stash
spec:
  caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN1RENDQWFDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFOTVFzd0NRWURWUVFERXdKallUQWUKRncweE9UQTVNakF4TURBek5EUmFGdzB5T1RBNU1UY3hNREF6TkRSYU1BMHhDekFKQmdOVkJBTVRBbU5oTUlJQgpJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBcFpCZTVQa25CZ3VhZ21Id3NDMWg3NHRvCk05WE5ZNGxyVVFkUmhNWmdmMFNBcGc1SzF1ZHZ4enRoUEFRUGg2YS82Q1Bock1EbGFOVGhNTm5KYTlUcko2YzgKcU9rc2M4anNrcGtUbkFnMHpTdjN3QzR1OUhPdW14YmoyZ2x5dzdFSzR5cGFnZkVkems3c2EyZ3o0VFRNZmZocApMTC9pK0lwbHYyalE3R2NhR0tzYmI3YzZJZG5QTFRhRHErQ1Fwa0VzR1cwQTVLcXdmbVR2dkd1VlgxTWovU2s1CmJKbys2NklubUJ5RU9qWE5tdXBrU0Y1UzdiR21CS1lZUy91dGlaWk5CZzdZQXlpNStueU4rcmhtMmpTaitqOGsKTjJqR01DZ3ZLZTFZaG56SStOdU9vaXJLb1VOUUk0Q2lJRDVZT0xGeUoyckZOdFVtanFUbjlmeVd6SXVuYndJRApBUUFCb3lNd0lUQU9CZ05WSFE4QkFmOEVCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHCjl3MEJBUXNGQUFPQ0FRRUFLdDNyWkpTQWVzTmJuK0NqRWtMbVBybHBwNUdBWnJCVHNWOS9udGVGeW5Zc2twRzAKekQ4NkkvajlmU2tEUUdTcmtuU2ZzOEZKQ2plK3FRRzZqbVJMVTdkYVV6TGdDd3Y3bE5QRElVVVZCVGRkc3dDbwpKenFja1FUeWc5aWY1WUN1NmUwejdIQUt6UXZ5OCt2ejZqZUVvUGk2empuYUtCcDNpOEpNY3F2eW10NXdxSTNYClRTLy82aVFHNDdDSUNVNDQ5ZkpmcmkyN3Vid1llWXkwb29qWUJ1a1FoTDl5dmtjL3lLL3Ntd1ZyVlc1azVId3AKOEdpQ1JaWVZsTFlocDRNU1ZocGROdzFoS05oU0hJZUtQWFRpV3BSNXV6eW1ncGlJbm44bXA3VzZUN3NadFgyVApVMi9wZm9HWWJZMXN6OXpISmpOY0RuTnRvanlya1BZazIrUkZ4dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  group: admission.stash.appscode.com
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: stash-operator
    namespace: stash
  version: v1alpha1
```

Basically i can see 

1. Flux apply all manifests
1. Operator patch the resource
1. kubectl get shows the annotations
1. Flux sync after 1m 
1. annotation is gone 

I can see in the flux output  on second sync 
```
...
apiservice.apiregistration.k8s.io/v1alpha1.admission.stash.appscode.com configured
apiservice.apiregistration.k8s.io/v1alpha1.repositories.stash.appscode.com unchanged
apiservice.apiregistration.k8s.io/v1beta1.admission.stash.appscode.com unchanged
...
```
