### ISSUE TITLE
Flux sync fails to run if there are any duplicate yamls in sync repo

### ISSUE THREAD

**Issue by latchmihay** [fluxcd/flux#2508]
**Describe the bug**
Flux sync fails to run if there are any duplicate yamls in sync repo

**To Reproduce**
create a duplicate file in a repo which flux syncs from, in my example i have place the same namespace file twice

**Expected behavior**
Ignore if they are duplicate and just apply over and over, or at-least have exceptions for namespace duplicates.
Perhaps duplicate checking could be a flag that operators can opt out of during flux daemon startup. 

**Logs**
```
ts=2019-10-09T14:31:58.422718237Z caller=images.go:23 component=sync-loop error="getting unlocked automated resources: duplicate definition of '<cluster>:namespace/logging' (in logging/logging-namespace.yaml and logging-namespace.yaml)"

ts=2019-10-09T14:32:08.222398153Z caller=loop.go:101 component=sync-loop err="loading resources from repo: duplicate definition of '<cluster>:namespace/logging' (in logging/logging-namespace.yaml and logging-namespace.yaml)"
```

**Additional context**

- Flux version: 1.15.0
- Helm Operator version: null
- Kubernetes version: 1.15.3
- Git provider: github
- Container registry provider: null

**Comment by hiddeco** [comment]
> Flux is a tool that automatically ensures that the state of a cluster matches the config in git.
> — [`README.md`](https://github.com/fluxcd/flux/blob/master/README.md)

As namespaces can still contain different labels or other type of metadata, the outcome by either applying over-and-over, or having exceptions for namespace duplicates will both result in an unpredictable cluster state outcome.

Ignoring one of the two isn't an option either, as Flux isn't able to tell what file contains the actual truth.

Flux blocking this is thus simply to ensure a reproducible cluster state, which is one of the main goals.

**Comment by pierretasci** [comment]
As a counter point, I am trying to use Flux with Kustomize. It fails with the error message: 

` duplicate definition of '<cluster>:kustomization/' (in cluster/overlays/minikube/foo/bar/kustomization.yaml and cluster/overlays/minikube/laurem/ipsum/kustomization.yaml)`

Each of those kustomize files setups a different controller in my cluster yet Flux believes they are applying the same change.

**Comment by latchmihay** [comment]
@pierretasci are the contents of the `kustomization.yaml` the same?

I assume they are.

**Comment by pierretasci** [comment]
They are very different.

The first one:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../base/internal/foo

# Ensure all components are deployed into system namespace
namespace: system

patchesStrategicMerge:
  - patch-webhook.yaml

secretGenerator:
  - name: injector-tls
    type: "kubernetes.io/tls"
    files:
      - tls.crt=certs/system.svc.pem
      - tls.key=certs/system.svc-key.pem
```

The second one:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../base/internal/bar

# Ensure all components are deployed into system namespace
namespace: system
```

Obviously both import further kustomize files but it seems to be complaining about the duplication of a Kustomize kind more than anything?

But at no point is there any duplication in what is being applied to the cluster.

**Comment by hiddeco** [comment]
@pierretasci your `--git-path` should be configured in such a way that it excludes Kustomization overlay directories (or any `kustomization.yaml` files in general).

It would however be friendlier from us to ignore the `Kustomization` resources when we encounter them and log a warning instead of aggressively slamming on the brake of the sync, which has been taken note of as a future improvement.

**Comment by ntx-ben** [comment]
I'm in the same boat as @pierretasci.

Using manifests factorization with kustomize. I have a single repository containing all my workloads for different overlays. Flux is instructed to read from a specific overlay using `--git-path=overlays/staging`. I would assume Flux would be able to recognize that there are multiple workloads to manage under the following setup:

```
/bases
---/app1
    kustomization.yaml (and other manifests)
---/app2
    kustomization.yaml (and other manifests)
/overlays
---/staging
------/app1
       .flux.yaml
       flux-patch.yaml
       kustomization.yaml
------/app2
       .flux.yaml
       flux-patch.yaml
       kustomization.yaml
```
The contents of each `.flux.yaml` is as such:

```
version: 1
patchUpdated:
  generators:
    - command: kustomize build ./app1 # $CWD is set to /overlays/staging
  patchFile: flux-patch.yaml
```

Getting the same error:

```
loading resources from repo: duplicate definition of '<cluster>:kustomization/' (in overlays/staging/app1/kustomization.yaml and overlays/staging/app2/kustomization.yaml
```

Is there any way to make this work using one instance of flux monitoring that /overlays/staging folder. I don't want to have an instance of flux per micro-service...
