### ISSUE TITLE
Manifest factorization docs show wrong example for patchUpdated Kustomize.

### ISSUE THREAD

**Issue by heprotecbuthealsoattac** [fluxcd/flux#2555]
At the end of https://docs.fluxcd.io/en/stable/references/fluxyaml-config-files.html it says:
```
Lastly, here is another example using Kustomize which is much simpler than the commandUpdated-based example presented earlier.
```

However the actual snippet is this:
```
version: 1
patchUpdated:
  generators:
    - command: helm template ../charts/mychart -f overrides.yaml
  patchFile: flux-patch.yaml
```

Which is the same snippet as the one above describing how to deploy a Helm chart without a Tiller installation.
