### ISSUE TITLE
fluxcd failed to automate helmrelease chart-image

### ISSUE THREAD

**Issue by HaveFun83** [fluxcd/flux#2618]
**Describe the bug**

fluxcd is unable to automate a helmrelease structure / chart-image with more than two path values within the repository statement.

Example image path:
`private-docker-registry.net/public/bitnami/redis:5.0.6`
` <registry> <repository (with more than two values)>:<imagetag>`

The following helmrelease structure failed to automate the chart-image as the repository statement only accept two path values.
```
values:
  image:
    registry: docker.io
    repository: repo/image
    tag: version
```

We found the code source for this behavior here: https://github.com/fluxcd/flux/blob/07b3d3d608dc53738d9778d6dd23355e8f50e550/pkg/image/image.go#L145-L161

**To Reproduce**
Steps to reproduce the behaviour:

If you check-in an helmrelease with the following structure:
```
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: test
  annotations:
    flux.weave.works/automated: true
    flux.weave.works/tag.chart-image: semver:~3.8
spec:
  releaseName: rabbitmq
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: rabbitmq
    version: 6.8.4
  values:
    image:
      registry: private-docker-registry.net/public
      repository: bitnami/rabbitmq
      tag: 3.8.0-debian-9-r0
```
fluxcd is unable to automate the helmrelease with the following error:
```
ts=2019-11-12T15:52:53.944052104Z caller=loop.go:145 component=sync-loop jobID=e4f37091-fe83-3ccb-5c03-fb5fad94c2ae state=done success=false err="verifying changes: failed to verify changes: the image for container \"chart-image\" in resource \"gitops-system:helmrelease/redis-demo\" should be \"private-docker-registry.net/public/bitnami/redis:5.0.6\", but is \"private-docker-registry.net/bitnami/redis:5.0.6\""
```
we also tried the following
```
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: test
  annotations:
    flux.weave.works/automated: true
    flux.weave.works/tag.chart-image: semver:~3.8
spec:
  releaseName: rabbitmq
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: rabbitmq
    version: 6.8.4
  values:
    image:
      registry: private-docker-registry.net
      repository: public/bitnami/rabbitmq
      tag: 3.8.0-debian-9-r0
```
than the error will be
```
ts=2019-11-12T18:30:13.745729746Z caller=images.go:159 component=sync-loop err="fetching image metadata for private-docker-registry.net/bitnami/redis: errors:\ndenied: requested access to the resource is denied\nunauthorized: authentication required
```
as `public/` will be ignored and stripped out

**Expected behavior**

fluxcd should support a repository statement with more than 2 path values

**Logs**
If applicable, please provide logs of `fluxd` or the helm-operator. In a standard stand-alone installation of Flux, you'd get this by running `kubectl logs -n default deploy/flux`.

see above

**Additional context**
Add any other context about the problem here, e.g 
- Flux version:  1.15.0
- Helm Operator version: 1.0.0-rc3
- Kubernetes version: 1.15.4
- Git provider: private gitlab
- Container registry provider: private harbor

**Comment by hiddeco** [comment]
The structure you are linking to works fine, and is actually covered by tests, [as can be seen here](https://github.com/fluxcd/flux/blob/07b3d3d608dc53738d9778d6dd23355e8f50e550/pkg/image/image_test.go#L54).

Does this problem only occur for the automation of `HelmRelease` resources, or for all resources Flux handles? The answer to this could possibly reduce the size of the haystack, before I go looking for the needle.

**Comment by HaveFun83** [comment]
> The structure you are linking to works fine, and is actually covered by tests, [as can be seen here](https://github.com/fluxcd/flux/blob/07b3d3d608dc53738d9778d6dd23355e8f50e550/pkg/image/image_test.go#L54).
> 
> Does this problem only occur for the automation of `HelmRelease` resources, or for all resources Flux handles? The answer to this could possibly reduce the size of the haystack, before I go looking for the needle.

Thanks for looking into this issue.
The error only occurs on helmReleases with the following structure:
```
values:
  image:
    registry: docker.io
    repository: repo/image
    tag: version
```
