### ISSUE TITLE
Not able to pull tags for some of the images

### ISSUE THREAD

**Issue by to266** [fluxcd/flux#2624]
**Describe the bug**
Flux is not able to pull image tags from a private GCR, but only for some of the images:
```
caller=warming.go:180 component=warmer canonical_name=us.gcr.io/luminovo-default/training auth={map[]} err="requesting tags: denied: Failed to read tags for host 'us.gcr.io', repository '/v2/luminovo-default/training/tags/list'"
```
Strangely enough, flux is able to pull many other image tags from the same repo (`us.gcr.io/luminovo-default/training-operator` and similar) that are created with the same CI steps. I have also verified that the tags are present (and they're successfully used by the operator, for example).

**Expected behavior**
To be able to fetch tags and / or have a clearer error - does not look like it's a problem with auth, but then what?

**Additional context**
- Flux version: 1.15.0
- Kubernetes version: 1.14.8
- Container registry provider: GCR

**Comment by squaremo** [comment]
The `auth={map[]}` bit of the log message indicates that it didn't find credentials (in an imagePullSecret attached to the workload in question, or its service account). If you're running on GCP it will attempt to get a token from the metadata service, and I don't think those get reported in the log message.

I would check that the GCP service account that's running the workload _also_ has permissions to see the image repo in question. I don't know GCP/GKE well enough to go any further than that, sorry!

**Comment by to266** [comment]
This is super surprising, since it's essentially able to fetch many other images. The `HelmRelease` in question (with some trimming) looks line this:
```yaml
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: training-orchestrator
  namespace: testing
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.orchestrator: glob:dev-*
    fluxcd.io/tag.operator: glob:dev-*
    fluxcd.io/tag.training: glob:dev-*
spec:
  releaseName: training-orchestrator-testing
  chart:
    git: <our-repo>
    ref: master
    path: training-orchestrator/training-orchestrator
  values:
    imagePullSecrets:
    - name: gcr-pull-key
    training:
      image:
        repository: us.gcr.io/luminovo-default/training
        tag:  dev-2ce3b890 # cannot pull this tag
    orchestrator:
      replicaCount: 1
      serviceAccount:
        create: true
      image:
        repository: us.gcr.io/luminovo-default/training-orchestrator
        tag: dev-2ce3b890 # gets this tag without problems
    operator:
      replicaCount: 1
      serviceAccount:
        create: true
      image:
        repository: us.gcr.io/luminovo-default/training-operator
        tag: dev-2ce3b890 # gets this tag without problems
```
Also I just confirmed that the `flux` serviceaccount indeed has an identical `imagePullSecret` (can't be literally the same, since it's in a different namespace) attached to it. Any ideas?
