### ISSUE TITLE
Why does Flux consume so much memory? answer: > 200k resources in the cluster

### ISSUE THREAD

**Issue by hiddeco** [fluxcd/flux#2633]
**Describe the bug**
The Flux daemon uses an increasing amount of RAM (up to 2.5GB before getting OOM killed for Flux `1.16`) with `--sync-garbage-collection=true` and `--manifest-generation=true` set, and just `1.9M` resource files on disk.

**To Reproduce**
Steps to reproduce the behaviour:
1. Spin up a Flux daemon with `--sync-garbage-collection=true` and `--manifest-generation=true` set. The `.flux.yaml` file on this setup is:

   ```yaml
   version: 1
   patchUpdated:
     generators:
     - command: cat *.yaml
     patchFile: flux-patch.conf
   ```

**Expected behavior**
A more graceful amount of memory being used.

**Additional context**
- Flux version: behaviour has been reported for version `1.15.0` and `1.16.0`

**Comment by hiddeco** [comment]
#### heap and goroutine dumps
User was requested to provide a heap and goroutines dumps, the easiest way for to do this is by making two `curl` calls:

```console
/home/flux # curl -sK -v http://localhost:3030/debug/pprof/heap > heap.out
/home/flux # curl -sK -v http://localhost:3030/debug/pprof/goroutines > goroutines.out
```

No spurious amount of goroutines can be observed, and the reported `inuse_space` only totals for about `7-9MB`.

#### `/tmp`

Garbage collection of temporary resources seems to be okay:

```console
/home/flux # ls /tmp | wc -l
5
/home/flux # ls /tmp
flux-gitclone236288646  flux-working285393832   flux-working842178345   goroutine-2.4g          heap-2.4g
``` 

#### `top`

`top` shows a total mem usage of the `fluxcd` process of `2495m`:

```console
PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
    7     1 root     S    2495m  16%   3   0% fluxd --memcached-hostname=<snip> --listen-metrics=:3031 --git-ci-skip --ssh-keygen-dir=/var/fluxd/keygen --k8s-secret-name=f
```

#### `pmap`

```console
pmap 7                       
7: fluxd --memcached-hostname=<snip> --listen-metrics=:3031 --git-ci-skip --ssh-keygen-dir=/var/fluxd/keygen --k8s-secret-name=flux-git-deploy --git-url=<snip> --git-bra                                                            
0000000000400000   16780K r-xp  /usr/local/bin/fluxd                                                      
0000000001463000   17104K r--p  /usr/local/bin/fluxd                                                      
0000000002517000     512K rw-p  /usr/local/bin/fluxd                                                      
0000000002597000     204K rw-p    [ anon ]                                                                
000000c000000000   67584K rw-p    [ anon ]                                                                
000000c004200000   20480K rw-p    [ anon ]                   
...
... TONS OF ANON
00007fca40213000     960K rw-p    [ anon ]
00007fca40307000   24172K rw-p    [ anon ]
00007fca41aaa000   41096K rw-p    [ anon ]
00007ffd66deb000     132K rw-p  [stack]
00007ffd66e0f000      12K r--p  [vvar]
00007ffd66e12000       8K r-xp  [vdso]
ffffffffff600000       4K r-xp  [vsyscall]
mapped: 2555840K
```

**Comment by 2opremio** [comment]
It seems like the memory consumption peaks up almost immediately (after Flux 1.16 starts up) and then Flux gets killed.

Also, it seems like Flux is not killed anymore when setting `GOGC=25`, with a stable memory consumption (no build up in memory usage, indicating no leaks are happening).

This points to the garbage collector not running often enough to satisfy both:
* The memory limit of the pod
* The frequency and size of Flux's allocations

If the memory consumption of Flux keeps being stable (i.e. indicating no leaks) while running with `GOGC=25`, I am not sure what else can we do (or rather what's worth doing) in order to fix this.

However, 2.5 GB of memory seems like a huge amount of memory for program like Flux for a normal-sized cluster.

So. I think that at least we should gather more information to fully explain why that is happening. e.g. amount of resources in the cluster, size of the git repo etc ...

**Comment by nabadger** [comment]
Hi, I work with Francesco who reported this issue via slack.

We've been running `v1.16.0` with `GOGC=25` for about an hour, with only 1 OOMKilled event which is not bad.

![2019-11-26_16-30](https://user-images.githubusercontent.com/28828562/69653181-b35cc280-106a-11ea-9217-43c73d453182.png)

The Git repo which Flux references is `77M` - this is a monorepo, so contains kustomize and rendered manifests for all environments.

The Git path that Flux points to inside this repo is `1.8M` (the rendered manifests for a specific environment).

We deploy `236` Kubernetes resources (where a resource can be something like a `ClusterRole`, `Deployment`, `DaemonSet`, `Ingress` etc).

Our flux.yaml (we also run fluxcloud/filebeat sidecars, but i've removed those)
```yaml

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    instance: flux-apps
    name: flux
  name: flux-apps
  namespace: flux-apps
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      instance: flux-apps-fluxd
      name: flux
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        instance: flux-apps-fluxd
        name: flux
    spec:
      automountServiceAccountToken: false
      containers:
      - args:
        - --memcached-hostname=flux-apps-memcached.flux-apps.svc.cluster.local
        - --listen-metrics=:3031
        - --git-ci-skip
        - --ssh-keygen-dir=/var/fluxd/keygen
        - --k8s-secret-name=flux-git-deploy
        - --git-url=<redacted>
        - --git-branch=master
        - --git-label=flux-dev-nb1-sync
        - --git-poll-interval=1m
        - --sync-interval=5m
        - --sync-garbage-collection=true
        - --git-path=rendered/environments/dev/nb1
        - --manifest-generation=true
        env:
        - name: GOGC
          value: "25"
        image: fluxcd/flux:1.16.0
        imagePullPolicy: IfNotPresent
        name: flux
        ports:
        - containerPort: 3030
          name: api
          protocol: TCP
        - containerPort: 3031
          name: metrics
          protocol: TCP
        resources:
          limits:
            cpu: 750m
            memory: 1500Mi
          requests:
            cpu: 250m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/fluxd/ssh
          mountPropagation: None
          name: git-key
          readOnly: true
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          mountPropagation: None
          name: flux-apps-token-sc2w7
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: flux-apps
      serviceAccountName: flux-apps
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
      volumes:
      - name: git-key
        secret:
          defaultMode: 256
          optional: false
          secretName: flux-git-deploy
      - name: flux-apps-token-sc2w7
        secret:
          defaultMode: 420
          optional: false
          secretName: flux-apps-token-sc2w7
```
