### ISSUE TITLE
Why doesn't garbage collection work when restricting Flux's RBAC permissions?

### ISSUE THREAD

**Issue by tl-alexandre-kaskasoli** [fluxcd/flux#2648]
**Describe the bug**
fluxd doesn't delete resources managed by flux when they are removed from the git repository, _when fluxd is running with a role with limited privileges_ and garbage collection enabled.

we want to restrict the resources that developers can create/alter in a given namespace, so we're limiting fluxd's privileges using RBAC.

when we don't limit privileges (ie: when flux is running with `cluster-admin` privileges), garbage collection works as expected.

**To Reproduce**
Steps to reproduce the behaviour:
1. use the following service account and role for flux:
```
---
# The service account, cluster roles, and cluster role binding are
# only needed for Kubernetes with role-based access control (RBAC).
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    name: flux-team-a
  name: flux-team-a
  namespace: team-a
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  labels:
    name: flux-team-a
  name: flux-team-a
  namespace: team-a
rules:
  - apiGroups: ["*"]
    resources:
      [
        "configmaps",
        "cronjobs",
        "deployments",
        "horizontalpodautoscalers",
        "jobs",
        "networkpolicies",
        "persistentvolumeclaims",
        "persistentvolumes",
        "pods",
        "replicasets",
        "rolebindings",
        "roles",
        "serviceaccounts",
        "services",
        "secrets",
        "statefulsets",
      ]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels:
    name: flux-team-a
  name: flux-team-a
  namespace: team-a
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flux-team-a
subjects:
  - kind: ServiceAccount
    name: flux-team-a
    namespace: team-a
```
2. create a resource in the flux git repository, for example a `configmap`, witness the resource being created
3. delete the resource in the flux git repository, notice the resource does not get deleted

**Expected behavior**
expected that flux would delete resources create by flux when it has sufficient permissions to do so.

**Logs**
N/A - no output in logs regarding the above.

**Additional context**
- Flux version: 1.15
- Helm Operator version: N/A
- Kubernetes version: 1.14
- Git provider: GitHub
- Container registry provider: N/A

**Comment by tl-alexandre-kaskasoli** [comment]
I noticed that adding the following ClusterRole is sufficient to make garbage collection work.

```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    name: flux-team-a
  name: flux-team-a
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list"]
```

It would be useful to document the minimum permissions needed for garbage collection, so users can apply the principle of least privileges.

**Comment by 2opremio** [comment]
In order to garbage-collect resources of certain `apiVersion` and `Kind` (e.g. `v1` `ConfigMap`), Flux needs to be able to:

1. Discover that `apiVersion/Kind` through the discovery API, which is [allowed by default](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#discovery-roles) for every user. I doubt your configuration needs changing anything in this regard, since everything works when being permissive about get/watch/list
2. list resources of `apiVersion/Kind`, in order to figure out whether they are not referenced by the git repository anymore. 
3. delete resources of `apiVersion/Kind` in order to garbage-collect unreferenced resources.

Depending on your configuration, e.g. if you use namespace filtering (`--k8s-allow-namespace`), you may also need to allow listing namespaces. In versions < 1.16 (like your case), you had to be able to list namespaces regardless of your `--k8s-allow-namespace` flag (because #2520 wasn't yet included).

Also, following my description above, it should be enough to use your initial RBAC configuration with minor adjustments. You could either:
* Add permissions for listing namespaces
* If you don't use `--k8s-allow-namespace`, upgrading to flux 1.16 is probably enough.

I haven't tested this explicitly (I am just using my code knowledge). Could you give it a try and report back?

**Comment by tl-alexandre-kaskasoli** [comment]
I tried 

```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    name: flux-cluster-read
  name: flux-cluster-read
rules:
  - apiGroups: ["*"]
    resources: ["namespaces", "customresourcedefinitions"]
    verbs: ["get", "list", "watch"]
```

That wasn't sufficient. Currently using:

```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    name: flux-cluster-read
  name: flux-cluster-read
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
```

Which gets the job done.

The logs don't show any output related to a lack of permissions on the resources that need to be garbage-collected.

**Comment by 2opremio** [comment]
> I tried
> 
> ```
> apiVersion: rbac.authorization.k8s.io/v1beta1
> kind: ClusterRole
> metadata:
>   labels:
>     name: flux-cluster-read
>   name: flux-cluster-read
> rules:
>   - apiGroups: ["*"]
>     resources: ["namespaces", "customresourcedefinitions"]
>     verbs: ["get", "list", "watch"]
> ```
> 
> That wasn't sufficient. 


I meant adding that on top of what you already have. Is that what you did?

**Comment by tl-alexandre-kaskasoli** [comment]
Apologies for not being clear. Yes that was added on top of what I outlined in the first post.

**Comment by goober** [comment]
We are facing the same issues where flux does not delete objects that have been delete from the repository. We are using the the 1.17.0 version. And if I remember correctly it worked with the feature-flag `--sync-garbage-collection` in 1.16.x.

We have currently the following RBAC on each namespace that flux should handle:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flux:application-deployer
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - configmaps
      - serviceaccounts
    verbs:
      - create
      - get
      - patch
      - delete
      - list
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - get
      - patch
      - delete
      - list
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - create
      - get
      - patch
      - delete
      - list
  - apiGroups:
      - route.openshift.io
    resources:
      - 'routes/custom-host'
    verbs:
      - create
  - apiGroups:
      - apps.openshift.io
    resources:
      - deploymentconfigs
    verbs:
      - create
      - get
      - patch
      - delete
      - list
  - apiGroups:
      - "extensions"
    resources:
      - ingresses
    verbs:
      - create
      - get
      - patch
      - delete
      - list
  - apiGroups:
      - "batch"
    resources:
      - cronjobs
      - jobs
    verbs:
      - create
      - get
      - patch
      - delete
      - list
  - apiGroups:
      - "bitnami.com"
    resources:
      - sealedsecrets
    verbs:
      - create
      - get
      - patch
      - delete
      - list
```
