### ISSUE TITLE
Manifest comments are removed

### ISSUE THREAD

**Issue by rtluckie** [fluxcd/flux#2660]
**Describe the bug**
Comments in yaml manifests are removed when images are updated via a automated release

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a manifest w/ automation enabled with a comment (see below)
2. Trigger a image update
3. Observe comment is removed

**Expected behavior**
Comments should persist

**Additional context**
Add any other context about the problem here, e.g 
- Flux version: `flux:1.15.0`
- Helm Operator version: `helm-operator:1.0.0-rc3`
- Kubernetes version: `1.16.3`
- Git provider: `github enterprise`
- Container registry provider: `docker.io`

```yaml
##################################################
#            **DO NOT EDIT MANUALLY**
#
# This file is auto-generated by `make generate`
##################################################
 ---
 apiVersion: helm.fluxcd.io/v1
 kind: HelmRelease
...
```
