### ISSUE TITLE
Invalid image ID on HelmRelease

### ISSUE THREAD

**Issue by alastairs** [fluxcd/flux#2663]
### Describe the bug
Flux incorrectly updates `HelmRelease`s when the tag is specified separately from the image, resulting in an invalid image ID error. I think also there's been a regression of the fix for #1290, or it wasn't fixed as I expected from reading that issue description. 

### To Reproduce
1. Configure FluxCD and the Helm Operator.
2. Define a `HelmRelease` for a chart with an `imageTag` value, e.g. `stable/traefik` or `elastic/filebeat`. A sample `HelmRelease` is included below
3. Set Flux automation annotations, including to point Flux at the `imageTag` value
4. Watch Flux update the image reference to the latest tag (1.7.19 at the time of writing)
5. Watch further Helm deployments fail

#### Sample HelmRelease
```yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: traefik
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:~1.7
    # Tell Flux where to find the tag value
    tag.fluxcd.io/traefik: imageTag
spec:
  releaseName: belligerent-dog
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: traefik
    version: 1.79.0
  rollback:
    enable: true
  values:
    ## Default values for Traefik
    image: traefik
    imageTag: v1.7
```

**Expected behavior**
Flux overwrites the `imageTag` value with the new tag version. Instead, however, it overwrites the `image` value, appending the tag. This results in Helm attempting to deploy an image like `traefik:v1.7.19:v1.7`. Flux logs a message stating `expected image name as either <image>:<tag> or just <image>: invalid image ID`.

**Additional context**
Add any other context about the problem here, e.g 
- Flux version: 1.16
- Helm Operator version: 1.0.0-rc4
- Kubernetes version: 1.13 (GKE)
- Git provider: GitHub
- Container registry provider: Docker Hub

**Comment by alastairs** [comment]
I wondered if this might be because the traefik tags are `v<semver>`, rather than just `<semver>`. However, the following `HelmRelease` for filebeat displays the same behaviour

```yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: filebeat
  namespace: waives-system
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:~7.4
    # Tell Flux where to find the tag value
    tag.fluxcd.io/traefik: imageTag
spec:
  releaseName: filebeat
  chart:
    repository: https://helm.elastic.co
    name: filebeat
    version: 7.4.1
  values:
    image: docker.elastic.co/beats/filebeat
    imageTag: 7.4.1
```

**Comment by stefanprodan** [comment]
You're missing the repository and filter annotations https://docs.fluxcd.io/en/stable/references/helm-operator-integration.html#annotations

**Comment by stefanprodan** [comment]
Try this:

```yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: filebeat
  namespace: waives-system
  annotations:
    filter.fluxcd.io/filebeat: semver:~7.4
    tag.fluxcd.io/filebeat: imageTag
    repository.fluxcd.io/filebeat: image
spec:
  releaseName: filebeat
  chart:
    repository: https://helm.elastic.co
    name: filebeat
    version: 7.4.1
  values:
    image: docker.elastic.co/beats/filebeat
    imageTag: 7.4.1
```
