### ISSUE TITLE
Pass image information to pod

### ISSUE THREAD

**Issue by Miradorn** [fluxcd/flux#2689]
**Describe the feature**

I need to get the tag of the container image from within the container.
Due to our build pipeline, the Tag is not known at build time (It is build/tagged with the current commit sga and tagged with a release version later).
Therefore I think a solution would be to somehow pass the image tag that Flux discovers to the container as an environment variable, maybe with a yaml anchor or with something different.

As a shortened example using a helmrelease:

```
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: apollon
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:~0
spec:
  releaseName: example
  chart:
    ...
  values:
    image:
      repository: eu.gcr.io/production-255914/apollon
      tag: &image-tag 0.9.2
  
    env:
      IMAGE_TAG: *image-tag
```

If you have another solution for this problem or if it already works somehow please enlighten me! :D 

**Expected behavior**
As a user I have a way to pass the image information (name, tag) to the container, e.g. as an Environment variable.
