### ISSUE TITLE
flux automated image updated stops updating if there are any corrupted image manifests

### ISSUE THREAD

**Issue by isen-ng** [fluxcd/flux#2690]
**Describe the bug**
I have seen this issue https://github.com/fluxcd/flux/issues/1701 but I think this is still not working for automated workloads.

We have a helm release with multiple images on automated releases. Recently we encountered a corrupted manifest for datadog and automated updating of images stopped completely. I should add that updating the image values/helm charts manually still cause them to be deployed successfully, so this should not be a helm-operator problem.

**To Reproduce**
Steps to reproduce the behaviour:
0. We installed flux with helm-operator on our kubernetes cluster using your helm chart, 0.15.0
1. Setup automated release

```
---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  namespace: my_namespace
  name: my_application
  annotations:
    fluxcd.io/automated: "true"
    repository.fluxcd.io/service1: service1.image
    repository.fluxcd.io/service2: service2.image
    repository.fluxcd.io/service3: service3.image
    repository.fluxcd.io/service4: service4.image
    filter.fluxcd.io/service1: regexp:^([0-9]+)\.([0-9]+)\.([0-9]+)-alpha[0-9]{4}-[a-z0-9]{7}$
    filter.fluxcd.io/service2: regexp:^([0-9]+)\.([0-9]+)\.([0-9]+)-alpha[0-9]{4}-[a-z0-9]{7}$
    filter.fluxcd.io/service3: regexp:^([0-9]+)\.([0-9]+)\.([0-9]+)-alpha[0-9]{4}-[a-z0-9]{7}$
    filter.fluxcd.io/service4: regexp:^([0-9]+)\.([0-9]+)\.([0-9]+)-alpha[0-9]{4}-[a-z0-9]{7}$
spec:
  chart:
    git: git@github.com:traveloka/tvlk-eas
    ref: master
    path: ci-cd/helm-charts/eas
  rollback:
    # If set, will perform rollbacks for this release.
    enable: true
    # If set, will force resource update through delete/recreate if needed. This may cause downtime, (for example: delete and recreate Ingress rules)
    force: false
    # Prevent hooks from running during rollback.
    disableHooks: false
    # Time in seconds to wait for any individual Kubernetes operation. Disable because of this bug https://github.com/fluxcd/flux/issues/2250
    # timeout: 120
    # If set, will wait until all Pods, PVCs, Services, and minimum
    # number of Pods of a Deployment are in a ready state before
    # marking the release as successful. It will wait for as long
    # as the set timeout.
    wait: true
  values:
    service1:
        image: my_aws_ecr_repo.aws.com/my_service1:1.0.1-alpha0001-1234567
    service1:
        image: my_aws_ecr_repo.aws.com/my_service2:1.0.1-alpha0001-1234567
    service1:
        image: my_aws_ecr_repo.aws.com/my_service3:1.0.1-alpha0001-1234567
    service1:
        image: my_aws_ecr_repo.aws.com/my_service4:1.0.1-alpha0001-1234567
```

2. Setup latest datadog

```
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: datadog
  namespace: kube-system
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: datadog
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: datadog
    version: 1.38.10
  rollback:
    # If set, will perform rollbacks for this release.
    enable: true
    # If set, will force resource update through delete/recreate if needed. This may cause downtime, (for example: delete and recreate Ingress rules)
    force: true
    # Prevent hooks from running during rollback.
    disableHooks: false
    # Time in seconds to wait for any individual Kubernetes operation. Disable because of this bug https://github.com/fluxcd/flux/issues/2250
    # timeout: 120
    # If set, will wait until all Pods, PVCs, Services, and minimum
    # number of Pods of a Deployment are in a ready state before
    # marking the release as successful. It will wait for as long
    # as the set timeout.
    wait: true
  values:
    datadog:
      apiKeyExistingSecret: "datadog-keys"
      appKeyExistingSecret: "datadog-keys"
      logsEnabled: true
      logsConfigContainerCollectAll: true
      apmEnabled: false
    clusterAgent:
      enabled: true
      metricsProvider:
        enabled: true
      token: "my_token"
    daemonset:
      containers:
        agent:
          logLevel: "WARN"
```

3. Make new releases for service 1, 2, 3 and 4
4. Automated images are not updated in the git repository

**Expected behavior**
Automated images should be updated in the git repository

**Logs**

This is the logs we see repeating in the flux container
```
ts=2019-12-13T16:03:41.870915742Z caller=repocachemanager.go:223 component=warmer canonical_name=index.docker.io/datadog/agent auth={map[]} warn="manifest for tag 7.15.1 missing in repository datadog/agent" impact="flux will fail to auto-release workloads with matching images, ask the repository administrator to fix the inconsistency"
ts=2019-12-13T16:03:42.125858497Z caller=repocachemanager.go:223 component=warmer canonical_name=index.docker.io/datadog/agent auth={map[]} warn="manifest for tag 7.15.1 missing in repository datadog/agent" impact="flux will fail to auto-release workloads with matching images, ask the repository administrator to fix the inconsistency"
ts=2019-12-13T16:03:42.12591486Z caller=warming.go:206 component=warmer updated=datadog/agent successful=0 attempted=2
ts=2019-12-13T16:03:42.126158182Z caller=images.go:17 component=sync-loop msg="polling for new images for automated workloads"
<and nothing else for a while, then repeats this>
```

I should say that the automated releases has worked prior to this and suddenly stopped working without any update to the charts or value files. So that means that the regex that filters the images work. I've also verified that the images exist in the repository and verified that the polling agent has access to the repository.

Running `fluxctl list-images` does not list the new images available in the repository as well. (Which I strongly think is where the problem might lie).

**Additional context**
Add any other context about the problem here, e.g 
- Flux version: 1.15.0
- Helm Operator version: 0.10.1
- Kubernetes version: 1.13.x
- Git provider: github
- Container registry provider: AWS ECR
