### ISSUE TITLE
Automated release picks image contrary to filter

### ISSUE THREAD

**Issue by noamt** [fluxcd/flux#2706]
**Describe the bug**
The `HelmRelease` updates with new tags that don't match the filter

**To Reproduce**

1. Single cluster
2. 2 namespaces - `research` and `production`
3. Single chart repository that defines a web app
4. A `HelmRelease` object that controls the web app on the `research` namespace with a filter of `'glob: develop-*'`
5. A `HelmRelease` object that controls the web app on the `production` namespace with a filter of `'glob: master-*'`
6. Release an image tagged with `develop-$HASH`
7. Both `research` and `production` `HelmRelease`s are updated with the new image.

Research `HelmRelease`:
```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: api-research
  namespace: research
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    repository.fluxcd.io/api-research: api.image.repository
    tag.fluxcd.io/api-research: api.image.tag
    filter.fluxd.io/api-research: 'glob: develop-*'
spec:
  releaseName: api-research
  chart:
    git: git@github.com:******
    ref: master
    path: charts/webapp
  values:
    api:
      image:
        repository: eu.gcr.io/****/webapp
        tag: develop-$HASH
        pullPolicy: Always
```

Production `HelmRelease`:
```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: api-production
  namespace: production
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    repository.fluxcd.io/api-production: api.image.repository
    tag.fluxcd.io/api-production: api.image.tag
    filter.fluxd.io/api-production: 'glob: master-*'
spec:
  releaseName: api-production
  chart:
    git: git@github.com:*******
    ref: master
    path: charts/webapp
  values:
    api:
      image:
        repository: eu.gcr.io/****/webapp
        tag: develop-$HASH # this was "lastest"
        pullPolicy: Always
```

**Expected behavior**
The `HelmRelease` defined with a `'glob: master-*'` expression should not pick images prefixed with `develop-` 

**Additional context** 
- Flux version: docker.io/fluxcd/flux:1.16.0
- Helm operator version: docker.io/fluxcd/helm-operator-prerelease:helm-v3-dev-ded36aeb 
- Targeted Helm version: v3
- Kubernetes version: v1.14.8-gke.18
- Git provider: github
- Container registry provider: Google Cloud
