### ISSUE TITLE
There was an error trying to release: Error: no changes made in repo

### ISSUE THREAD

**Issue by aimuz** [fluxcd/flux#2724]
**Describe the bug**
I have the following error using 
```
fluxctl release --workload=demo:deployment/podinfo -i stefanprodan/podinfo:3.0.5 --k8s-fwd-ns flux-master
```

```
fluxctl list-images --k8s-fwd-ns flux-master --namespace demo
```

```text
WORKLOAD                 CONTAINER  IMAGE                   CREATED
demo:deployment/podinfo  podinfod   stefanprodan/podinfo    
                                    |   9715769             27 Oct 18 08:52 UTC
                                    |   7181351             25 Mar 19 10:13 UTC
                                    |   2192219             18 Aug 18 11:24 UTC
                                    |   3.1.5               06 Nov 19 22:35 UTC
                                    |   3.1.4               06 Nov 19 22:21 UTC
                                    |   3.1.3               06 Nov 19 22:16 UTC
                                    |   3.1.2               06 Nov 19 22:02 UTC
                                    |   3.1.1               06 Nov 19 22:00 UTC
                                    |   3.1.0               06 Nov 19 21:59 UTC
                                    |   3.0.5               05 Sep 19 15:38 UTC
                                    : (4 image(s) omitted)  
                                    '-> 2.1.3               13 Aug 19 09:33 UTC
                         init       alpine                  
                                    |   3                   24 Dec 19 19:20 UTC
                                    |   3.11                24 Dec 19 19:20 UTC
                                    |   3.11.2              24 Dec 19 19:20 UTC
                                    |   latest              24 Dec 19 19:20 UTC
                                    |   3.11.0              19 Dec 19 23:21 UTC
                                    |   20191219            19 Dec 19 23:21 UTC
                                    |   edge                19 Dec 19 23:21 UTC
                                    |   20191114            14 Nov 19 22:19 UTC
                                    '-> 3.10                21 Oct 19 17:21 UTC
                                        3.10.3              21 Oct 19 17:21 UTC
```

**To Reproduce**
Steps to reproduce the behaviour:

The only difference between me and the official `flux-get-started`  is this file

podinfo-dep.yaml

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: demo
  labels:
    app: podinfo
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.init: regex:^3.10.*
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: podinfo
    spec:
      initContainers:
      - name: init
        image: alpine:3.10.1
        command:
        - sleep
        - "1"
      containers:
      - name: podinfod
        image: stefanprodan/podinfo:2.1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9898
          name: http
          protocol: TCP
        command:
        - ./podinfo
        - --port=9898
        - --level=info
        - --random-delay=false
        - --random-error=false
        env:
        - name: PODINFO_UI_MESSAGE
          value: "Greetings human!"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9898
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9898
        resources:
          limits:
            cpu: 1000m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi

```

**Expected behavior**

**Logs**

```
ts=2020-01-08T02:58:17.633734356Z caller=loop.go:135 component=sync-loop jobID=15d37d7b-0f3c-b168-27fb-62ed9b2ec878 state=in-progress
ts=2020-01-08T02:58:17.682451417Z caller=releaser.go:59 component=sync-loop jobID=15d37d7b-0f3c-b168-27fb-62ed9b2ec878 type=release updates=0
ts=2020-01-08T02:58:17.682495712Z caller=releaser.go:61 component=sync-loop jobID=15d37d7b-0f3c-b168-27fb-62ed9b2ec878 type=release exit="no images to update for services given"
ts=2020-01-08T02:58:17.689840253Z caller=loop.go:145 component=sync-loop jobID=15d37d7b-0f3c-b168-27fb-62ed9b2ec878 state=done success=false err="no changes made in repo"
ts=2020-01-08T02:58:18.144497474Z caller=loop.go:127 component=sync-loop event=refreshed url=ssh://git@gitee.com/ryzhaimuz/flux-get-started.git branch=master HEAD=ff7fa4360a35efae69e24e52a4b35dec1c743ff1
```

**Additional context**
Add any other context about the problem here, e.g 
- Flux version: 1.17.0
- Helm Operator version: 
- Kubernetes version: v1.15.4
- Git provider:
- Container registry provider:
