### ISSUE TITLE
type="internal kubernetes error"... unknown (get customresourcedefinitions.apiextensions.k8s.io)

### ISSUE THREAD

**Issue by icy** [fluxcd/flux#2725]
**Describe the bug**

I see some strange error message in flux daemon logs, but there are no thing else

**To Reproduce**

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux
  namespace: flux
spec:
  template:
    spec:
      containers:
      - name: flux
        args:
        - --memcached-hostname=memcached.flux.svc.cluster.local
        - --memcached-service=
        - --ssh-keygen-dir=/var/fluxd/keygen
        - --git-url=git@github.com:myCompany/testing-repository.git
        - --git-branch=testing-branch
        - --git-path=platform/k8s/services/euw1-infra-fluxcd/
        - --git-label=flux
        - --git-user=foobar
        - --git-email=foobar@users.noreply.github.com
        - --sync-state=git
        - --manifest-generation=true
        - --listen-metrics=:3031
        - --git-ci-skip=true
        - "--git-ci-skip-message=[ci skip]"
        - --git-poll-interval=1m
```

**Expected behavior**

No such error log

**Logs**

```
mpatible/tools/cache/reflector.go:94: Failed to watch *v1beta1.CustomResourceDefinition: unknown (get customresourcedefinitions.apiextensions.k8s.io)"
ts=2020-01-08T09:52:05.945466074Z caller=main.go:267 type="internal kubernetes error" kubernetes_caller=k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:270 err="pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to watch *v1beta1.CustomResourceDefinition: unknown (get customresourcedefinitions.apiextensions.k8s.io)"
ts=2020-01-08T09:52:07.025017265Z caller=main.go:267 type="internal kubernetes error" kubernetes_caller=k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:270 err="pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to watch *v1beta1.CustomResourceDefinition: unknown (get customresourcedefinitions.apiextensions.k8s.io)"
ts=2020-01-08T09:52:08.094997447Z caller=main.go:267 type="internal kubernetes error" kubernetes_caller=k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:270 err="pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to watch *v1beta1.CustomResourceDefinition: unknown (get customresourcedefinitions.apiextensions.k8s.io)"
ts=2020-01-08T09:52:09.170984587Z caller=main.go:267 type="internal kubernetes error" kubernetes_caller=k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:270 err="pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to watch *v1beta1.CustomResourceDefinition: unknown (get customresourcedefinitions.apiextensions.k8s.io)"

```

**Additional context**

- Flux version:  1.17.0
- Helm Operator version:  We are not using Helm / Helm Operator
- Kubernetes version: Eks 1.14.7
- Git provider: github
- Container registry provider: ECR
