### ISSUE TITLE
Unable to list a docker repository if we have a empty string tag

### ISSUE THREAD

**Issue by gaieges** [fluxcd/flux#2735]
**Describe the bug**
A docker image repository that contains an empty tag (ie `my.repo.com/app:`) will fail to sync with the image repository with the following messages:

```
ts=2020-01-10T19:57:01.113606079Z caller=images.go:159 component=daemon err="fetching image metadata for repo.azurecr.io/app: empty tag in fetched tags"
ts=2020-01-10T20:03:48.084791767Z caller=warming.go:188 component=warmer err="empty tag in fetched tags" tags="unsupported value type"
```

**To Reproduce**
Steps to reproduce the behaviour:
0. What's your setup?
Azure container registry.  Unsure as to how a image such as `my.repo.com/app:` ever got set but .. here we are.

```
flux                 	4       	Thu Jan  9 18:35:07 2020	DEPLOYED	flux-1.0.0                 	1.17.0     	flux
helm-operator        	1       	Thu Jan  9 17:10:40 2020	DEPLOYED	helm-operator-0.4.0        	1.0.0-rc6  	flux
```

1. Push image named as such to your repository: `my.repo.com/app:`
1. Setup `HelmRelease` like below
```yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: myapp
  namespace: prod
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/app: "glob:master-*"

    tag.fluxcd.io/app: image.tag
    repository.fluxcd.io/app: image.repository

spec:
  releaseName: app-prod
  targetNamespace: prod
  timeout: 300
  resetValues: true
  forceUpgrade: false

  chart:
    git: git@github.com:myorg/app.git
    path: charts/app
    ref: master

  values:
    image:
      repository: my.repo.com/app
      tag: latest
```

1. Look at logs and see messages pasted above.

**Expected behavior**
Image get updated on git commit 

**Logs**

Relevant ones pasted above

**Additional context**
Add any other context about the problem here, e.g 
- Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-11-13T23:50:10Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T16:51:36Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
- Git provider: github
- Container registry provider: Azure Container Registry
