### ISSUE TITLE
Support Git repository authentication using BankVault

### ISSUE THREAD

**Issue by tomerleib** [fluxcd/flux#2737]
**Describe the feature**
In my organization, we're not storing sensitive tokens inside K8s secrets but instead using Vault for storing it and inject the secret directly into the pod.

**What would the new user story look like?**
Users who already runs Bank Vaults (or Vault) would like to pass the tokens as the environment variables.
For example this project: https://banzaicloud.com/blog/inject-secrets-into-pods-vault-revisited/

This solution is tested and working with other projects such as cert-manager and externalDNS.
**Expected behavior**
Assuming users have an existing Vault server running, they will provide the following changes in the deployment:
```yaml
...
annotations:
    vault.security.banzaicloud.io/vault-addr: "https://vault.infra:8200"
    vault.security.banzaicloud.io/vault-tls-secret: vault-tls
    vault.security.banzaicloud.io/vault-role: "default"
...
extraEnvs:
  - name: GIT_AUTHUSER
    value: "vault:secret/data/accounts/flux#GIT_AUTHUSER"
  - name: GIT_AUTHKEY
    value: "vault:secret/data/accounts/flux#GIT_AUTHUSER"
...
```
Those annotations will use Kubernetes Auth into Vault and will store the values as environment variables which later will be used by `git.url` instead of storing the token inside K8s Secret.

**Current behavior**
I've tested this implementation and those are my results so far:

1. When the `extraEnvs` are set as above and git.url is configured with `$(GIT_AUTHUSER):$(GIT_AUTHKEY)` - it results with the following url in the logs: `url=https://$GIT_AUTHUSER@github.com/myrepo/flux-test.git` and the following error: 
```
Authentication failed for 'https://github.com/myrepo/flux-test.git/', full output:\n Cloning into bare repository '/tmp/flux-gitclone898767176'...\nremote: Invalid username or password.\nfatal: Authentication failed for 'https://github.com/myrepo/flux-test.git/'\n" 
```

2. When the `extraEnvs` are set as above and git.url is configured with `$GIT_AUTHUSER:$GIT_AUTHKEY` - it results with the following url  ```url=ssh://@https//$%28GIT_AUTHUSER%29:$%28GIT_AUTHKEY%29@github.com:myrepo/temp-charts.git``` 
and the following error:
```
err="git repo not ready: git clone --mirror: fatal: unable to access 'https://github.com:myrepo/temp-charts.git/': URL using bad/illegal format or missing URL
```
