### ISSUE TITLE
Manifest generation with Kustomize causes updates to timeout when including remote resources

### ISSUE THREAD

**Issue by rdubya16** [fluxcd/flux#2801]
**Describe the feature**
Ability to use flux automated releases with kustomize manifests that contain kustomization.yamls that apply to multiple deployments. 

**What would the new user story look like?**
Say you have kustomize manifest that looks like the following. The image directive overrides the image used on all the listed deploy resources with one change.

```
resources:
- deploy1.yaml
- deploy2.yaml 
...
- deploy50.yaml

images:
- name: example.com/image
  newTag: release-1.0 
```

Currently with flux their is no way to automate these deploys without some nasty hack. The patching process would only need to make one update in this case to effect all the deploys listed. I tried using custom commandUpdated in flux.yaml but ran into issues due to the number of deploys that need to be iterated through and run with kustomize build . (took well over 10 mins to complete due to using remote repos in our kustomize builds)

I also tried only automating one of the deployments but flux would detect that unexpected deployment images changed and disallow the patching. A workaround for this issue might be allow for the disabling of the validation that blocks this.

```
version: 1
commandUpdated:
  generators:
   - command: kustomize build .
  updaters:
  - containerImage:
      command: kustomize edit set image example.com/image=$FLUX_IMG:$FLUX_TAG
```

**Expected behavior**
I would expect to be able to use flux automate with dry'd up kustomize manifests
