### ISSUE TITLE
tag filter annotation globbing implementation

### ISSUE THREAD

**Issue by daveoy** [fluxcd/flux#2867]
hi friends,

im hoping you can help me confirm this, but does the globbing implementation used by the tag annotation only implement the wildcard ('*') and none of the rest of the standard globbing conventions?

im trying to use a glob like so:

```yaml
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: videorouter
  namespace: flux
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.frontend: glob:frontend-[!ci]*
    fluxcd.io/tag.backend: glob:backend-[!ci]*
    fluxcd.io/tag.cms: glob:cms-[!ci]*
spec:
  releaseName: videorouter
  targetNamespace: videorouter
  chart:
    git: git@git.themill.com:devops/mill-kubernetes.git
    path: videorouter
    ref: charts
  values:
    frontend:
      image: docker.themill.com/videorouter:frontend-5aef4c37
    backend:
      image: docker.themill.com/videorouter:backend-5aef4c37
    cms:
      image: docker.themill.com/videorouter:cms-5aef4c37
  valuesFrom:
  - chartFileRef:
      path: values.chi2.yaml
```
to ignore intermediate ci containers that use a similar tag format, but as far as i can tell flux is interpreting the square brackets and exclamation point as literals, since the images im trying to target are also being ignored:
```
[(⎈ |chi2:flux) davey@mb587 ~] $ fluxctl list-images -w flux:helmrelease/videorouter
WORKLOAD                      CONTAINER  IMAGE                           CREATED
flux:helmrelease/videorouter  backend    docker.themill.com/videorouter
                                         |   backend-2a4eb51f            21 Feb 20 16:57 UTC
                                         |   backend-ci-2a4eb51f         21 Feb 20 16:57 UTC
                                         |   frontend-2a4eb51f           21 Feb 20 16:56 UTC
                                         |   frontend-ci-2a4eb51f        21 Feb 20 16:56 UTC
                                         |   cms-2a4eb51f                21 Feb 20 16:56 UTC
                                         |   cms-ci-2a4eb51f             21 Feb 20 16:56 UTC
                                         |   backend-ci-61bfc235         21 Feb 20 16:52 UTC
                                         |   cms-ci-61bfc235             21 Feb 20 16:52 UTC
                                         |   frontend-ci-61bfc235        21 Feb 20 16:52 UTC
                                         |   backend-ci-e25f015f         21 Feb 20 16:13 UTC
                                         : (8 image(s) omitted)
                                         '-> backend-5aef4c37            21 Feb 20 15:54 UTC
                              cms        docker.themill.com/videorouter
                                         |   backend-2a4eb51f            21 Feb 20 16:57 UTC
                                         |   backend-ci-2a4eb51f         21 Feb 20 16:57 UTC
                                         |   frontend-2a4eb51f           21 Feb 20 16:56 UTC
                                         |   frontend-ci-2a4eb51f        21 Feb 20 16:56 UTC
                                         |   cms-2a4eb51f                21 Feb 20 16:56 UTC
                                         |   cms-ci-2a4eb51f             21 Feb 20 16:56 UTC
                                         |   backend-ci-61bfc235         21 Feb 20 16:52 UTC
                                         |   cms-ci-61bfc235             21 Feb 20 16:52 UTC
                                         |   frontend-ci-61bfc235        21 Feb 20 16:52 UTC
                                         |   backend-ci-e25f015f         21 Feb 20 16:13 UTC
                                         : (10 image(s) omitted)
                                         '-> cms-5aef4c37                21 Feb 20 15:54 UTC
                              frontend   docker.themill.com/videorouter
                                         |   backend-2a4eb51f            21 Feb 20 16:57 UTC
                                         |   backend-ci-2a4eb51f         21 Feb 20 16:57 UTC
                                         |   frontend-2a4eb51f           21 Feb 20 16:56 UTC
                                         |   frontend-ci-2a4eb51f        21 Feb 20 16:56 UTC
                                         |   cms-2a4eb51f                21 Feb 20 16:56 UTC
                                         |   cms-ci-2a4eb51f             21 Feb 20 16:56 UTC
                                         |   backend-ci-61bfc235         21 Feb 20 16:52 UTC
                                         |   cms-ci-61bfc235             21 Feb 20 16:52 UTC
                                         |   frontend-ci-61bfc235        21 Feb 20 16:52 UTC
                                         |   backend-ci-e25f015f         21 Feb 20 16:13 UTC
                                         : (12 image(s) omitted)
                                         '-> frontend-5aef4c37           21 Feb 20 15:54 UTC
```
here i would expect flux to pick up `backend-2a4eb51f`,`frontend-2a4eb51f` and `cms-2a4eb51f` according to the annotations i've given the helmrelease. instead what i've got is the initial containers set in the helmrelease still being applied.

is this what you would also expect?
