### ISSUE TITLE
[helm-operator] Changes to helm chart not being detected

### ISSUE THREAD

**Issue by rally25rs** [fluxcd/flux#2932]
**Describe the bug**

After a failed helm release, helm-operator seems to have difficulty identifying changes to the chart.

**To Reproduce**

I made a commit that had some helm chart changes, but also included an error that prevented the helm release from passing.

Specifically, inside an existing `Deployment` I 

* Edited `spec.template.spec.containers[0].volumeMounts`
* Edited `spec.template.spec.volumes`
* Added `spec.template.spec.containers[0].metadata`

It looks like like `spec.template.spec.containers[0].metadata` was misplaced, that is not a valid attribute, which resulted in the helm release error

```
status:
  conditions:
  - lastTransitionTime: "2020-03-23T15:01:30Z"
    lastUpdateTime: "2020-03-23T15:09:58Z"
    message: 'failed to upgrade chart for release [qa]: error validating "": error
      validating data: ValidationError(Deployment.spec.template.spec.containers[0]):
      unknown field "metadata" in io.k8s.api.core.v1.Container'
    reason: HelmUpgradeFailed
    status: "False"
    type: Released
```

I then added a new commit that deleted the offending `spec.template.spec.containers[0].metadata` and moved it to `spec.template.metadata`

![image](https://user-images.githubusercontent.com/38535/77345523-1efa2800-6d0b-11ea-920f-25a02aea5fc5.png)

This resulted in `helm-operator` reporting:

```
ts=2020-03-23T15:42:58.393469753Z caller=release.go:404 component=release release=qa targetNamespace=qa resource=qa:helmrelease/qa helmVersion=v3 info="no changes" action=skip
```

The changes I had made to `volumes` and `volumeMounts` was never deployed, nor was the updated `metadata`.

**Expected behavior**

I expect helm-operator to detect that there are several changes to the chart compared to wat was last successful deployed, and make a deployment.

**Logs**

(log snippets above)

**Additional context**

- helm-operator version: `fluxcd/helm-operator:1.0.0-rc9`
- Kubernetes version: AWS EKS 🤷‍♂ 
- Git provider: github
- Container registry provider: github
