### ISSUE TITLE
Ability to pass body and headers in externalSourceRef

### ISSUE THREAD

**Issue by avielb** [fluxcd/flux#2947]
**Describe the feature**
Hey, 
I have a use-case where I use externalSourceRef, to get values.yaml from remote location. 
what is really missing for me is the ability pass authentication / context within the request. 

**What would the new user story look like?**
```
valuesFrom:
  - externalSourceRef:
      url: https://example.com/static/raw/values.yaml 
      body: | 
        { "a": "b"}
      header: 
        - "Authorization: Bearer my_token"
        - "X-App-Token: a1b2c3d4"
      optional: true
```   
1. What are the prerequisites for this?
None, can be optional
