### ISSUE TITLE
Sync with Kubernetes fails with Got empty response for: external.metrics.k8s.io/v1beta1

### ISSUE THREAD

**Issue by mycrEEpy** [fluxcd/flux#2965]
**Describe the bug**

When committing manifests to git flux can't deploy them to Kubernetes.
The sync seems to fail when running kubectl apply, but the error is empty.

**To Reproduce**

Steps to reproduce the behaviour:

1. Provide Flux install instructions
```sh
fluxctl install \
--git-branch=master \
--git-user=Flux \
--git-email=test@test.com \
--git-url=git@some-gitlab-instance.com:some/repo/flux.git \
--git-path=workloads \
--namespace=flux
```

2. Provide a GitHub repository with Kubernetes manifests
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: dev
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.16.0
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 10m
            memory: 32M
          limits:
            cpu: 100m
            memory: 32M
```

**Expected behavior**

Manifests should be successfully synced with Kubernetes.

**Logs**

```
ts=2020-04-02T18:56:45.814605174Z caller=loop.go:133 component=sync-loop event=refreshed url=ssh://git@some-gitlab-instance.com/some/repo/flux.git branch=master HEAD=133eb3b947d51b526ad46eccb400311769176524                                                                               
ts=2020-04-02T18:56:45.824652148Z caller=sync.go:73 component=daemon info="trying to sync git changes to the cluster" old=133eb3b947d51b526ad46eccb400311769176524 new=133eb3b947d51b526ad46eccb400311769176524                                                                                                  
ts=2020-04-02T18:56:45.899487567Z caller=main.go:276 type="internal kubernetes error" kubernetes_caller=k8s.io/client-go@v0.17.4/discovery/cached/memory/memcache.go:199 err="couldn't get resource list for external.metrics.k8s.io/v1beta1: Got empty response for: external.metrics.k8s.io/v1beta1"            
ts=2020-04-02T18:56:48.161673523Z caller=sync.go:539 method=Sync cmd=apply args= count=1                                                              
ts=2020-04-02T18:56:50.197903203Z caller=sync.go:605 method=Sync cmd="kubectl apply -f -" took=2.036176074s err="running kubectl: " output=           
ts=2020-04-02T18:56:52.089516554Z caller=sync.go:605 method=Sync cmd="kubectl apply -f -" took=1.891538188s err="running kubectl: " output=           
ts=2020-04-02T18:56:52.440129934Z caller=sync.go:167 component=daemon err="dev:deployment/nginx-deployment: running kubectl: "                 
ts=2020-04-02T18:56:55.085696454Z caller=loop.go:226 component=sync-loop state="tag flux" old=133eb3b947d51b526ad46eccb400311769176524 new=133eb3b947d51b526ad46eccb400311769176524                                                                                                                               
ts=2020-04-02T18:56:55.496348617Z caller=loop.go:133 component=sync-loop event=refreshed url=ssh://git@some-gitlab-instance.com/some/repo/flux.git branch=master HEAD=133eb3b947d51b526ad46eccb400311769176524
```                                                                      

**Additional context**

- Flux version: 1.18.0 & 1.19.0
- Kubernetes version: v1.15.10-eks-bac369
- Git provider: Gitlab
- Container registry provider: Docker Hub
