### ISSUE TITLE
automated mode enabled only for particular container in a pod

### ISSUE THREAD

**Issue by r0bj** [fluxcd/flux#2976]
**Describe the feature**
My deployment consists of two containers: `myapp` and `jaeger-agent`. I would like to enable fluxcd automated mode only for `myapp` container (which I control), not for `jaeger-agent` (which is an external tool).
Example deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
  annotations:
    fluxcd.io/automated: "true"
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: myapp:1.2.0
        ports:
        - containerPort: 8080
      - name: jaeger-agent
        image: jaegertracing/jaeger-agent:1.17.1
        command:
        - /go/bin/agent-linux
        - --reporter.grpc.host-port=jaeger-collector:14250
        ports:
        - containerPort: 6831
          protocol: UDP
```

From my experience, in practice, deployments consists of application container and multiple sidecar containers (jaeger-agent, prometheus-exporter, service-mesh, logs shipper, etc.). So in this case it would make sense if automated mode is enabled only for application container, not all containers in the deployment.

Is that currently possible with fluxcd?
