### ISSUE TITLE
Garbage collection of CronJob resources

### ISSUE THREAD

**Issue by groodt** [fluxcd/flux#2983]
**Describe the bug**

It appears that garbage collection of CronJob resources is not working.

We have a Flux setup with `--sync-garbage-collection=true`. It works on our cluster and we have examples of ConfigMap, StatefulSets, RoleBindings being garbage-collected.

However, CronJob resources are not being cleaned-up.

Any ideas?

**To Reproduce**

1. Commit a new CronJob to git
2. Allow flux to sync and create the CronJob on the cluster
3. Check CronJob created on the cluster
4. Remove newly created CronJob from git
5. Allow flux to sync
6. Check CronJob still exists on the cluster

**Expected behavior**

CronJob should be removed

**Additional context**

- Flux version: 1.18.0
- Kubernetes version: 1.15.0

**Comment by groodt** [comment]
Reference CronJob if it's helpful.

```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  annotations: {}
  labels:
    name: delete-me
  name: delete-me
  namespace: default
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 20
  jobTemplate:
    spec:
      completions: 1
      parallelism: 1
      template:
        metadata:
          labels:
            name: delete-me
        spec:
          containers:
          - args: []
            command:
            - date
            env: []
            image: alpine:3.11
            imagePullPolicy: IfNotPresent
            name: date
            ports: []
            stdin: false
            tty: false
            volumeMounts: []
          imagePullSecrets: []
          initContainers: []
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 30
          volumes: []
  schedule: 0 * * * *
  successfulJobsHistoryLimit: 10
```
