### ISSUE TITLE
Patch file does not support multiple updates

### ISSUE THREAD

**Issue by runningman84** [fluxcd/flux#3003]
**Describe the bug**

It looks like there is a configuration issue or a flux bug. Once flux finds two new docker images for different releases it uses the same file and commits alternating changes for both updates to the same file instead of adding a new block.

**To Reproduce**

Steps to reproduce the behaviour:

1. Setup two helm releases for automatic updates
2. Wait until both releases get new docker image releases

My .flux file looks like this
```
version: 1
patchUpdated:
  generators:
    - command: kustomize build .
  patchFile: flux-patch.yaml
```

my helm value file for the flux installation looks like this:
```
additionalArgs:
- --manifest-generation=true
git:
  url: git@github.com:runningman84/flux-repo-home.git
  branch: 'verified-deployment'
  path: patches/prod
  pollInterval: "30m"
rbac:
  create: true
helmOperator:
  create: true
  createCRD: false
prometheus:
  enabled: true
  serviceMonitor:
    create: true
registry:
  automationInterval: "60m"
  excludeImage: index.docker.io/jacobalberty/unifi,index.docker.io/metallb/*
sync:
  interval: "60m"
```

**Expected behavior**

Flux should add both updates to the flux-patch file and split them using ---

**Logs**

![image](https://user-images.githubusercontent.com/1699128/79269461-c696f000-7e9c-11ea-9173-59d617ec9a9d.png)

If applicable, please provide logs of `fluxd`. In a standard stand-alone installation of Flux, you'd get this by running `kubectl logs deploy/flux  -n flux`.

**Additional context**

- Flux version:  1.19 
- Helm Op version: 1.0
- Kubernetes version: 1.17
- Git provider: github
- Container registry provider: docker hub
