### ISSUE TITLE
./.flux.yaml: manifest not found error when enabling automated image update

### ISSUE THREAD

**Issue by ghfalcon7** [fluxcd/flux#3027]
I'm trying to enable automated container image update but I'm encountering this error:

err="applying changes: updating resource teamtool-install-be:deployment/teamtool-install-be in ./.flux.yaml: manifest not found"

Target git repo structure:
```
.
├── app_files
├──.flux.yaml
├── kustomization.yaml
└── teamtool-install-be.yaml

```
contents of .flux.yaml:
```
version: 1
patchUpdated:
  generators:
  - command: kustomize build .
  patchFile: flux-patch.yaml
```
contents of teamtool-install-be.yaml:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamtool-install-be
  annotations:
    fluxcd.io/automated: "true"
  labels:
    app: teamtool-install-be
```

The error message is making no sense to me, I would really appreciate some help in understanding what is the issue here. Thx!

**Additional context**

- Flux version: 1.18.0
- Kubernetes version: 1.15
- Git provider: GitHub
- Container registry provider: ECR
