### ISSUE TITLE
Flux does not garbage collect cronjobs

### ISSUE THREAD

**Issue by sam-jay** [fluxcd/flux#3048]
**Describe the bug**

Flux does not garbage collect CronJob workloads. `syncGarbageCollection.enabled` is set to `true` and works for other resources.

**To Reproduce**

Steps to reproduce the behaviour:

1. Commit a CronJob to a repo watched by Flux:
```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: slack-hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: slack-hello
            image: technosophos/slack-notify
            env:
            - name: SLACK_WEBHOOK
              value: "<SLACK_WEBHOOK>"
            - name: SLACK_MESSAGE
              value: "Hello everyone!"
          restartPolicy: OnFailure
```
2. Wait for Flux to detect and create the CronJob workload
3. Delete the CronJob resource from the repo
4. Wait 5+minutes for the next Flux sync

**Expected behavior**

I expected the CronJob resource to get removed, but it did not get removed.

**Logs**

```
ts=2020-05-08T01:06:48.224458644Z caller=images.go:17 component=sync-loop msg="polling for new images for automated workloads"
ts=2020-05-08T01:08:13.456507138Z caller=loop.go:133 component=sync-loop event=refreshed url=https://XXXXXXX.git branch=XXXXXXX HEAD=a4231b75e7e728dd8752ed5735cf048dd6190494
ts=2020-05-08T01:08:13.469572163Z caller=sync.go:73 component=daemon info="trying to sync git changes to the cluster" old=f26d63081f0e9f178336076f01b0bdaf506878b3 new=a4231b75e7e728dd8752ed5735cf048dd6190494
ts=2020-05-08T01:08:13.748443483Z caller=sync.go:539 method=Sync cmd=apply args= count=7
ts=2020-05-08T01:08:13.963777974Z caller=sync.go:605 method=Sync cmd="kubectl apply -f -" took=215.286569ms err=null output="namespace/demo unchanged\nnamespace/monitoring unchanged\nservice/podinfo unchanged\nsecret/redis-auth unchanged\ndeployment.apps/podinfo configured\nhorizontalpodautoscaler.autoscaling/podinfo unchanged\nhelmrelease.helm.fluxcd.io/redis unchanged"
ts=2020-05-08T01:08:14.128298337Z caller=daemon.go:701 component=daemon event="Sync: a4231b7, no workloads changed" logupstream=false
ts=2020-05-08T01:08:17.659785297Z caller=loop.go:226 component=sync-loop state="tag flux-sync" old=f26d63081f0e9f178336076f01b0bdaf506878b3 new=a4231b75e7e728dd8752ed5735cf048dd6190494
ts=2020-05-08T01:08:18.118016005Z caller=loop.go:133 component=sync-loop event=refreshed url=https://XXXXXXX.git branch=XXXXXXX HEAD=a4231b75e7e728dd8752ed5735cf048dd6190494
```

**Additional context**

- Flux version: flux-1.3.0
- Kubernetes version: v1.16.8-eks-e16311
- Git provider: Github
- Container registry provider: Docker hub
