### ISSUE TITLE
RunAsNonRoot issues

### ISSUE THREAD

**Issue by carlpett** [fluxcd/flux#3097]
**Describe the bug**
I'm trying to get flux to run as non-root (for compliance reasons), and thought I'd detail current steps required, and where it doesn't work.

**To Reproduce**
On the flux Deployment, set `.spec.template.spec.securityContext.runAsNonRoot: true`.

- The Dockerfile doesn't have a `USER`, so we need to also set `securityContext.RunAsUser`. The uid chosen needs to exist in /etc/passwd, otherwise git complains. We've set it to `65534`, which is the `nobody` user.
- The git key secret volume mount only has root permissions by default, so we need to also set `securityContext.fsGroup` so Kubernetes adjusts the permissions. We use `65534` here too, the `nobody` group.
- Flux will try to read the cluster connection config from `$HOME/.kube/config`, but there isn't one for our user (the image has created one in /root/, but that we naturally don't have access to). We could create one, but it also works if the kubeconfig setting is set to empty string, so we pass `--kube-config=`. This is deprecated in favour of using the `KUBECONFIG` environment variable, but apparently envs cannot be set to an empty string (this is odd, but I at least couldn't get it to work, and Kubernetes removed the `value: ""` from my `env` block when I tried).

After these steps, we are now stuck on flux trying to chmod the key to 0400, but failing for lack of permissions. 

At this point, the manifest looks like this:
<details><summary><i>Expand</i></summary>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux
  labels:
    app: flux
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: flux
  template:
    metadata:
      labels:
        app: flux
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
      serviceAccountName: flux
      automountServiceAccountToken: true
      containers:
      - name: flux
        image: docker.io/fluxcd/flux:1.19.0
        imagePullPolicy: IfNotPresent
        args:
        - --log-format=json
        - --k8s-secret-name=flux-git-deploy
        - --registry-disable-scanning

        - --sync-interval=5m
        - --sync-garbage-collection-dry

        - --git-url=ssh://git@github.com/our-org/our-repo
        - --git-branch=master
        - --git-path=target
        - --git-readonly=true
        - --git-poll-interval=5m
        - --kube-config=
        ports:
        - name: http
          containerPort: 3030
          protocol: TCP
        livenessProbe:
          httpGet:
            port: 3030
            path: /api/flux/v6/identity.pub
          initialDelaySeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            port: 3030
            path: /api/flux/v6/identity.pub
          initialDelaySeconds: 5
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
        volumeMounts:
        - name: git-key
          mountPath: /etc/fluxd/ssh
          readOnly: true

      volumes:
      - name: git-key
        secret:
          secretName: flux-git-deploy
          defaultMode: 0400
```

</details>

**Expected behavior**
It should be reasonably simple to not run as root.

**Logs**
```
Flag --kube-config has been deprecated, please use the KUBECONFIG environment variable instead
{"caller":"main.go:259","ts":"2020-06-01T09:02:58.033175114Z","version":"1.19.0"}
{"caller":"main.go:284","ts":"2020-06-01T09:02:58.033544761Z","warning":"--git-readonly prevents use of --sync-state=git. Forcing to --sync-state=secret"}
{"caller":"main.go:358","info":"SSH keygen dir (--ssh-keygen-dir) not provided, so using the deploy key volume (--k8s-secret-volume-mount-path=/etc/fluxd/ssh); this may cause problems if the deploy key volume is mounted read-only","ts":"2020-06-01T09:02:58.033782203Z"}
{"caller":"main.go:485","err":"failed to chmod identity file: chmod /etc/fluxd/ssh/identity: read-only file system","ts":"2020-06-01T09:02:58.042310632Z"}
```

**Additional context**

- Flux version: 1.19.0
- Kubernetes version: v1.16.8-gke.15
- Git provider: Github
- Container registry provider: Docker Hub

**Comment by carlpett** [comment]
I've hacked around the permission issue with an init container and an extra emptyDir volume:
```yaml
      initContainers:
      - name: ssh-key-permission-fix
        command:
        - /bin/sh
        - -c
        - |
          cp /input/identity /output/identity
          chmod 400 /output/identity
        image: busybox
        volumeMounts:
        - mountPath: /input
          name: git-key-secret
          readOnly: true
        - mountPath: /output
          name: git-key-ephemeral
```

So now fluxd starts and runs as `nobody`.
