### ISSUE TITLE
Redis Chart not found - Helm release

### ISSUE THREAD

**Issue by nikhilbalekundargi** [fluxcd/flux#3122]
**Describe the bug**

We are tying to deploy Redis out application using Helm Operator of Flux. Redis not deployed to cluster.

Steps to reproduce the behaviour:

Helm Release Yaml -
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
name: redis
namespace: redis
annotations:
fluxcd.io/automated: "true"
fluxcd.io/locked: "true"
spec:
releaseName: redis
chart:
repository: https://charts.bitnami.com/bitnami
name: bitnami/redis
usePassword: true
service:
type: ClusterIP
port: 6379
cluster:
enabled: true

**Expected behavior**

Redis should be deployed.

**Logs**

Helm Operator Logs -
ts=2020-06-09T14:06:21.839631193Z caller=release.go:75 component=release release=redis targetNamespace=redis resource=redis:helmrelease/redis helmVersion=v3 info="starting sync run"
ts=2020-06-09T14:06:21.847528763Z caller=release.go:81 component=release release=redis targetNamespace=redis resource=redis:helmrelease/redis helmVersion=v3 error="failed to prepare chart for release: could not find valid chart source configuration for release"

**Additional context**

GKE Cluster

- Flux version: 
version.BuildInfo{Version:"v3.2.2", GitCommit:"a6ea66349ae3015618da4f547677a14b9ecc09b3", GitTreeState:"clean", GoVersion:"go1.13.12"}

- Kubernetes version:
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.36", GitCommit:"34a615f32e9a0c9e97cdb9f749adb392758349a6", GitTreeState:"clean", BuildDate:"2020-04-06T16:33:17Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}

- Git provider: Github

- Container registry provider: NA

**Comment by nikhilbalekundargi** [comment]
Also tried with below yaml config but no luck.

```yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: redis
  namespace: redis
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/locked: "true"
spec:
  releaseName: redis
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: bitnami/redis
  values:
    usePassword: true
    master:
      service:
        type: ClusterIP
        port: 6379
    cluster:
      enabled: true
```
