### ISSUE TITLE
err="running kubectl: error: unable to recognize \"STDIN\": an error on the server (\"\") has prevented the request from succeeding"

### ISSUE THREAD

**Issue by michael-niemand** [fluxcd/flux#3126]
**Bug description**

Followed the tutorial for installing Flux. Installed using fluxctl on AKS. After pushing the first workload (2 namespaces in the namespaces folder, 1 service and a hello world app with 3 replicas in the workloads folder), I get the error
`err="running kubectl: error: unable to recognize \"STDIN\": an error on the server (\"\") has prevented the request from succeeding"`
Nothing from the repo is being deployed.

**edit: Something interesting I found out trying to debug:
I deployed a simple `kubectl version` job using the bitnami/kubectl:latest image with the same ServiceAccount and same namespace as flux. works just fine. However, if I change the image to 1.15.3 (flux has kubectl 1.15.9) it throws the same error as the flux container** which leads me to believe that this is an issue with kubectl, that will be fixed in a new release - I already saw that the master branch already contains an newer kubectl version (1.17)

**To Reproduce**

Steps to reproduce the behaviour:

1. Installed flux using `fluxctl install --git-user=${GHUSER} --git-email=my-email@mailprovider.com --git-url=ssh://git@bitbucket.some-private-server.com:7999/infra/k8s-gitops.git --git-path=namespaces,workloads --namespace=flux | kubectl apply -f -` on AKS k8s version 1.16.9 (latest non preview version at the time of writing)
2. succcessfully established connection to private git (bitbucket)
3. add namespaces and workloads to git like:

```
apiVersion: v1
kind: Namespace
metadata:
  name: dev
```

```
apiVersion: v1
kind: Namespace
metadata:
  name: prod
```

```
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: dev
  labels:
    app.kubernetes.io/instance: dev
    app.kubernetes.io/name: hello-world
    app.kubernetes.io/version: 1.0.0
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: dev
    app.kubernetes.io/name: hello-world
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: "hello-world"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello-world
    spec:
      containers:
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:1.7
        ports:
        - containerPort: 8080
```

**Expected behavior**

namespace and hello world app are being deployed

**Logs**

```
ts=2020-06-10T09:07:42.7589883Z caller=loop.go:133 component=sync-loop event=refreshed url=ssh://git@bitbucket.some-private-server.com:7999/infra/k8s-gitops.git branch=master HEAD=7bb83d1753a814c510b1583da6867408a5f7e21b
ts=2020-06-10T09:09:00.631764Z caller=sync.go:73 component=daemon info="trying to sync git changes to the cluster" old=7bb83d1753a814c510b1583da6867408a5f7e21b new=7bb83d1753a814c510b1583da6867408a5f7e21b
ts=2020-06-10T09:09:01.6130559Z caller=sync.go:539 method=Sync cmd=apply args= count=3
ts=2020-06-10T09:09:20.2097034Z caller=sync.go:605 method=Sync cmd="kubectl apply -f -" took=18.5965923s err="running kubectl: error: unable to recognize \"STDIN\": an error on the server (\"\") has prevented the request from succeeding" output=
ts=2020-06-10T09:09:38.7432182Z caller=sync.go:605 method=Sync cmd="kubectl apply -f -" took=18.5334244s err="running kubectl: error: unable to recognize \"STDIN\": an error on the server (\"\") has prevented the request from succeeding" output=
ts=2020-06-10T09:09:57.277918Z caller=sync.go:605 method=Sync cmd="kubectl apply -f -" took=18.5346491s err="running kubectl: error: unable to recognize \"STDIN\": an error on the server (\"\") has prevented the request from succeeding" output=
ts=2020-06-10T09:09:57.2779965Z caller=sync.go:167 component=daemon err="<cluster>:namespace/dev: running kubectl: error: unable to recognize \"STDIN\": an error on the server (\"\") has prevented the request from succeeding; <cluster>:namespace/prod: running kubectl: error: unable to recognize \"STDIN\": an error on the server (\"\") has prevented the request from succeeding; dev:service/hello-world: running kubectl: error: unable to recognize \"STDIN\": an error on the server (\"\") has prevented the request from succeeding"
ts=2020-06-10T09:09:57.2879489Z caller=images.go:17 component=sync-loop msg="polling for new images for automated workloads"
ts=2020-06-10T09:09:57.3002208Z caller=images.go:27 component=sync-loop msg="no automated workloads"
```

**Additional context**

- Flux version:
      fluxctl version returns "unversioned" - installed via snap on Linux using --edge flag
      fluxd 1.19.0
- Kubernetes version: 1.18.3 (client) 1.16.9 (server)
- Git provider: Bitbucket
- Container registry provider: public
