### ISSUE TITLE
Flux is not catching duplication for apiservice object types

### ISSUE THREAD

**Issue by antoniotamer** [fluxcd/flux#3135]
**Describe the bug**

`APIService` objects in k8s seems to accept `namespace`, but that appears to not have any effect on the actual apiservice definition. If there are 2 APIService named the same in my git repo but with different namespace, flux seems to be alternating between applying one or the other. I think for `APIService` object, flux should try to ignore namespace and identify the conflict/duplicate.

An example of that issue becoming a problem is if you install `metrics-server` and `kube-prometheus`. Both try to install an APIService named `v1beta1.metrics.k8s.io`, but each points to a different service/namespace (as a result of applying overlays). Flux does not detect the conflict, and so whenever flux sync loop runs, it seems that whichever manifest is applied last wins.

**To Reproduce**

Steps to reproduce the behaviour:

1. Install flux
2. Create 2 k8s services
3. In your flux repo, add an APIService manifest pointing to the first service. 
4. In your flux repo, add an APIService manifest pointing to the second service

eg for step3:

```
---
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.metrics
spec:
  service:
    name: metrics-server
    namespace: kube-system
  group: metrics
  version: v1alpha1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100
```

eg for step 4:

```
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.metrics.k8s.io
  namespace: monitoring
spec:
  group: metrics.k8s.io
  groupPriorityMinimum: 100
  insecureSkipTLSVerify: true
  service:
    name: prometheus-adapter
    namespace: monitoring
  version: v1beta1
  versionPriority: 100
```
5. Run `while true; do kubectl get apiservice | grep metrics; sleep 5; done`. After some time, you might see this output:

```
$ while true; do kubectl get apiservice | grep metrics; sleep 5; done
v1beta1.metrics.k8s.io                 monitoring/prometheus-adapter   True        108d
v1beta1.metrics.k8s.io                 monitoring/prometheus-adapter   True        108d
v1beta1.metrics.k8s.io                 monitoring/prometheus-adapter   True        108d
v1beta1.metrics.k8s.io                 monitoring/prometheus-adapter   True        108d
v1beta1.metrics.k8s.io                 monitoring/prometheus-adapter   True        108d
v1beta1.metrics.k8s.io                 monitoring/prometheus-adapter   True        108d
v1beta1.metrics.k8s.io                 kube-system/metrics-server   True        108d
v1beta1.metrics.k8s.io                 kube-system/metrics-server   True        108d
v1beta1.metrics.k8s.io                 kube-system/metrics-server   True        108d
v1beta1.metrics.k8s.io                 kube-system/metrics-server   True        108d
v1beta1.metrics.k8s.io                 monitoring/prometheus-adapter   True        108d
v1beta1.metrics.k8s.io                 monitoring/prometheus-adapter   True        108d
v1beta1.metrics.k8s.io                 monitoring/prometheus-adapter   True        108d
```

**Expected behavior**

I would expect flux to detect that 2 APIService objects exist in the graph and to treat them as duplicates, even if they have different namespaces - they are in effect going to modify the same object.  

**Logs**

Flux logs are all over the place, we'll see this for a few sync cycles:
```
v1beta1.metrics.k8s.io unchanged
```

followed by this:
```
v1beta1.metrics.k8s.io configured
```

In environments where flux manages hundreds of objects, it's very hard to tell that this is what's happening.

**Additional context**

- Flux version: 1.18.0
- Kubernetes version: 1.14
- Git provider: codecommit
- Container registry provider: dockerhub, ecr, quay.io, etc.
