### ISSUE TITLE
can't use flux with private gitlab repo

### ISSUE THREAD

**Issue by suppix** [fluxcd/flux#3150]
Can't make flux work with private gitlab registry. 
Can you please help me?

```
ts=2020-06-23T13:14:24.68162784Z caller=warming.go:180 component=warmer canonical_name=git.mydomain.com:4567/user/frontend/ui auth={map[]} err="requesting tags: Get https://git.domain.com:4567/v2/user/frontend/ui/tags/list: denied: access forbidden"
```

Although I can successfully do: 
`helm upgrade -i frontend frontend `

My frontend.yaml
```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: frontend
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
spec:
  chart:
    repository: ssh://git@git.domain.com:2222/deploy/stage.git
    name: frontend
    path: user/frontend
    version: 1.0.0
  values:
    image:
      repository: git.domain.com:4567/user/frontend/ui
      tag: 6c0279e030d7
      imagePullSecrets:
        - name: my-registry-secret
    replicaCount: 1
```

And helm chart values.yaml
```
image:
  repository: git.domain.com:4567/user/frontend/ui
  pullPolicy: "Always"
  tag: "latest"
  imagePullSecrets:
    - name: my-registry-secret
```
