### ISSUE TITLE
SyncGarbageCollection does not delete sealed secrets

### ISSUE THREAD

**Issue by pmorelli92** [fluxcd/flux#3157]
**Describe the bug**

When running flux with `syncGarbageCollection.enabled = true`, if you delete a sealed secret from the git repository, it will still exists on the cluster after sync happens.

**To Reproduce**

Steps to reproduce the behaviour:

Install Flux:

```
helm repo add fluxcd https://charts.fluxcd.io

helm install flux fluxcd/flux \
--set git.url='https://<user>:<password>@github.com/<user>/<repo>.git' \
--set git.pollInterval=2m \
--set git.branch=master \
--set syncGarbageCollection.enabled=true \
--namespace flux
```

Install sealed secrets operator:

```
helm repo add def https://kubernetes-charts.storage.googleapis.com

helm install sealed-secrets def/sealed-secrets --namespace flux
```

Get public key

```
kubeseal --fetch-cert \
--controller-namespace=flux \
--controller-name=sealed-secrets \
> pub-cert.pem
```

Create a secret

```
kubectl -n flux create secret generic secret-example \
--from-literal=myKey=12345 \
-o yaml > secret-example.yaml
```

Encrypt the secret:

```
kubeseal --format=yaml --cert=pub-cert.pem < secret-example.yaml > secret-example-enc.yaml
rm secret-example.yaml #Delete original secret
```

Commit and Push -> Secrets get created.

Remove: `rm secret-example-enc.yaml`
Commit and Push -> Secret does not get deleted after sync.

**Expected behavior**

Secret should have been deleted.

**Logs & Others**

If we check the sync code, the resources that are going to be deleted are expected to have the GC label:
https://github.com/fluxcd/flux/blob/master/pkg/cluster/kubernetes/sync.go#L362

```
gcMarkLabel = kresource.PolicyPrefix + "sync-gc-mark"
```

If I commit and push a deployment yaml file like this:

```
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: flux
  labels:
    app: busybox
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
```

When Flux deploys it I can do:

```
kubectl get pods -n flux -o yaml busybox
```

And I will see

```
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: busybox
    fluxcd.io/sync-gc-mark: sha256.XyV_TVWhn1l2NfBuvPunnwN4ooCDJUa60srbi_7LGRc
```

However, when I do the same for the secret deployed before:

```
kubectl get secrets -n flux secret-example -o yaml
```

I get

```
apiVersion: v1
data:
  myKey: MTIzNDU=
kind: Secret
metadata:
  creationTimestamp: "2020-06-25T10:03:45Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:myKey: {}
      f:type: {}
    manager: kubectl
    operation: Update
    time: "2020-06-25T10:03:45Z"
  name: secret-example
  namespace: demo
  resourceVersion: "3401"
  selfLink: /api/v1/namespaces/demo/secrets/secret-example
  uid: 4e705e35-5bce-48e5-ab65-41ff7826fae1
type: Opaque
```

Since it does not have the `fluxcd.io/sync-gc-mark` it is not deleted.

My question: Is this intended or is it a bug or something I am doing wrong?

**Additional context**

- Flux version: 1.19
- Kubernetes version:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-18T02:59:13Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Git provider: Github
- Container registry provider: Docker
