### ISSUE TITLE
Parsing .YAML files

### ISSUE THREAD

**Issue by FurentesT** [fluxcd/flux#3158]
Hello. 
I'm very new with flux. Trying to setup authomatic pulling of images from private repo on gitlab, but it looks like flux try to find some data by parsing all my .yml files and dives me same error in logs and when i try to run 
`fluxctl list-workloads`

The error is
`Flux was unable to parse the files in the git repo as manifests,
giving this error:
  parsing YAML doc from <filename>: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str input {... into resource.baseObject`

To Reproduce

Maybe it's a bad way to initiate all the stuff but as I say I'm very new with it and it's the best way that i found

1. Run kubes deployments.
Flux settings in deployment file:
`
```
apiVersion: v1
kind: Service
metadata:
  name: flux-expose-service
  labels: 
    app: flux
spec:
  type: NodePort
  ports:
  - port: 3031
    protocol: TCP
    nodePort: 30004
  selector:
    app: <myApp>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux
spec:
  replicas: 1
  selector:
    matchLabels:
      name: flux
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/port: "3031" # tell prometheus to scrape /metrics endpoint's port.
      labels:
        name: flux
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      serviceAccountName: flux
      volumes:
      - name: git-key
        secret:
          secretName: flux-git-deploy
          defaultMode: 0400 # when mounted read-only, we won't be able to chmod

      - name: git-keygen
        emptyDir:
          medium: Memory
      containers:
      - name: flux
        image: docker.io/fluxcd/flux:1.19.0
        env:
          - name: GITLAB_USER
            valueFrom:
              secretKeyRef:
                name: gitlab-secret
                key: user
          - name: GITLAB_PASS
            valueFrom:
              secretKeyRef:
                name: gitlab-secret
                key: pass
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
        ports:
        - containerPort: 3030 # informational
        livenessProbe:
          httpGet:
            port: 3030
            path: /api/flux/v6/identity.pub
          initialDelaySeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            port: 3030
            path: /api/flux/v6/identity.pub
          initialDelaySeconds: 5
          timeoutSeconds: 5
        volumeMounts:
        - name: git-key
          mountPath: /etc/fluxd/ssh
          readOnly: true
        - name: git-keygen
          mountPath: /var/fluxd/keygen # to match location given in image's /etc/ssh/config

        args:

        - --memcached-service=

        - --ssh-keygen-dir=/var/fluxd/keygen

        - --git-url=<my gitrep with HTTPS creds>
        - --git-branch=master

        - --git-label=flux-sync
        - --git-user=<my git login>
        - --git-email=<my e-mail>

        - --manifest-generation=true

        - --listen-metrics=:3031

        - --sync-timeout=100m0s 
````

2. Install flux services 
`fluxctl install --git-user=<git user> --git-email=<git pass> --git-url=<git repo https> | kubectl apply -f -`

3. `fluxctl sync` or `fluxctl list-workloads`

In root of my repo i have .flux.yaml and flux-patch.yml. flux-patch is empty.

```
# .flux.yaml
version: 1
patchUpdated:
    generators:
    - command: kustomize build .
    patchFile: flux-patch.yaml
```
