### ISSUE TITLE
Flux tries to access an insecure but trusted docker mirror, throws errors, and I have no idea why

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [fluxcd/flux#3174]
This is a really minor issue: it is non-breaking; everything works, actually. But I receive error messages in logs when everything is configured correctly (or seems to be correct).

**Describe the bug**
Given that we have a docker repo, that has an address `http://10.10.11.10:8181/`, and that it is present in the docker-daemon config on all master and worker nodes, and that we have an up to date, synced, working workload that uses an image `wordpress-ldap` from that repo, `flux` job writes this error message (with an interval of roughly 5min):

`ts=2020-07-06T21:39:02.730099733Z caller=warming.go:154 component=warmer canonical_name=10.10.11.10:8181/wordpress-ldap auth={map[]} err="Get https://10.10.11.10:8181/v2/: http: server gave HTTP response to HTTPS client"`

`sudo docker info` shows that the registry is trusted (we checked that on **each** node, including the master nodes):

```yaml
# irrelevant stuff was stripped out
 Kernel Version: 4.15.0-88-generic
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.792GiB
 Name: corecubeworker4
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
  provider=vmwarevsphere
 Experimental: false
 Insecure Registries:
  10.10.11.10:8181
  127.0.0.0/8
 Registry Mirrors:
  http://10.10.11.10:8181/
```

We can say for sure that the workload is running and up to date. It uses the correct image, and we made changes to flux resources after the first successful deployment with a custom image.

![изображение](https://user-images.githubusercontent.com/3174357/86650738-10741a00-c037-11ea-83fa-7d221ca7c12a.png)

```yaml
▶ helm status kammiac-site -n kammiac-site 
NAME: kammiac-site
LAST DEPLOYED: Mon Jul  6 02:03:19 2020
NAMESPACE: kammiac-site
STATUS: deployed
REVISION: 13
NOTES: doobedoo
```

So everything works perfectly, yet we still get errors in logs. Nothing else interesting is happening around these error messages.

**To Reproduce**

```yaml
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kammiac-site
  namespace: kammiac-site
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: kammiac-site
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: wordpress
    version: 9.1.3
  values:
    updateStragegy: Recreate
    image:
      registry: 10.10.11.10:8181
      repository: wordpress-ldap
      tag: latest
      # pullPolicy: Always
      debug: true
    wordpressScheme: https
    allowOverrideNone: true
    allowEmptyPassword: false
    customHTAccessCM: kammiac-site-config
    securityContext:
      enabled: true
  # most other fields were removed; they are irrelevant anyways
```

The chart was deployed a couple of months ago so this procedure is mainly pulled off our git repo history.

0. Start with a regular Kubernetes cluster without special configs. Get flux set up and configured.
1. Push a HelmRelease with a link to a secure image repository (bitnami/wordpress)
2. Change it so an image is downloaded from an insecure repo.
3. Change the template of worker and master nodes in Kubernetes cluster so that  `10.10.11.10:8181` is included in `Registry Mirrors` and `Insecure Registries`.
4. Gradually re-provision nodes so the changes in docker runtime are applied everywhere.
5. The deployment gets updated automatically. Everything is fine, yet the log of `flux` job still writes new errors:

`ts=2020-07-07T00:52:17.728798061Z caller=warming.go:154 component=warmer canonical_name=10.10.11.10:8181/wordpress-ldap auth={map[]} err="Get https://10.10.11.10:8181/v2/: http: server gave HTTP response to HTTPS client"`

**Expected behavior**

No errors in `flux` log ¯\_(ツ)_/¯

**Additional context**

- Flux version: fluxcd/flux:1.19.0
- Kubernetes version: v1.17.4
- Git provider: Gitlab (the public one)
- Container registry provider: Sonatype Nexus Repository Manager (OSS version) for Wordpress-ldap, Docker hub for everything else
