### ISSUE TITLE
Can't seem to get automation of HelmRelease working

### ISSUE THREAD

**Issue by michael-niemand** [fluxcd/flux#3187]
**Description**

I have a HelmRelease whose image is not being updated - neither automatically (while being annotated to be automated, see yaml below) nor when explicitly trying to update using fluxctl release like so:

`fluxctl release --update-image=our-aks-registry.azurecr.io/drupal/fk-product-drupal:develop-542 --workload product-dev:helmrelease/drupal-product-dev-helmrelease -f`

Flux says in the logs "no images to update for services given" and "no changes made in repo" (full logs below) even though:

- there is no filter active (I had one earlier but threw it out to make sure it's not the culprit)

- I applied the credentials for the ACR like mentioned here (mounting /etc/kubernetes/azure.json): https://docs.fluxcd.io/en/1.17.0/troubleshooting.html#why-are-my-images-not-showing-up-in-the-list-of-images

- `fluxctl list-images` returns all images, including the one passed to the release command, so Flux can obviously read from the registry (I copy-pasted the name from list-images to the release command to prevent typos)

- `fluxctl automate -w product-dev:helmrelease/drupal-product-dev-helmrelease -n product-dev`  returns 
```
product-dev:helmrelease/drupal-product-dev-helmrelease  
success  
Commit pushed:	1d95f97
```  
... so Flux can also write to git.

The released image always stays what's provided in the Chart.yaml of the chart this HelmChart resource refers to under appVersion (master-72 in that case) and never changes. Do I need to alter the Chart in any way maybe?

The HelmRelease looks like this:

```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    fluxcd.io/automated: "true"
    repository.fluxcd.io/chart-image: our-aks-registry.azurecr.io/drupal/fk-product-drupal
  name: drupal-product-dev-helmrelease
  namespace: product-dev
spec:
  chart:
    git: ssh://git@bitbucket.intra.company.com:7999/infra/helm-charts.git
    path: charts/product
    ref: master
  releaseName: drupal-product-dev
  values:
    image:
      drupal:
        repository: our-aks-registry.azurecr.io/drupal/fk-product-drupal
        tag: develop-540
      nginx:
        repository: our-aks-registry.azurecr.io/drupal/fk-product-nginx
        tag: develop-540
  valuesFrom:
  - chartFileRef:
      path: values-dev.yaml
```

The Chart.yaml looks like this:
```
apiVersion: v2
name: drupal-product
description: A Helm chart for Kubernetes to deploy multiple product instances
type: application
version: 0.1.1
appVersion: master-72
```

As you can see, even explicitly passing the tag in the HelmRelease spec does not lead to a deployment of said version (tag: develop-540, but master-72 as stated in the Chart.yaml stays deployed). I assume I'm making something wrong, but after 3 days of trying to debug, I'm at my wits end.

**Logs**

[kubectl logs -n flux deploy/flux](https://gist.github.com/michael-niemand/be66d10e7fede036999438b5526d153b)

**Additional context**

- Flux version: Using the latest 1.20 release
- Kubernetes version: 1.16.9 AKS
- Git provider: Bitbucket
- Container registry provider: AKS ACR

I guess my main question is: How does flux determine when to update the image since it can clearly see that there are newer images in the registry? 

edit: Here's the output of list-images, which indicates flux can read from the repo and the dates indicate that there are in fact newer images available:
[list-image.log](https://github.com/fluxcd/flux/files/4904613/list-image.log)

**Comment by ekristen** [comment]
I'm not an expert, but it appears you are using the annotations incorrectly.

I don't believe `repository.fluxcd.io/chart-image` is a valid annotation.

What you are looking for is telling flux that there are multiple images in play that might need to be automated. Try

```
repository.fluxcd.io/drupal: image.drupal.repository
tag.fluxcd.io/drupal: image.drupal.tag
repository.fluxcd.io/nginx: image.nginx.repository
tag.fluxcd.io/nginx: image.nginx.tag
```

**Comment by michael-niemand** [comment]
> I'm not an expert, but it appears you are using the annotations incorrectly.
> 
> I don't believe `repository.fluxcd.io/chart-image` is a valid annotation.
> 
Thank you for your reply!
I copied this from https://docs.fluxcd.io/en/1.20.0/references/helm-operator-integration/ but might have applied it wrong ...

> ```
> repository.fluxcd.io/drupal: image.drupal.repository
> tag.fluxcd.io/drupal: image.drupal.tag
> repository.fluxcd.io/nginx: image.nginx.repository
> tag.fluxcd.io/nginx: image.nginx.tag
> ```

... thus I changed my HelmRelease to your version, but the result is the same: No new image, same error message as above.

**Comment by michael-niemand** [comment]
Ok, so I got it working after reading Stefans comments in other issues. So for anybody a search engine leads here:

- make sure your annotations fit, that's the only thing that matters! You might refer to the values section in HelmChart from the annotations, but the values do not what matters for the update mechanism! Only the annotations matter to the update. For my example that means (pay attention especially to the repo and tag annotations):

```
  annotations:
    fluxcd.io/automated: "true" 
    repository.fluxcd.io/drupal: image.drupal.repository
    tag.fluxcd.io/drupal: appVersion 
    filter.fluxcd.io/drupal: "glob:develop-*"
    repository.fluxcd.io/nginx:  image.nginx.repository
    tag.fluxcd.io/nginx: appVersion
    filter.fluxcd.io/nginx: "glob:develop-*"

...

  values:
    appVersion: develop-540
    image:
      drupal:
        repository: akswebprodacr.azurecr.io/drupal/fk-fresubin-drupal
      nginx:
        repository: akswebprodacr.azurecr.io/drupal/fk-fresubin-nginx
```


**Oh and one more thing: I've found the registry annotation to not work - no matter what I put there, it always tried to append what I put in repository.fluxcd.io to the official docker registry URL. Just put your private registry URL in front of the repo string.**
