### ISSUE TITLE
invalid image ID error with nginx-controller chart 2.11.0

### ISSUE THREAD

**Issue by rust84** [fluxcd/flux#3189]
**FluxCD version**:
v1.20

**Kubernetes version** (use `kubectl version`):
v1.17.7

**Environment**:
k3s 

**What happened**:

When deploying the nginx-ingress controller helm chart 2.11.0 I noticed an error in the Flux logs. The release is deployed successfully however I see the error again with each sync.

`2020-07-12T17:20:25.474929454Z stderr F ts=2020-07-12T17:20:25.47466219Z caller=images.go:39 resource=kube-system:deployment/nginx-ingress-ext-ingress-nginx-controller err="expected image name as either <image>:<tag> or just <image>: invalid image ID"`

**What you expected to happen**:

Release deploys successfully with no errors.

**How to reproduce it**:

Create the following HelmRelease and observe the Flux logs.

```
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: kube-system
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: 'regexp:^v([0-9]+\.[0-9]+\.[0-9]+)$'
spec:
  releaseName: nginx-ingress
  helmVersion: v3
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: 2.11.0
  values:
    controller:
      image:
        repository: us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller
        tag: v0.34.0
      replicaCount: 1
      service:
        loadBalancerIP: 10.1.0.150
        externalTrafficPolicy: Local
```

**Anything else we need to know**:

/kind bug

**Comment by hphsu** [comment]
I also run into this issue.

**Comment by sdil** [comment]
Hi I had the same issue. However, I did not install nginx-ingress using Helm.

I fixed it by editing the nginx-ingress deployment manually to remove the sha.

`us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller:v0.34.1@sha256:0e072dddd1f7f8fc8909a2ca6f65e76c5f0d2fcfb8be47935ae3457e8bbceb20` into `us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller:v0.34.1`

Hope it helps. I'll open a PR in nginx-ingress Github project.

**Comment by sdil** [comment]
@rust84 @hphsu the nginx-ingress maintainer recommends to remove the digest from the helm manifest. You can set: 

```controller:
  image:
    digest: ''
```

**Comment by aledbf** [comment]
@sdil I am sorry. I don't recommend the removal of the digest. What I posted achieves what you want to do without any change in the provided manifests in ingress-nginx
Please check https://success.docker.com/article/images-tagging-vs-digests. 
You should write a different regexp rule for `fluxcd.io/tag.chart-image`

**Comment by sdil** [comment]
I think the root cause is actually FluxCD could not interpret image tag with digest. I created a simple Nginx service like:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: kube-system
  labels:
    app: test
spec:
  selector:
    matchLabels:
      app: test
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - image: nginx:stable@sha256:617fd9238bfff4a99543f231b9fb2a708002cdcaabffbb894d5b1e778363b90a
        name: nginx
```

And I can see this error log in Flux:

```
2020-08-03T13:27:08.870463449Z ts=2020-08-03T13:27:08.87033911Z caller=images.go:39 resource=kube-system:deployment/nginx-ingress-ingress-nginx-controller err="expected image name as either <image>:<tag> or just <image>: invalid image ID"
```

The correct fix should be applied on FluxCD itself :pray:
