### ISSUE TITLE
crashloop when sops is enabled

### ISSUE THREAD

**Issue by monotek** [fluxcd/flux#3205]
**Describe the bug**

flux crashloops when sops is enabled.

If i disable sops the container starts, i can exec in the flux container and decrypt a secret via sops after cloning the github repo.

**To Reproduce**

Install 

```
kubectl create namespace flux
kubectl -n flux create configmap sops-gpg-public-key --from-file=gpg-public-keys=/root/fluxcd/sops-gpg-public-key
kubectl -n flux create secret generic sops-gpg-private-key --from-file=gpg-keys=/root/fluxcd/sops-gpg-private-key
kubectl -n flux create secret generic ssh-private-key --from-file=identity=/root/fluxcd/ssh-private-key
helm repo add fluxcd https://charts.fluxcd.io
helm repo update
helm upgrade -i flux fluxcd/flux --wait --namespace flux --version=1.4.0 -f /root/fluxcd/values.yaml
```

My values file looks like:
```
git:
  url: git@github.com:monotek/flux
  secretName: ssh-private-key

gpgKeys:
  configMapName: sops-gpg-public-key
  secretName: sops-gpg-private-key

sops:
  enabled: true

manifestGeneration: true

registry:
  disableScanning: true

prometheus:
  enabled: true

dashboard:
  enabled: true

syncGarbageCollection:
  enabled: true
```

Create a sops encrypted kubernetes secret:

```
kubectl -n test --dry-run=true -o yaml create secret generic "test-helm-secrets" --from-file=values.yaml=secret-values.yaml > dec.secrets.yaml
sops -e dec.secrets.yaml > secrets.yaml
```
secret-values.yaml looks like:

```
value: secret
```

An reference is in helm operator release:

```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: test
  namespace: test
spec:
  releaseName: test
  chart:
    repository: https://test.github.io
    name: test
    version: 1.0.0
  valuesFrom:
    - secretKeyRef:
      name: test-helm-secrets
  values:
    foo: bar
```

**Expected behavior**

Flux decrypts sops secrets and container goes not into crashloop 

**Logs**

```
 k logs -f -l app=flux
ts=2020-07-20T23:58:23.155439941Z caller=main.go:493 component=cluster identity.pub="ssh-rsa *removed*
ts=2020-07-20T23:58:23.155462901Z caller=main.go:498 host=https://10.96.0.1:443 version=kubernetes-v1.18.6
ts=2020-07-20T23:58:23.155523693Z caller=main.go:510 kubectl=/usr/local/bin/kubectl
ts=2020-07-20T23:58:23.156900728Z caller=main.go:527 ping=true
ts=2020-07-20T23:58:23.157285707Z caller=main.go:666 url=ssh://git@github.com/monotek/*removed* user="foo bar" email=foobar@gmail.com signing-key= verify-signatures-mode=none sync-tag=flux-sync state=git readonly=false registry-disable-scanning=true notes-ref=flux set-author=true git-secret=false sops=true
ts=2020-07-20T23:58:23.157358519Z caller=main.go:772 upstream="no upstream URL given"
ts=2020-07-20T23:58:23.157952325Z caller=main.go:795 addr=:3030
ts=2020-07-20T23:58:23.15972099Z caller=loop.go:67 component=sync-loop info="Registry scanning is disabled; no image updates will be attempted"
ts=2020-07-20T23:58:23.160035338Z caller=loop.go:108 component=sync-loop err="loading last-synced resources: git repo not ready: git repo has not been cloned yet"
ts=2020-07-20T23:58:23.538367867Z caller=checkpoint.go:24 component=checkpoint msg="up to date" latest=1.20.0
ts=2020-07-20T23:58:13.967402907Z caller=sync.go:606 method=Sync cmd="kubectl apply -f -" took=215.396675ms err="running kubectl: The HelmRelease \"external-dns\" is invalid: spec.values: Invalid value: \"null\": spec.values in body must be of type object: \"null\"" output=
ts=2020-07-20T23:58:14.207804279Z caller=sync.go:606 method=Sync cmd="kubectl apply -f -" took=240.23813ms err="running kubectl: The HelmRelease \"zammad\" is invalid: spec.valuesFrom.secretKeyRef: Invalid value: \"null\": spec.valuesFrom.secretKeyRef in body must be of type object: \"null\"" output=
ts=2020-07-20T23:58:14.572428968Z caller=sync.go:159 info="cluster resource not in resources to be synced; deleting" dry-run=false resource=<cluster>:customresourcedefinition/helmreleases.helm.fluxcd.io
ts=2020-07-20T23:58:14.572596661Z caller=sync.go:159 info="cluster resource not in resources to be synced; deleting" dry-run=false resource=fluxcd:helmrelease/helm-operator
ts=2020-07-20T23:58:14.572844315Z caller=sync.go:540 method=Sync cmd=delete args= count=2
ts=2020-07-20T23:58:14.84073007Z caller=sync.go:606 method=Sync cmd="kubectl delete -f -" took=267.592877ms err=null output="helmrelease.helm.fluxcd.io \"helm-operator\" deleted\ncustomresourcedefinition.apiextensions.k8s.io \"helmreleases.helm.fluxcd.io\" deleted"
ts=2020-07-20T23:58:14.840982003Z caller=sync.go:230 component=daemon err="infra:helmrelease/external-dns: running kubectl: The HelmRelease \"external-dns\" is invalid: spec.values: Invalid value: \"null\": spec.values in body must be of type object: \"null\"; zammad:helmrelease/zammad: running kubectl: The HelmRelease \"zammad\" is invalid: spec.valuesFrom.secretKeyRef: Invalid value: \"null\": spec.valuesFrom.secretKeyRef in body must be of type object: \"null\""
ts=2020-07-20T23:58:14.848464706Z caller=daemon.go:701 component=daemon event="Sync: c8350f3, no workloads changed" logupstream=false
ts=2020-07-20T23:58:18.678937757Z caller=loop.go:236 component=sync-loop state="tag flux-sync" old=78f0b3472f82a07bbdddf4896874875f53352570 new=c8350f3414fca9378b8a8614b45735bf2dc9f17d
ts=2020-07-20T23:58:19.977970039Z caller=loop.go:134 component=sync-loop event=refreshed url=ssh://git@github.com/monotek/fluxcd-apps branch=master HEAD=c8350f3414fca9378b8a8614b45735bf2dc9f17d
ts=2020-07-20T23:58:32.299197018Z caller=main.go:809 exiting=terminated
ts=2020-07-20T23:58:32.299386517Z caller=loop.go:77 component=sync-loop stopping=true
rpc error: code = Unknown desc = Error: No such container: 7fba84b448b000fed0907a56cd5bed99d18892b13fc84eb971fe7ce7d7c823bdts=2020-07-20T23:58:34.446678663Z caller=loop.go:134 component=sync-loop event=refreshed url=ssh://git@github.com/monotek/fluxcd-apps branch=master HEAD=c8350f3414fca9378b8a8614b45735bf2dc9f17d
panic: attempted to parse unknown event: 8 [recovered]
	panic: attempted to parse unknown event: 8

goroutine 84 [running]:
github.com/mozilla-services/yaml.handleErr(0xc0020f0678)
	/home/circleci/go/pkg/mod/github.com/mozilla-services/yaml@v0.0.0-20191106225358-5c216288813c/yaml.go:254 +0x9a
panic(0x1a3b5c0, 0xc002215700)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/mozilla-services/yaml.(*parser).parse(0xc002228c00, 0xc00010f1b8)
	/home/circleci/go/pkg/mod/github.com/mozilla-services/yaml@v0.0.0-20191106225358-5c216288813c/decode.go:124 +0x198
github.com/mozilla-services/yaml.(*parser).mapping(0xc002228c00, 0x8)
	/home/circleci/go/pkg/mod/github.com/mozilla-services/yaml@v0.0.0-20191106225358-5c216288813c/decode.go:195 +0x9f
github.com/mozilla-services/yaml.(*parser).parse(0xc002228c00, 0xc002211280)
	/home/circleci/go/pkg/mod/github.com/mozilla-services/yaml@v0.0.0-20191106225358-5c216288813c/decode.go:113 +0x106
github.com/mozilla-services/yaml.(*parser).mapping(0xc002228c00, 0x8)
	/home/circleci/go/pkg/mod/github.com/mozilla-services/yaml@v0.0.0-20191106225358-5c216288813c/decode.go:195 +0x9f
github.com/mozilla-services/yaml.(*parser).parse(0xc002228c00, 0xc002211240)
	/home/circleci/go/pkg/mod/github.com/mozilla-services/yaml@v0.0.0-20191106225358-5c216288813c/decode.go:113 +0x106
github.com/mozilla-services/yaml.(*parser).mapping(0xc002228c00, 0xc00223c240)
	/home/circleci/go/pkg/mod/github.com/mozilla-services/yaml@v0.0.0-20191106225358-5c216288813c/decode.go:195 +0x9f
github.com/mozilla-services/yaml.(*parser).parse(0xc002228c00, 0xc00223c240)
	/home/circleci/go/pkg/mod/github.com/mozilla-services/yaml@v0.0.0-20191106225358-5c216288813c/decode.go:113 +0x106
github.com/mozilla-services/yaml.(*parser).mapping(0xc002228c00, 0xc0020f0401)
	/home/circleci/go/pkg/mod/github.com/mozilla-services/yaml@v0.0.0-20191106225358-5c216288813c/decode.go:195 +0x9f
github.com/mozilla-services/yaml.(*parser).parse(0xc002228c00, 0xc002223da0)
	/home/circleci/go/pkg/mod/github.com/mozilla-services/yaml@v0.0.0-20191106225358-5c216288813c/decode.go:113 +0x106
github.com/mozilla-services/yaml.(*parser).document(0xc002228c00, 0xc0020f0401)
	/home/circleci/go/pkg/mod/github.com/mozilla-services/yaml@v0.0.0-20191106225358-5c216288813c/decode.go:142 +0x9f
github.com/mozilla-services/yaml.(*parser).parse(0xc002228c00, 0x4ca)
	/home/circleci/go/pkg/mod/github.com/mozilla-services/yaml@v0.0.0-20191106225358-5c216288813c/decode.go:117 +0x6b
github.com/mozilla-services/yaml.unmarshalDocuments(0xc002238000, 0x4ca, 0x6ca, 0x19c1540, 0xc0022111e0, 0xc002226701, 0x0, 0x0)
	/home/circleci/go/pkg/mod/github.com/mozilla-services/yaml@v0.0.0-20191106225358-5c216288813c/yaml.go:88 +0x259
github.com/mozilla-services/yaml.CommentUnmarshaler.UnmarshalDocuments(...)
	/home/circleci/go/pkg/mod/github.com/mozilla-services/yaml@v0.0.0-20191106225358-5c216288813c/yaml.go:68
go.mozilla.org/sops/v3/stores/yaml.(*Store).LoadEncryptedFile(0x2fdebd8, 0xc002238000, 0x4ca, 0x6ca, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/circleci/go/pkg/mod/go.mozilla.org/sops/v3@v3.5.0/stores/yaml/store.go:108 +0xba
go.mozilla.org/sops/v3/decrypt.DataWithFormat(0xc002238000, 0x4ca, 0x6ca, 0x4, 0xc0002e2da8, 0x1, 0xc0020f0cf8, 0x504a8e, 0xc00010f188)
	/home/circleci/go/pkg/mod/go.mozilla.org/sops/v3@v3.5.0/decrypt/decrypt.go:38 +0xc0
go.mozilla.org/sops/v3/decrypt.Data(0xc002238000, 0x4ca, 0x6ca, 0x1d4c160, 0x4, 0x18, 0xc0020f0c68, 0x5049f5, 0x0, 0x0)
	/home/circleci/go/pkg/mod/go.mozilla.org/sops/v3@v3.5.0/decrypt/decrypt.go:75 +0x91
github.com/fluxcd/flux/pkg/cluster/kubernetes/resource.softDecrypt(0xc002238000, 0x4ca, 0x6ca, 0x4ca, 0x6ca, 0x0, 0x0, 0x20be4e0)
	/home/circleci/go/src/github.com/fluxcd/flux/pkg/cluster/kubernetes/resource/load.go:215 +0x61
github.com/fluxcd/flux/pkg/cluster/kubernetes/resource.loadFile(0xc00219f880, 0x3e, 0x1, 0x0, 0x20300000000000, 0x7f9524dfcfff, 0x7f9524bae068, 0xd0010000000000)
	/home/circleci/go/src/github.com/fluxcd/flux/pkg/cluster/kubernetes/resource/load.go:207 +0x77
github.com/fluxcd/flux/pkg/cluster/kubernetes/resource.Load.func1(0xc00219f880, 0x3e, 0x21521a0, 0xc002236000, 0x0, 0x0, 0x4d99c9, 0xc002236000)
	/home/circleci/go/src/github.com/fluxcd/flux/pkg/cluster/kubernetes/resource/load.go:55 +0x2c5
path/filepath.walk(0xc00219f880, 0x3e, 0x21521a0, 0xc002236000, 0xc0020f1420, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:358 +0x425
path/filepath.walk(0xc00219f7c0, 0x31, 0x21521a0, 0xc0021c1ee0, 0xc0020f1420, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:382 +0x2ff
path/filepath.walk(0xc0021d0cf0, 0x29, 0x21521a0, 0xc0021c1520, 0xc0020f1420, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:382 +0x2ff
path/filepath.walk(0xc0021d0c60, 0x23, 0x21521a0, 0xc0021c1450, 0xc0020f1420, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:382 +0x2ff
path/filepath.walk(0xc0020a8300, 0x1a, 0x21521a0, 0xc00219a5b0, 0xc0020f1420, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:382 +0x2ff
path/filepath.Walk(0xc0020a8300, 0x1a, 0xc00056d420, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:404 +0xff
github.com/fluxcd/flux/pkg/cluster/kubernetes/resource.Load(0xc0020a8300, 0x1a, 0xc0020aa310, 0x1, 0x1, 0xc00056d401, 0x40d6bd, 0x1c82ce0, 0xc0020a6780)
	/home/circleci/go/src/github.com/fluxcd/flux/pkg/cluster/kubernetes/resource/load.go:31 +0x19b
github.com/fluxcd/flux/pkg/cluster/kubernetes.(*manifests).LoadManifests(0xc000213140, 0xc0020a8300, 0x1a, 0xc0020aa310, 0x1, 0x1, 0x203000, 0x1a3b5c0, 0x0)
	/home/circleci/go/src/github.com/fluxcd/flux/pkg/cluster/kubernetes/manifests.go:122 +0x67
github.com/fluxcd/flux/pkg/manifests.(*rawFiles).GetAllResourcesByID(...)
	/home/circleci/go/src/github.com/fluxcd/flux/pkg/manifests/rawfiles.go:96
github.com/fluxcd/flux/pkg/manifests.(*configAware).getResourcesByID(0xc0020b4e40, 0x213dda0, 0xc0000ba058, 0x1, 0x1, 0xc00056dce0)
	/home/circleci/go/src/github.com/fluxcd/flux/pkg/manifests/configaware.go:204 +0x126
github.com/fluxcd/flux/pkg/manifests.(*configAware).GetAllResourcesByID(0xc0020b4e40, 0x213dda0, 0xc0000ba058, 0xc0020b6300, 0x28, 0x2125760)
	/home/circleci/go/src/github.com/fluxcd/flux/pkg/manifests/configaware.go:182 +0x5a
github.com/fluxcd/flux/pkg/daemon.(*Daemon).getLastResources(0xc000203c20, 0x213dda0, 0xc0000ba058, 0x21256a0, 0xc001862040, 0x0, 0x0, 0x0)
	/home/circleci/go/src/github.com/fluxcd/flux/pkg/daemon/sync.go:140 +0x176
github.com/fluxcd/flux/pkg/daemon.(*Daemon).Sync(0xc000203c20, 0x213dda0, 0xc0000ba058, 0x1aa0d3e8, 0xed6a826aa, 0x0, 0xc0020b6210, 0x28, 0x21256a0, 0xc001862040, ...)
	/home/circleci/go/src/github.com/fluxcd/flux/pkg/daemon/sync.go:49 +0x82
github.com/fluxcd/flux/pkg/daemon.(*Daemon).Loop(0xc000203c20, 0xc0001785a0, 0xc0001114d0, 0x20f2f20, 0xc000213500)
	/home/circleci/go/src/github.com/fluxcd/flux/pkg/daemon/loop.go:103 +0x525
created by main.main
	/home/circleci/go/src/github.com/fluxcd/flux/cmd/fluxd/main.go:777 +0x5990

```

**Additional context**

- Flux version: 1.20
- Kubernetes version: 1.18.5
- Git provider: Github private repo
- Container registry provider: bare metal

**Comment by monotek** [comment]
This might be a problem with k8s version 1.18.6.
I could not reproduce in 1.16.12.

**Comment by monotek** [comment]
Looks like the commented out part of my helmrelase values habs been problem:

```
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: metallb
  namespace: infra
spec:
  releaseName: metallb
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: metallb
    version: 0.1.17
  values:
    configInline:
      # The address-pools section lists the IP addresses that MetalLB is
      # allowed to allocate, along with settings for how to advertise
      # those addresses over BGP once assigned. You can have as many
      # address pools as you want.
      address-pools:
      - # A name for the address pool. Services can request allocation
        # from a specific address pool using this name, by listing this
        # name under the 'metallb.universe.tf/address-pool' annotation.
        name: generic-cluster-pool
        # Protocol can be used to select how the announcement is done.
        # Supported values are bgp and layer2.
        protocol: layer2
        # A list of IP address ranges over which MetalLB has
        # authority. You can list multiple ranges in a single pool, they
        # will all share the same settings. Each range can be either a
        # CIDR prefix, or an explicit start-end range of IPs.
        addresses:
        -  10.2.2.2/32
```

switching to the following config solved the problem:

```
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: metallb
  namespace: infra
spec:
  releaseName: metallb
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: metallb
    version: 0.1.17
  values:
    configInline:
      address-pools:
        - name: generic-cluster-pool
          protocol: layer2
          addresses:
            -  10.2.2.2/32
```
