### ISSUE TITLE
Flux fails to update HelmRelease container image tag

### ISSUE THREAD

**Issue by tux-00** [fluxcd/flux#3206]
I'm not sure if it's a bug or if I'm wrong with something in structure of my repository but I can't find any information on the error I get.

When I'm trying to automate the update of the container tag into an HelmRelease I get the following error in Flux logs:
```
ts=2020-07-21T09:46:57.460744607Z caller=loop.go:152 component=sync-loop jobID=a00e3768-9323-8160-97b2-d20bbdbce077 state=done success=false err="applying changes: updating resource dev:helmrelease/front-player in dev/../.flux.yaml: no update.containerImage commands to run in ../.flux.yaml (from path dev)"
```

Flux seems to detect the new images (but do not perform the update due to the above error):
```
$ fluxctl list-images -n dev --workload=helmrelease/front-player
WORKLOAD                      CONTAINER    IMAGE                                                       CREATED
dev:helmrelease/front-player  chart-image  mycompany.com/labs/app/front/app-front-player  
                                           |   dev-65e81240                                            20 Jul 20 16:03 UTC
                                           |   dev-10a8f554                                            20 Jul 20 14:24 UTC
                                           '-> dev-610f38ea                                            17 Jul 20 08:54 UTC
                                               latest                                                  17 Jul 20 08:54 UTC
                                               dev-a2af8698                                            16 Jul 20 08:37 UTC
                                               dev-e07de04a                                            16 Jul 20 06:41 UTC
                                               dev-59845524                                            15 Jul 20 15:26 UTC
                                               dev-dd02794f                                            15 Jul 20 14:15 UTC
                                               dev-960c8bd5                                            15 Jul 20 13:33 UTC
                                               f9b3e5e4                                                21 Apr 20 08:14 UTC
```

HelmRelease status:
```
NAME           RELEASE        PHASE       STATUS     MESSAGE                                                            AGE
front-player   front-player   Succeeded   deployed   Release was successful for Helm release 'front-player' in 'dev'.   3d20h
```

Global directory tree:
```
.
├── base
│   └── releases
├── common
│   ├── namespaces
│   └── releases
├── dev # <--- The problem is here
│   ├── releases
│   └── kustomization.yaml
├── predev
│   ├── releases
│   └── kustomization.yaml
├── preprod
│   ├── releases
│   └── kustomization.yaml
└── prod
    ├── releases
    └── kustomization.yaml
```

Dev directory tree:
```
dev/
├── releases
│   ├── front
│   │   ├── kustomization.yaml
│   │   └── player.yaml
│   ├── monitoring
│   │   └── [TRUNCATED]
│   └── kustomization.yaml
└── kustomization.yaml
```

The kustomization.yaml into `dev/releases/front/`:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - player.yaml
```

The YAML which is failing is this one (`dev/releases/front/player.yaml`):
```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: front-player
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: front-player
  chart:
    git: git@gitlab.bbuzcloud.com:nextgen/flux-cluster-config.git
    ref: charts
    path: front
  values:
    replicaCount: 1

    image:
      repository: mycompany.com/labs/app/front/app-front-player
      tag: dev-610f38ea
      pullPolicy: IfNotPresent

    imagePullSecrets:
      - name: mycompany.com
[TRUNCATED]
```

Flux install command:
```
helm upgrade -i flux \
--set registry.rps=100 \
--set registry.disableScanning=false \
--set registry.includeImage="mycompany.com/*" \
--set git.url=git@gitlab.bbuzcloud.com:nextgen/flux-cluster-config.git \
--set git.branch=master \
--set git.path="dev\,common" \
--set git.label="dev" \
--set git.pollInterval=1m \
--set-string ssh.known_hosts="${KNOWN_HOSTS}" \
--set manifestGeneration="true" \
--set prometheus.enabled="true" \
--set prometheus.serviceMonitor.create="true" \
--set prometheus.serviceMonitor.namespace="monitoring" \
--set dashboards.enabled="true" \
--namespace flux \
--version 1.4.0 \
fluxcd/flux
```

Additional logs (Flux detects that he needs to update a workload):
```
ts=2020-07-21T09:52:57.596415875Z caller=images.go:111 component=sync-loop workload=dev:helmrelease/front-player container=chart-image repo=mycompany.com/labs/app/front/app-front-player pattern=glob:dev-* current=mycompany.com/labs/app/front/app-front-player:dev-610f38ea info="added update to automation run" new=mycompany.com/labs/app/front/app-front-player:dev-65e81240 reason="latest dev-65e81240 (2020-07-20 16:03:09.0982546 +0000 UTC) > current dev-610f38ea (2020-07-17 08:54:44.883909628 +0000 UTC)"
```

- Flux version: 1.20.0
- Kubernetes version: v1.16.3
- Git provider: Gitlab
- Container registry provider: Docker Registry

**Comment by tux-00** [comment]
It seems a configuration was bad into the .flux.yaml file at the root of the repo, now the file looks like this:
```
version: 1
commandUpdated:
  generators:
    - command: kustomize build .
  updaters:
    - containerImage:
        command: kustomize edit set image $FLUX_CONTAINER=$FLUX_IMG:$FLUX_TAG
```

The error about `no update.containerImage commands to run` is not present anymore but Flux can't update the workload and the log is:
```
ts=2020-07-21T15:50:08.802625308Z caller=loop.go:152 component=sync-loop jobID=621eac08-1e25-0a30-5769-b375643694e1 state=done success=false err="verifying changes: failed to verify changes: the image for container \"chart-image\" in resource \"dev:helmrelease/front-player\" should be \"mycompany.com/labs/cpos/front/cpos-front-player:dev-43a911e5\", but is \"mycompany.com/labs/cpos/front/cpos-front-player:dev-0de9456c\""
```

I also changed the player.yaml file wich is now (changed `filter.fluxcd.io/chart-image` to `filter.fluxcd.io/tag.chart-image`, not sure it makes a difference):
```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: front-player
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/tag.chart-image: glob:dev-*
spec:
  releaseName: front-player
  chart:
    git: git@gitlab.bbuzcloud.com:nextgen/flux-cluster-config.git
    ref: charts
    path: front
  values:
    replicaCount: 1

    image:
      repository: mycompany.com/labs/app/front/app-front-player
      tag: dev-610f38ea
      pullPolicy: IfNotPresent

    imagePullSecrets:
      - name: mycompany.com
[TRUNCATED]
```
