### ISSUE TITLE
Problem unmarshalling patch

### ISSUE THREAD

**Issue by davidmogar** [fluxcd/flux#3218]
**Describe the bug**

I'm trying to deploy multiple releases sharing the same secrets. To do so I defined a configmap which contains a single `values.yaml` key with all the secret keys. I used sops to encrypt the content of `values.yaml` so my final file looks like this (I omit part of the content with `...`):
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
    name: secrets
    namespace: default
data:
    values.yaml: ENC[AES256_...
sops:
...
```
Then, I have a `.flux.yaml` file with the following content:
```yaml
version: 1
patchUpdated:
  generators:
    - command: sops -d --output ../secrets.yaml ../secrets.enc.yaml
    - command: kubectl apply -f ../secrets.yaml
    - command: rm -rf ../secrets.yaml
  patchFile: helm-release-patch.yaml
```
The configmap is created successfully in the cluster with the expected content (I omit again part of the content with `...`):
```yaml
apiVersion: v1
data:
  values.yaml: |
    secrets:
...
kind: ConfigMap
metadata:
...
```
The release is not created though as Flux seems to fail when unmharsalling the content:
```
Unable to parse files as manifests

Flux was unable to parse the files in the git repo as manifests,
giving this error:

    processing "../.flux.yaml", cannot apply patchFile "helm-release-patch.yaml" to generated resources: cannot parse ../.flux.yaml: parsing YAML doc from "../.flux.yaml": yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `configm...` into resource.baseObject

Check that any files mentioned are well-formed, and resources are not
defined more than once. It's also worth reviewing...
```
My release references the configmap with:
```yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
...
spec:
  valuesFrom:
    - configMapKeyRef:
        name: secrets
        namespace: default
```
**Logs**

```
ts=2020-07-27T13:46:12.095346641Z caller=sync.go:73 component=daemon info="trying to sync git changes to the cluster" old= new=8816f22a1ded9696997378b14443aba737679151
ts=2020-07-27T13:46:14.362938739Z caller=loop.go:107 component=sync-loop err="loading resources from repo: processing \"../.flux.yaml\", cannot apply patchFile \"helm-release-patch.yaml\" to generated resources: cannot parse ../.flux.yaml: parsing YAML doc from \"../.flux.yaml\": yaml: unmarshal errors:\n  line 1: cannot unmarshal !!str `configm...` into resource.baseObject"
```

**Additional context**

- Flux version: 1.19
- Kubernetes version: 1.18
- Git provider: GitLab
- Container registry provider: GitLab
