### ISSUE TITLE
Flux keeps using the latest image instead of the one in the IMAGE tag

### ISSUE THREAD

**Issue by Skarlso** [fluxcd/flux#3220]
**Describe the bug**

Hi.

So I have a deployment like this:

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cronohub
  name: gaia-app
  labels:
    app: gaia-app
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9090'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gaia-app
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9090'
      labels:
        app: gaia-app
        app.kubernetes.io/name: gaia-app
        app.kubernetes.io/instance: gaia-app
    spec:
      containers:
      - name: gaia
        image: gaiapipeline/gaia:v0.2.5
        ports:
        - containerPort: 8080
          name: gaia-http
        volumeMounts:
        - mountPath: /data
          name: gaia-data
          readOnly: false
        args:
        - -hostname="https://gaia.cronohub.org"
      volumes:
      - name: gaia-data
        persistentVolumeClaim:
          claimName: do-storage-gaia

```

Note that this `image: gaiapipeline/gaia:v0.2.5` is the image tag I'm using but in the repo, the latest is `gaiapipeline/gaia:latest-python` based on the push tag. But that doesn't contain stuff from the tag at v0.2.5. It just was happened to be pushed last.

So I would like flux to not be clever and apply whatever the hell is in the file instead of trying to apply the latest. I see this line in the logs:

```
ts=2020-07-29T06:59:56.386370319Z caller=images.go:111 component=sync-loop workload=cronohub:deployment/gaia-app container=gaia repo=gaiapipeline/gaia pattern=glob:* current=gaiapipeline/gaia:v0.2.5 info="added update to automation run" new=gaiapipeline/gaia:latest- │
│ python reason="latest latest-python (2020-07-29 05:07:33.2474212 +0000 UTC) > current v0.2.5 (2020-07-29 05:07:27.4521261 +0000 UTC)"
```

How can I disable this feature? :)

- Flux version: 1.19.0
- Kubernetes version: 1.17
- Git provider: github
- Container registry provider: hub.docker.com
