### ISSUE TITLE
flux hasn't access to ECR repo 

### ISSUE THREAD

**Issue by serheevas** [fluxcd/flux#3269]
**Describe the bug**

I run fluxcd as helm chart in k8s cluster,
and saw logs -  flux hasn't access to ECR:

**To Reproduce**

Steps to reproduce the behaviour:

1. Provide Flux install instructions

1.1 I installed k8s cluster using kops - kubernetes version 1.15.9
1.2. installed helm v2
1.3 installed fluxcd as helm package 1.5.0 version use manual  - https://hub.helm.sh/charts/fluxcd/flux/1.5.0

1.4  generated ssh, add it to git repo
1.5 create secret flux-ssh
1.6 get creds for ECR - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 720120786535.dkr.ecr.eu-west-1.amazonaws.com

1.7 created secret docker-creds from docker/config.json 
1.8 deploy fluxcd:
   helm upgrade -i fluxcd-test fluxcd/flux \
      --set git.url=git@github.com:sk-telemed/show2doc-helm-charts \
      --set git.secretName=flux-ssh \
      --set registry.dockercfg.enabled=true \
      --set registry.dockercfg.secretName=docker-creds \
      --set registry.trace=false \
      --namespace fluxcd

```
flux args:
  containers:
  - args:
    - --log-format=fmt
    - --ssh-keygen-dir=/var/fluxd/keygen
    - --ssh-keygen-format=RFC4716
    - --k8s-secret-name=flux-ssh
    - --memcached-hostname=fluxcd-test-memcached
    - --sync-state=git
    - --memcached-service=
    - --git-url=git@github.com:sk-telemed/show2doc-helm-charts
    - --git-branch=test
    - --git-path=
    - --git-readonly=false
    - --git-user=Weave Flux
    - --git-email=support@weave.works
    - --git-verify-signatures=false
    - --git-set-author=false
    - --git-poll-interval=5m
    - --git-timeout=20s
    - --sync-interval=5m
    - --git-ci-skip=false
    - --automation-interval=5m
    - --registry-rps=200
    - --registry-burst=125
    - --registry-trace=false
    - --docker-config=/dockercfg/docker.json
```

i checked get aws ecr login from my k8s node - its worked:
```
root@ip-172-20-99-119:/# aws ecr get-login --region eu-west-1 --no-include-email
docker login -u AWS -p eyJwYXlsb2FkIjoiVFkzM0JyZ29IWHFSak9......
```

2. Provide a GitHub repository with Kubernetes manifests

**Expected behavior**

flux get images/tags from ECR...

**Logs**
get logs from pod:
root@combo-VirtualBox:~/.docker# kubectl get po -n fluxcd
NAME                                                  READY   STATUS    RESTARTS   AGE
fluxcd-operator-test-helm-operator-544cb9f9b8-npmrz   1/1     Running   0          4h24m
fluxcd-test-5c6dcd69cc-7f9pb                          1/1     Running   0          38m
fluxcd-test-memcached-54f8cfbdd4-rfl46                1/1     Running   0          4h35m

ubectl -n fluxcd logs -f fluxcd-test-5c6dcd69cc-7f9pb

```
 denied: Your authorization token has expired. Reauthenticate and try again."
ts=2020-08-30T06:21:06.263400529Z caller=warming.go:180 component=warmer canonical_name=720120786535.dkr.ecr.eu-west-1.amazonaws.com/stage2-s2d-chatservice auth="{map[720120786535.dkr.ecr.eu-west-1.amazonaws.com:<registry creds for AWS@720120786535.dkr.ecr.eu-west-1.amazonaws.com, from stage2:secret/stage2-s2d-chat-service>]}" err="requesting tags: denied: Your authorization token has expired. Reauthenticate and try again."
ts=2020-08-30T06:21:06.272767668Z caller=warming.go:180 component=warmer canonical_name=720120786535.dkr.ecr.eu-west-1.amazonaws.com/stage2-s2d-notificationsserviceemail auth="{map[720120786535.dkr.ecr.eu-west-1.amazonaws.com:<registry creds for AWS@720120786535.dkr.ecr.eu-west-1.amazonaws.com, from stage2:secret/stage2-s2d-notifications-service-email>]}" err="requesting tags: denied: Your authorization token has expired. Reauthenticate and try again."
ts=2020-08-30T06:21:06.281591613Z caller=warming.go:180 component=warmer canonical_name=720120786535.dkr.ecr.eu-west-1.amazonaws.com/devs-s2d-chatservice auth="{map[720120786535.dkr.ecr.eu-west-1.amazonaws.com:<registry creds for AWS@720120786535.dkr.ecr.eu-west-1.amazonaws.com, from devs:secret/devs-s2d-chat-service>]}" err="requesting tags: denied: Your authorization token has expired. Reauthenticate and try again."
```
my secret docker-config

```
root@combo-VirtualBox:~/.docker# kubectl get secrets docker-creds1 -o yaml  -n fluxcd
apiVersion: v1
data:
  docker.json: ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICI3MjAxMjA3ODY1MzUuZGtyLmVjci5ldS13ZXN0LTEuYW1hem9uYXdzLmNvbSI6IHsKICAgICAgICAgICAgICAgICAgICAgICAgImF1dGgiOiAiUVZkVE9tVjVTbmRaV0d4ellqSkdhMGxxYjJsV1JtdDZUVEJLZVZveU9VbFhTRVpUWVdzNWExUXdTblZUZWxKVVdqRndkVmt3TlVOV00wWlJUVmhXZEZKck1WcFRiV3N3VkVjMWJWTnRUakZrUkU1eldsUkJNV05GTVROWmVtUXdXVE5XZG1Nd09WRk9WMUp3VlZoTk5XRlVUVEJrVlhSaFRUSjBWbE5IVGxGT1YxWnlWVlZXVTA5VGRIUmtNV3hTVTFSV1Nsb3dkRTVNTW1SdFlVVkdRbE15YkZkT1JUVlRVMVZ6ZDB3elJsQlVWbEoxVjFSb2FVMVhlRlJoVkVVd1YyNVNNMVZYWkd4T2EzUm9VbFpKZDFscmQzbFVSMlIzVkRCT2FXSkVXVEpoVmxFeVlrUkdTRTB3U25CTlJVazBZakExZGsxRk9YSlJlbVJIV1hwU2VGWnRXakJaVlRsNlpFWnNSV1ZFUlhwaFZrWlZUbXRPVUZGc1VsaFNhbHBOVjBkT1MxTkZXWHBhV0VVd1RsaFdjMVV3ZUVkV2VtZzJZVmMwTlZGVE9EQlRNbFpWVmxobk1FOVhkR2xUV0ZKU1ZXdE9iRTFJV25Wa01scEdaRlJXY21GdFRrdGFiWEJzVm01S1VsUnNiRVprUkVwQ1ZGWkdhMVJZVFRCU1ZsWnJVbXhTYzFKVGRHeFRSRTAwWTJ0U05GcHFUbWxqYkVaelltcEdjVkpVV25STk1FbzJUVlJPVFZKVlVsVlpXRWx5WVZVNVdXRkhkRWRoYld4UFYyMUtNbEZWVmtkVVJFWjNVVEJTTW1NeVRtNVdSRkpVWWtSR1dXRkdaSHBpVlVaWVpHcG9lRlZZVW14T1IyUkRUMVp3U2xNeVpGUmpWa1V3VVZoR1RtUnFXak5XUm14NlpXNXJNMkpyY0VKVVIzQnBXakZrVVZOVVpISk5WM00xWkZVMVExSnFRbFZrTWtaTFRYcENUazlXYkhWaVIyZDVaVmhTYzJSc1NraFNSbkIwVmpKb2VsUnRkSEZVTW1SelYxZHdlbEl3VWtsTWVYUTBVVzFLTWxFeFdtcFpiR3hRVm5wT2QxVldXbTFYUldjMFYydEdTMkl5U2xoVE0yeHdXak5vU1ZKVk5WZGhSV1JoWVRCYWVWSnVaelZWUjNOMlkyNUNSVk15V1hsVmJFcHZXbnBPTWxZeWNIWk9iRTR5VW10T1RFMVhOVnBWV0VKVVZFZGFWRlZXYUZwU2FrcFhWRzFhUzFkdFNUVkxNRFY1WVVSU1ZV.....
```

If applicable, please provide logs of `fluxd`. In a standard stand-alone installation of Flux, you'd get this by running `kubectl logs deploy/flux  -n flux`.

**Additional context**

- Flux version: docker.io/fluxcd/flux:1.20.2
- Kubernetes version: 1.15.9
- Git provider: github
- Container registry provider: kops
