### ISSUE TITLE
Too many commits from released images

### ISSUE THREAD

**Issue by nomeelnoj** [fluxcd/flux#3292]
**Describe the bug**

Our workloads run across 10-15 images.  We release these in parallel at the end of a release build, so they are uploaded to our registry within 5 min of each other maximum.

When flux scans the registry to deploy the new workloads, we get 7-10 individual commits back to our gitops repo saying `Auto-release of <image>`.  Occasionally, we get two images in one commit, but most always we see each image getting it's own distinct commit.

I have modified the registry automationInterval to 15m in hopes that it would find them all at once and commit them back all at once, but this has not changed anything.

**To Reproduce**

Steps to reproduce the behaviour:

1. Install flux, set automationInterval to 15m
2. Deploy 20-30 workloads sharing ~10-15 images
3. Upload new images for 7-10 of the images

**Expected behavior**

I would expect that flux sees all these images as new and waits to commit back until no new images are found or the commit message has maxed out with 10 images

**Additional context**

- Flux version: 1.20.2
- Kubernetes version: 1.17
- Git provider: github
- Container registry provider: ECR

**Comment by nomeelnoj** [comment]
Hello there? Any updates here?

**Comment by kingdonb** [comment]
Since you're working in a private registry, I think you would not be rate-limited by the registry itself, but flux image scanning may be rate limiting itself.

Have you found these configurable parameters under registry section of the flux chart?

https://github.com/fluxcd/flux/blob/881dd8ecd4414f055f0491ae17bdb96defaa300a/chart/flux/values.yaml#L165-L171

```yaml
registry:
  # Period at which to check for updated images
  automationInterval: "5m"
  # Maximum registry requests per second per host
  rps: 200
  # Maximum number of warmer connections to remote and memcache
  burst: 125
```

The limits self-imposed by Flux are based on these values. Depending on the number of images scanned by Flux for changes, you might find that setting these values higher results in faster turnaround on Flux image warmer reaching all of the images in time to coordinate a sync in single commit.
