### ISSUE TITLE
Flux dont release a new image app

### ISSUE THREAD

**Issue by neomadara** [fluxcd/flux#3317]
**Describe the bug**

When i created a new image and pushed to ECR, flux dont make the change of the image in the deployment, but if manually change deployment file, and pushed this commit, flux make the change in the cluster.

**To Reproduce**

if a run this:  
fluxctl release --workload=dev:deployment/hello-docker --update-image=hello-docker:release-1601736723

the response is:
Submitting release ...
Error: image "hello-docker:release-1601736723" does not exist: invalid image ID

Deployment file:

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: hello-docker
  annotations:
    fluxcd.io/tag.hello-docker: glob:release-*
    fluxcd.io/automated: 'true'
spec:
  selector:
    matchLabels:
      app: hello-docker
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-docker
    spec:
      containers:
      - name: hello-docker
        image: 273247641036.dkr.ecr.sa-east-1.amazonaws.com/hello-docker:release-1601736193
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: sa-east-1-ecr-registry
```

**Logs**

Deployment/flux
```
ts=2020-10-04T20:06:06.224346346Z caller=loop.go:142 component=sync-loop jobID=7ccc31f6-8ee2-b1b3-3d3a-9fc2041801d2 state=in-progress
ts=2020-10-04T20:06:06.324393535Z caller=loop.go:152 component=sync-loop jobID=7ccc31f6-8ee2-b1b3-3d3a-9fc2041801d2 state=done success=false err="image \"hello-docker:release-1601736723\" does not exist: invalid image ID"
```

**Additional context**

- Flux version: 1.20.2
- Kubernetes version: 1.18
- Git provider: github
- Container registry provider: ECR
