### ISSUE TITLE
SOPS + Azure KeyVault not decrypting a file

### ISSUE THREAD

**Issue by Djiit** [fluxcd/flux#3326]
**Describe the bug**

Hey, I'm trying to use the sops integration, using Azure Key Vault, but Flux fails to decrypt my file.

**To Reproduce**

Steps to reproduce the behaviour:

1. Install Flux with the following Helm values : 
```
sops:
  enabled: true
extraEnvs:
  - name: AZURE_CLIENT_ID
    value: REDACTED
  - name: AZURE_CLIENT_SECRET
    value: REDACTED
  - name: AZURE_TENANT_ID
    value: REDACTED
  - name: SOPS_AZURE_KEYVAULT_URLS
    value: REDACTED
```

2. Commit a resource (say, a secret) encrypted with SOPS (with the same variables as above, locally)

3. Nothing happens :( 

**Expected behavior**

Flux successfully decrypt the file and create a resource in Kubernetes.

**Logs**

```
ts=2020-10-09T16:24:06.445530578Z caller=images.go:23 component=sync-loop error="getting unlocked automated resources: unable to read file at \"/tmp/flux-working922399399/flux/REDACTED/secret.yaml\": failed to decrypt file: No keys found in file"
```

**Additional context**

- Flux version: 1.20.0
- Kubernetes version: 1.18.8
- Git provider: Gitlab
- Container registry provider: Harbor
