### ISSUE TITLE
image format problem with ingress-nginx

### ISSUE THREAD

**Issue by masterkain** [fluxcd/flux#3329]
just noticed this in flux logs:

`caller=images.go:39 resource=ingress-nginx:deployment/ingress-nginx-controller err="expected image name as either <image>:<tag> or just <image>: invalid image ID`

using this:

```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  annotations:
    fluxcd.io/ignore: "false"
spec:
  releaseName: ingress-nginx
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: 3.4.1
  values:
    controller:
```

these are their image setting:
https://github.com/kubernetes/ingress-nginx/blob/master/charts/ingress-nginx/values.yaml#L5-L12

anything we can do?
