### ISSUE TITLE
Bug? Properties specified in flux-patch.yaml for deployment are deleted in flux auto commit after new image is deployed

### ISSUE THREAD

**Issue by joerg-walter-de** [fluxcd/flux#3354]
I have a deployment organized in a base and an overlay. In the base some ENVs are declared. In the flux-patch.yaml file in the overlay only the image is declared. The whole flux mechanism works fine for that.

But when I add an ENV declaration in the flux-patch.yaml file 

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xxx
  namespace: xxx
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: xxx
      containers:
      - 
        name: xxx
        image: xxx:develop-v0.9.11-287f0365
        env:
        - 
          name: XXX
          value: 'yyy'

```

flux deletes in an auto commit after deploying a new image detected in the registry the env property from that file.

Is that intended behviour? If so how to cure that?

I have 

```
version: 1
patchUpdated:
  generators:
    - command: kustomize build .
  patchFile: flux-patch.yaml
```

and 

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base/
patchesStrategicMerge:
  - flux-patch.yaml
```
