### ISSUE TITLE
FluxCD not updating when new images are published in the Docker Registry

### ISSUE THREAD

**Issue by fernandocamargoti** [fluxcd/flux#3357]
**Describe the bug**

I have installed the FluxCD and Healm Operator, configuring it to access a private Git Repository and a private Docker Registry. If I change anything in the git repo, it syncs perfectly. But when I push a new tag of the image to the Docker Registry, nothing happens.

**To Reproduce**

Steps to reproduce the behaviour:

Installation commands:

```
kubectl create namespace flux-ai
kubectl create namespace ai
kubectl create secret generic datahreg --namespace flux-ai --from-file=.dockerconfigjson=docker-config.json --type=kubernetes.io/dockerconfigjson
kubectl create secret generic datahreg --namespace ai --from-file=.dockerconfigjson=docker-config.json --type=kubernetes.io/dockerconfigjson
kubectl create secret generic api-secret-auth --namespace ai --from-literal=postgres_password='[redacted]'
helm upgrade -i flux-ai charts/flux-ai/ --namespace flux-ai
```

I have a helm chart to configure the values of both FluxCD and Helm Operator:

```
Chart.yaml:
apiVersion: v2
name: flux
description: The configured Flux Instalation for the AI Deployment
type: application
version: 0.0.1
appVersion: 1.0
dependencies:
  - name: flux
    version: 1.5.0
    repository: https://charts.fluxcd.io
  - name: helm-operator
    version: 1.2.0
    repository: https://charts.fluxcd.io
```
```
values.yaml:
flux:
  git:
    url: [redacted]
    branch: master
    secretName: flux-git-deploy
  registry:
    trace: true
    dockercfg:
      enabled: true
      secretName: datahreg
      configFileName: /dockercfg/
  ssh:
    known_hosts: |
      # github
      github.com,140.82.113.3 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
      # private gitlab
      [redacted],[redacted] ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBPa9u0jE3d6ivlc0TVJQxcG7rnwlvwN7Rly5P4dvnT97crHtlCpLyjOhoFVO7ykXb2BuxLkYXVkaryx/VGhGZ5U=
helm-operator:
  createCRD: true
  allowNamespace: ai
  helm:
    versions: "v3"
  git:
    ssh:
      secretName: flux-git-deploy
      known_hosts: |
        # github
        github.com,140.82.113.3 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
        # private gitlab
        [redacted],[redacted] ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBPa9u0jE3d6ivlc0TVJQxcG7rnwlvwN7Rly5P4dvnT97crHtlCpLyjOhoFVO7ykXb2BuxLkYXVkaryx/VGhGZ5U=
```

This is my HelmRelease:

```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: daily-demand-forecaster
  namespace: ai
  annotations:
    fluxcd.io/automated: "true"
    registry.fluxcd.io/daily: docker.registry
    repository.fluxcd.io/daily: model.image.name
    tag.fluxcd.io/daily: model.image.tag
    filter.fluxcd.io/daily: semver:~1
spec:
  releaseName: daily-demand-forecaster
  chart:
    git: [redacted]
    ref: master
    path: charts/demand-forecaster
  values:
    docker:
      registry: [redacted]
    model:
      image:
        name: logit/gazin-daily-demand-forecaster
        tag: 1.0.20201106081312_322B77
    postgres:
      poolSize: 8
      host: [redacted]
      port: 5499
      db: [redacted]
      user: [redacted]
      password:
        secret: api-secret-auth
        key: postgres_password
```

Both private Git Repo and private Docker Registry seems to be correctly configured, since everything else works. The only thing that doesn't work is updating when a new tag is pushed into the Docker Registry.

Could it be related to the way my tags are written?

I have the current version 1.0.20201106081312_322B77 and the new version 1.0.20201106095051_076720. Could this suffix be impacting the update?

**Expected behavior**

After pushing a new tag, the release should be updated.

**Logs**

If applicable, please provide logs of `fluxd`. In a standard stand-alone installation of Flux, you'd get this by running `kubectl logs deploy/flux  -n flux`.

**Additional context**

- Flux version: 1.5.0
- Kubernetes version: 1.19
- Git provider: GitLab
- Container registry provider: Docker Registry
