### ISSUE TITLE
Configure helmrelease with custom values.yaml

### ISSUE THREAD

**Issue by gerardgorrion** [fluxcd/flux#3359]
Hi all,

We are deploying a fluxcd on our cluster. Now we want to use helm-operator to deploy a public chart (do not want to store every chart structure and files on every chart deployed), but we want to use a custom values.yaml file to configure chart deploy, and when we update values.yaml file, the helm deploy should recreate the pod with the new configuration.

We try to use _spec.valuesFrom_:
[https://docs.fluxcd.io/projects/helm-operator/en/1.0.0-rc9/references/helmrelease-custom-resource.html#config-maps](https://docs.fluxcd.io/projects/helm-operator/en/1.0.0-rc9/references/helmrelease-custom-resource.html#config-maps)

- configmaps
- secrets
- external sources
- chart files

But the problem is:

-  on configmaps and secrets we cant update values.yaml and apply, if we deploy manually configmap and secret work fine, but we can't automate it.
- chart files use the same repo that the chart, can't use custom values.yaml file
- external resources: this option should be work, but when configure at helmrelease yaml file...:

akhq.yaml
```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: akhq-kafka
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: akhq-kafka
  chart:
    repository: https://akhq.io/
    name: akhq
    version: 0.1.3
  valuesFrom:
  - externalSourceRef:
      url: https://bitbucketfactory.company.com/projects/CD/flux/values.yml
```
Log of helm-operator pod:
```
ts=2020-11-17T08:20:48.20723719Z caller=release.go:100 component=release release=akhq-kafka targetNamespace=default resource=default:helmrelease/akhq-kafka helmVersion=v2 error="failed to compose values for release: unable to yaml.Unmarshal [60 33 68 79 67 84 89 80 69 78 112 99 122 112 117 89 87 49 108 99 122 112 48 89 122 112 84 81 85 49 77 79 106 73 117 77 68 112 119 99 109 57 48 98 50 78 118 98 67 73 103 81 88 78 122 90 88 74 48 97 87 57 117 81 50 57 117 99 51 86 116 90 88 74 84 90 88 74 50 97 87 78 108 86 86 74 77 80 83 74 111 100 72 82 119 99 122 111 118 76 50 74 112 100 71 74 49 89 50 116 108 100 71 90 104 89 51 82 118 99 110 107 117 98 87 86 115 97 87 69 117 89 50 57 116 76 51 66 115 100 87 100 112 98 110 77 110 47 104 116 109 108 62] from URL https://bitbucketfactory.company.com/projects/CD/flux/values.yml"
```

There're some easy way to resolve this error or use a public chart with custom values.yaml?

Additional information:
**kubctl v1.19.0
EKS v1.15.12
fluxctl v1.20.1
helm 2.14
Tiller v2.14.0**

**Comment by gerardgorrion** [comment]
```
spec:
  chart:
     ...
  values:
    value1: data
    value2: data
```

Resolved.
