### ISSUE TITLE
Flux Workload Automation not respecting HelmRelease filter annotation

### ISSUE THREAD

**Issue by Starefossen** [fluxcd/flux#3365]
**Describe the bug**

Flux workload automation for HelmRelease objects is not respecting filter annotation.

**To Reproduce**

HelmRelease:

```yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/chart-image: glob:release-*
    fluxcd.io/automated: "true"
  name: my-app
  namespace: my-ns
spec:
  chart:
    name: my-chart
    repository: https://some-registry.io
    version: ^1.2.3
  values:
    image:
      image: myreg.io/my/image:release-v1-19-5-13
```

**Expected behavior**

When pushing new tags to the `myreg.io/my/chart` image matching the glob patter `release-*` Flux would update the HelmRelease. Pushing tags not matching the glob pattern `release-*` should not trigger an automatic update.

**Logs**

```
ts=2020-11-19T09:57:38.036775568Z caller=images.go:17 component=sync-loop msg="polling for new images for automated workloads"
ts=2020-11-19T09:57:38.160950653Z caller=images.go:111 component=sync-loop workload=myreg.io/my/image container=image repo=myreg.io/my/image pattern=glob:* current=myreg.io/my/image:release-v1-19-5-13 info="added update to automation run" new=myreg.io/my/image:develop-35ed5364 reason="latest develop-35ed5364 (2020-11-18 23:31:54.57459961 +0000 UTC) > current release-v1-19-5-13 (2019-09-17 05:07:18.451406646 +0000 UTC)"                                                                                                           
```

From the logs you can see that Flux is not using the correct pattern and is instead using `pattern=glob:*`.

Listing images confirms that Flux is not filtering image tags as expected:

```
$ fluxctl --k8s-fwd-ns my-ns list-images -w belron-test:helmrelease/my-app
WORKLOAD                        CONTAINER  IMAGE                                            CREATED
belron-test:helmrelease/my-app  image      myreg.io/my/image  
                                           '-> develop-35ed5364                             18 Nov 20 23:31 UTC
                                               develop--698c3358                            18 Nov 20 21:30 UTC
                                               develop-521e5f17                             18 Nov 20 13:05 UTC
                                               929dfb64                                     03 Nov 20 13:18 UTC
                                               adf7bb86                                     03 Nov 20 08:09 UTC
                                               11f5e261                                     30 Oct 20 12:51 UTC
                                               a8fc8885                                     30 Oct 20 06:00 UTC
                                               2ecaa0f7                                     29 Oct 20 13:48 UTC
                                               f84c0786                                     28 Oct 20 12:17 UTC
                                               e21e7399                                     28 Oct 20 11:55 UTC
```

**Additional context**

- Flux version: 1.21.0
- Kubernetes version: 1.14.0
- Git provider: GitHub
- Container registry provider: Azure

**Comment by Starefossen** [comment]
As pointed out by Stefan and Jonas in the Flux Slack Channel `image.image` is not a recognized variable format for the [automatic image detection](https://docs.fluxcd.io/en/stable/references/helm-operator-integration/#automated-image-detection) changing this to just `image` solved the problem for me 😄 

```yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/chart-image: glob:release-*
    fluxcd.io/automated: "true"
  name: my-app
  namespace: my-ns
spec:
  chart:
    name: my-chart
    repository: https://some-registry.io
    version: ^1.2.3
  values:
    image: myreg.io/my/image:release-v1-19-5-13
```
