### ISSUE TITLE
Automate single container in HelmRelease with multiple images

### ISSUE THREAD

**Issue by marcocaberletti** [fluxcd/flux#3379]
Hi,
I have a HelmRelase with multiple images; something like:

```yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: demo
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: demo
  chart:
    repository: my-repo
    name: helm-demo
    version: x.y.z
  values:
    app-01:
      image: repo-01:my-tag
    app-02:
      image: repo-02:my-tag
    app-03:
      image: repo-03:my-tag
```

With `fluxcd.io/automated: "true"`, all the containers are updated when a new image is pushed into the related registry, as expected.

Now, I would like to automate a single container (eg. `app-01`), and manage the update of the others "manually", using the command line (with `fluxctl release ... --update-image=....`)

Is it possible? How can I do that?

**Comment by kingdonb** [comment]
I am not sure of a straightforward way to accomplish this in Flux v1 and Helm Operator, (but I think the concern is better addressed in Flux v2's updated architecture for helm-controller!)

For Flux v1, the relevant documentation is here:
https://docs.fluxcd.io/en/1.21.1/references/automated-image-update/

and here
https://docs.fluxcd.io/en/1.21.1/references/helm-operator-integration/#filters

The limitation I think is that as you've discovered, "automated" is a binary flag and is either enabled or disabled on a per-resource basis since this annotation can only be placed once on each yaml manifest resource managed by Flux, which handles image automation. You can set extra-specific filters, and this may help you to still accomplish your goal on Flux v1.

For example if you set the filter down to something as specific as a glob or precise regex with no wildcard, matching the image that you have listed, this is a workaround. It should also work if this makes more sense for your use case, to set a filter that will never match any image tag; again a clumsy workaround. This is less than ideal when what you want is as you described, to manage independently multiple behaviors in a single YAML manifest. It requires repeating yourself a little bit more than is desirable, though it would seem to be a functioning solution that you could use in Flux v1.

In the Flux v2 image automation there is a first-class approach which I think is better designed in response to this issue, that is more workable, with fewer knobs, fewer opportunities for inconsistency than one may encounter using these workarounds.

https://toolkit.fluxcd.io/guides/image-update/#configure-image-updates

When image automation is enabled in the new Flux v2 architecture, the image reference in the YAML manifest is tagged with an "image policy marker" that is placed in a functional comment, like this one from the docs:

```yaml
spec:
  containers:
  - name: podinfod
    image: ghcr.io/stefanprodan/podinfo:5.0.0 # {"$imagepolicy": "flux-system:podinfo"}
```

That is a reference to an imagepolicy, and it is placed per-reference, (and it appears to me, this will help satisfy your issue!)
