### ISSUE TITLE
Incorrect image sorting

### ISSUE THREAD

**Issue by karlmuscat** [fluxcd/flux#3417]
**Describe the bug**

Image sorting seems to be incorrect for [reproducible builds](https://reproducible-builds.org/): 

```
WORKLOAD              CONTAINER       IMAGE                                    CREATED
test:deployment/test  test-container  xxx.dkr.ecr.eu-west-1.amazonaws.com/test
                                      '-> 1.0.0-test.98                        01 Jan 70 00:00 UTC
                                          1.0.0-test.99                        01 Jan 70 00:00 UTC
                                          2.0.0-test.98                        01 Jan 70 00:00 UTC
```
 Using `semver` filtering:
 
 ```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:*
```

**Expected behavior**

Versions follow the semver formatting, so I was expecting the ordering to be the inverse of the above.

**Additional context**

- Flux version: 1.21.1
- Kubernetes version: 1.15
- Git provider: Github
- Container registry provider: ECR
