### ISSUE TITLE
Flux sync-loop is failing with internal Error 

### ISSUE THREAD

**Issue by Bujail** [fluxcd/flux#3450]
**Describe the bug**

Flux sync-loop fails with internal error. Changes are not getting applied.

**To Reproduce**

Steps to reproduce the behaviour:

*Flux deployment yaml:*
```yml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: flux
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      name: flux
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/port: "3031"
      labels:
        name: flux
    spec:
      containers:
      - args:
        - --memcached-service=
        - --ssh-keygen-dir=/var/fluxd/keygen
        - --git-url=git@gitlab.com:xyz/infrastructure/clusters/stg.git
        - --git-branch=master
        - --git-label=flux
        - --registry-exclude-image=*
        - --manifest-generation=true
        - --listen-metrics=:3031
        - --git-readonly
        - --git-timeout=300s
        - --sync-timeout=30m
        image: docker.io/fluxcd/flux:1.22.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/flux/v6/identity.pub
            port: 3030
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: flux
        ports:
        - containerPort: 3030
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/flux/v6/identity.pub
            port: 3030
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          requests:
            cpu: "3"
            memory: 2Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/fluxd/ssh
          name: git-key
          readOnly: true
        - mountPath: /var/fluxd/keygen
          name: git-keygen
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry
      nodeSelector:
        nodegroup: agent
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: flux
      serviceAccountName: flux
      terminationGracePeriodSeconds: 30
      volumes:
      - name: git-key
        secret:
          defaultMode: 256
          secretName: flux-git-deploy
      - emptyDir:
          medium: Memory
        name: git-keygen
```

*All new changes should be applied to the cluster**

**Logs**

```
ts=2021-03-23T04:00:03.498726475Z caller=loop.go:108 component=sync-loop err="collating resources in cluster for sync: stream error when reading response body, may be caused by closed connection. Please retry. Original error: stream error: stream ID 36131; INTERNAL_ERROR"
ts=2021-03-23T04:00:03.500314177Z caller=loop.go:134 component=sync-loop event=refreshed url=ssh://git@gitlab.com/xyz/infrastructure/clusters/stg.git branch=master HEAD=1fab6b6fac9342a7944d9f59c56d6f184d14a0d6
ts=2021-03-23T04:00:34.430292113Z caller=loop.go:134 component=sync-loop event=refreshed url=ssh://git@gitlab.com/xyz/infrastructure/clusters/stg.git branch=master HEAD=1fab6b6fac9342a7944d9f59c56d6f184d14a0d6
ts=2021-03-23T04:07:11.5531765Z caller=sync.go:61 component=daemon info="trying to sync git changes to the cluster" old=d152f4eab76071b2fbbe00bd1860db5cd06d2a4d new=1fab6b6fac9342a7944d9f59c56d6f184d14a0d6
ts=2021-03-23T04:10:26.344102153Z caller=loop.go:108 component=sync-loop err="collating resources in cluster for sync: stream error when reading response body, may be caused by closed connection. Please retry. Original error: stream error: stream ID 36405; INTERNAL_ERROR"
ts=2021-03-23T04:10:26.345656977Z caller=loop.go:134 component=sync-loop event=refreshed url=ssh://git@gitlab.com/xyz/infrastructure/clusters/stg.git branch=feat/velero/encrypt HEAD=1fab6b6fac9342a7944d9f59c56d6f184d14a0d6
```

**Additional context**

- Flux version:  1.22.0
- Kubernetes version: 1.20.2
- Git provider: GitLab
- Container registry provider: GitLab

**Comment by kingdonb** [comment]
Thanks, can you provide some more information please? If this is a regression after upgrading, can you tell if it goes away when you revert to the previous version of Flux (if it was 1.21.2, or another version, please try backing down to prior version.)

Where is your Kubernetes cluster hosted, with what cloud provider (is it GKE?)

The error messages you listed aren't mentioned by any other reports I can find. I will do some research and get back to you.

In the mean time, please let me know if you are able to revert to the earlier version; whether it solves the problem to revert, or if the issue persists.

**Comment by Bujail** [comment]
Flux upgraded to v1.22.0 after getting the above INTERNAL error in v1.21.1. I tried v1.21.2 as well, but no luck.

At the beginning, we were running flux v1.17.1 and got the timeout issue( https://github.com/fluxcd/flux/issues/3049 ). By upgrading to v1.21.1 and removing `--sync-timeout` from arguments and adding `timeout` in .flux file fixed the issue temporarily. After some days, it started to report the INTERNAL error. As a test we upgraded to v1.22.0 but still we are getting the same error. 

Note:
Cluster is a vanilla deployment in AWS.  
The main Git repo will fetch base remote base repo while building.
Eg:
```yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ssh://git@gitlab.com/xyz/gitops-base.git/base/calico-v3.17.1?ref=v0.104.0

patchesStrategicMerge:
- calico-config-patch.yaml
```
