### ISSUE TITLE
Error re-connecting flux after cert-manager update

### ISSUE THREAD

**Issue by gerardgorrion** [fluxcd/flux#3454]
**Describe the bug**

When restore certificates from backup (updating cert-manager with below link: [https://cert-manager.io/docs/installation/upgrading/upgrading-0.16-1.0/](https://cert-manager.io/docs/installation/upgrading/upgrading-0.16-1.0/) ), whe update our certificates allocated in our repo (version v1alpha2 to v1) connected with flux, flux show error that can't manage this cert. Exported certificate with flux conf:

```
- apiVersion: cert-manager.io/v1beta1
  kind: Certificate
  metadata:
    annotations:
      fluxcd.io/sync-checksum: checksum1
...
```

and imported with:

```
- apiVersion: cert-manager.io/v1
  kind: Certificate
  metadata:
    annotations:
      fluxcd.io/sync-checksum: checksum1
...
```

Certificate on repo connected with flux:
```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: name-cert
spec:
  secretName: name-cert-secret
  dnsNames:
  - "ourdns.com"
  issuerRef:
    name: issuerRefName
    kind: ClusterIssuer
    group: cert-manager.io
```

**To Reproduce**

Steps to reproduce the behaviour:

1. Provide Flux install instructions
```
    fluxctl install \
    --git-user=delivery \
    --git-email=cd@sys.com \
    --git-url=https://user:$GPASS@ourgit.git \
    --git-path=path \
    --git-label=label \
    --namespace=flux | kubectl apply -f -
```
2. Provide a GitHub repository with Kubernetes manifests

Kubernetes 1.17 on EKS AWS

**Expected behavior**

When update cert manager version and restore certificate with the backup, we want to re-connect our certificate repo with flux.

**Logs**

```
ts=2021-03-31T08:26:25.698765334Z caller=sync.go:606 method=Sync cmd="kubectl apply -f -" took=302.16161ms err="running kubectl: exit status 1, stderr: The certificates \"name-cert\" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update" output=

ts=2021-03-31T08:26:25.698878272Z caller=sync.go:231 component=daemon err="default:certificate/name-cert: running kubectl: exit status 1, stderr: The certificates \"name-cert\" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update;
```

**Additional context**

- Flux version: 1.21.0
- Kubernetes version: 1.17.12
- Git provider: bitbucket
