### ISSUE TITLE
Helm ValuesFiles not updated during reconciliation

### ISSUE THREAD

**Issue by jonerer** [fluxcd/flux#3556]
### Describe the bug

Thanks for a great piece of software! I'm having a blast with it.

I have a HelmRelease where I load the values from normal helm value files. According to https://fluxcd.io/docs/components/helm/helmreleases/ the way to do that is to put them in the Spec, like so:

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my_helm_release
  namespace: agile
spec:
  interval: 5m
  chart:
    spec:
      chart: cluster/charts/my_helm_chart
      version: "0.1.2"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
      valuesFiles:
        - cluster/charts/my_helm_chart/values.yaml
        - cluster/charts/my_helm_chart/values_prod_tag.yaml
```

This works perfectly file, loading in the values.yaml file and adding values_prod_tag.yaml on top. **But** it doesn't update the helm release on reconciliation if either of the values files are changed. Reconciliation will only pick up the changes if I bump the "version" number on the chart.

The reason why I'm using normal helm values.yaml-files instead of putting all of my values under a `values`-block outside the `spec` is twofold:

1. I want to be able to easily update the values_prod_tag.yaml-file in my CI pipeline, to specify what image tag to use; updating inside a k8s resource file is trickier
2. I want to be able to use the standard `helm` CLI tools for debugging/development. In this case, I could do `helm template my_helm_release . -f values_prod_tag.yaml`  to see the output and validate or so. Having my values inside a k8s resource file (like a ConfigMap or sth) would be harder

### Steps to reproduce

Install a helm chart from a git repo, like so:

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my_helm_release
  namespace: agile
spec:
  interval: 5m
  chart:
    spec:
      chart: cluster/charts/my_helm_chart
      version: "0.1.2"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
      valuesFiles:
        - cluster/charts/my_helm_chart/values.yaml
        - cluster/charts/my_helm_chart/values_prod_tag.yaml
```

Commit changes to "values_prod_tag.yaml"

See that the installed helm chart isn't updated (by checking `helm list` and seeing the revision number not be bumped)

### Expected behavior

Updating a values file referenced by a HelmRelease should re-render the helm chart and update the installed helm release upon reconciliation.

Alternatively, if there is some other more "Flux"-y way I would be very interested to learn!

### Kubernetes version / Distro / Cloud provider

Rancher rke 1.20.4

### Flux version

Flux version 0.17.2

### Git provider

Github

### Maintenance Acknowledgement

- [X] I am aware of Flux v1's maintenance status

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
