### ISSUE TITLE
Flux automate image updates issue

### ISSUE THREAD

**Issue by lgs** [fluxcd/flux#3562]
### Describe the bug

We have image pools that starts with `master-` and `develop*-` tags. So after every image build, we want automatically update in our flux-patch.yaml related service image tag with the newest one. 

We have implemented this code below with the regexp definition, but anyway when the newest images are coming, flux is updating it with the wrong images.

This is our flux-patch.yaml implementation (on GitHub):

```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/chart-image: regexp:^((^master|^develop[A-Za-z]*)-(\d+)(?![A-Za-z])*)$
    fluxcd.io/automated: "true"
  name: my-service-name
  namespace: my-namespace
```

The regex error we get can be seen here:

![InkedAutoImageUpdate_LI](https://user-images.githubusercontent.com/1573/138849305-75bdaaaf-b37e-46f3-a755-2eeaec6dd29d.jpg)

### Steps to reproduce

Run the regex like reported in the following "Expected behavior" form field.

### Expected behavior

 With this `regexp ^((^master|^develop[A-Za-z]*)-(\d+)(?![A-Za-z])*)$`, we are expecting to take only `develop-NUMBER`, `master-NUMBER`, `development-NUMBER` images. So for example it should update `develop-15` to `develop-16`, `master-5` to `master-6`, `development-10` to `development-11`.

  Here the results of auto deployment and our regular expression:
<img width="1051" alt="Regex" src="https://user-images.githubusercontent.com/1573/138722306-f72c0026-1cb7-4861-b1c5-d25da5585c0e.png">

### Kubernetes version / Distro / Cloud provider

Amazon EKS 1.18

### Flux version

flux:1.21.0

### Git provider

GitHub 

### Container Registry provider

Harbor

### Maintenance Acknowledgement

- [X] I am aware of Flux v1's maintenance status

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
