### ISSUE TITLE
Can Kustomize use env substitution for a non kubernetes kind?

### ISSUE THREAD

**Issue by rodrigoscferraz** [fluxcd/flux#3575]
### Describe the bug

I guess this is not an issue but i don't know where i can put my doubts.
I have an env file with some key value pairs and i want to use one of this values inside a file that is a yaml file but not a Kubernetes kind...something like this:
`objstore.yaml`
```
type: s3
config:
  bucket: ${THANOS_OBJSTORE_BUCKET}
  endpoint: s3.us-west-2.amazonaws.com
```
Is it possible?

My kustomize file looks like this:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
secretGenerator:
  - name: thanos-objstore-config
    files:
      - objstore.yml
generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: kustomize-env
    namespace: flux-system
    envs:
      - env
```

Basically i'm passing the file to secretGenerator but each environment (prod, staging,etc) have a different bucket name, so i need to set this dynamically. So i used an env file, and works fine for Kubernetes Kinds but when i tried to do the same for the file above the secret generated had exactly the value ${THANOS_OBJSTORE_BUCKET} instead of the value in env file.

### Steps to reproduce

Use secretGenerator with a non kubernetes kind

### Expected behavior

I want to use env on non kubernetes kinds.

### Kubernetes version / Distro / Cloud provider

1.22

### Flux version

1.23

### Maintenance Acknowledgement

- [X] I am aware of Flux v1's maintenance status

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
