### ISSUE TITLE
[question] Flux on spot/preemptible instances

### ISSUE THREAD

**Issue by PatrykGala** [fluxcd/flux#3583]
### Describe the bug

Hi,
I'm using Flux v2 with GKE autopilot cluster, for test/dev environments I would like to use Flux with spot instances. Is the setup reliable? Are flux images fault tolerant?

### Steps to reproduce

spot_instances.yaml

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: not_used
  namespace: flux-system
spec:
  template:
    spec:
      nodeSelector:
        cloud.google.com/gke-spot: "true"
```

kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
  - path: spot_instances.yaml
    target:
      kind: Deployment

resources:
  - gotk-components.yaml
  - gotk-sync.yaml
```

### Expected behavior

Flux should works correctly on Spot instances.

### Kubernetes version / Distro / Cloud provider

1.21.5-gke.1302

### Flux version

# Flux Version: v0.24.1

### Maintenance Acknowledgement

- [X] I am aware of Flux v1's maintenance status

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
